DFHack/scripts

autofarm.rb

This is a fix I wrote years ago but never bothered to commit that allows autofarm to handle crops with growdurs that exceed a single season. There are none in standard DF, but some community mods add such crops.

autofarm: handle crops with long growdurs

---

forum-dwarves.lua
gui/choose-weapons.lua
gui/clone-uniform.lua
gui/guide-path.lua
gui/liquids.lua
gui/mechanisms.lua
gui/power-meter.lua
gui/rename.lua
gui/room-list.lua
gui/settings-manager.lua
gui/siege-engine.lua
gui/workshop-job.lua

Scripts now have keybinding info auto-generated for build-time HTML docs.  See DFHack/dfhack#972
At runtime, more reliable information can be sourced from the `hotkeys` or `keybinding` commands, or of course inspecting the init files.  See DFHack/dfhack#963

Edit docs to match new keybinding directive

---

ban-cooking.rb

1) All ban-able items must be cook-able to be banned.
2) Checks to ensure that kitchen.exc_types[index] exists before attempting to write to it.
-- Ran into issues with the original script attempting to ban non-cookable plant items, which lead to mismatches in the length of the kitchen.exc_types versus the others.
3) Change the index variable in the ban_cooking function from a key lookup to a numerical index value
4) Added subtype parameter to allow handling of tree fruits.
5) Added printing of the item that has been banned.
6) Seeds banning bans the seeds from being cooked now.
-- Required that banning not be for seed producers that can't be brewed into alcohol for logistic/time reasons
7) Fixed mill and thread banning, as they referenced local variable 'm', but didn't set it.
-- I don't …

Proposed fixes for ban-cooking.rb

---

modtools/syndrome-trigger.lua

New arg added: **-synclass**
Allows a target SYN_CLASS to be specified instead of a syndrome name. This allows modders to specify an effect for a bunch of syndromes at once, hence saving time. It can also be used with syndromes like the generated vampire and werebeast curses, which lack names but have syndrome classes.

syndrome-trigger updated to work with syndrome classes

---

modtools/create-unit.lua

occasionally the original point of creation has no map data (its below the bottom floor of hell, and therefore does not exist).
figured that since the point it tries to create the unit is a series of simulated actions that moves through the arena spawn unit menus, that before opening the menu, you could just move the cursor there, if location was set, it worked.  
also added an argument to set the unit to civ_id and group_id of the the fort, to reduce on the verbose of most commands (nearly every use I have for create-unit is set to the civ and group of the fort...).  
moved the civ_id change closer to the point of actually creating the unit,  thought about moving it into the createNemesis function... but didn't.
corrected error involving out of bounds vector, on old forts in the setting …

fixed a few issues

---

gui/create-item.lua

current behaviour creates unusable gloves (they have no handedness defined), and boots and gloves are created lonely. Creating them in pairs that are actually usable is probably better default behaviour.

gui/create-item.lua: create matching boots and gloves with handedness

---

gui/dfstatus.lua

I made my fort walls out of logs (heresy I know) and the count on logs was ~3k.  When I added the "not item.flags.construction" flag I went down to 200 available logs.
68x59 square wall, Hollow with a 64x55 inner wall.  Three high with floors on the inside and top.

Should not count logs used in constructions

---

view-item-info.lua

```
df_43_05_win/hack/scripts/view-item-info.lua:279: bad argument #1 to 'decode' (material id is not a number)
stack traceback:
[C]: in field 'decode'
D:\Games\df\df_43_05_win/hack/scripts/view-item-info.lua:279: in global 'get_plant_reaction_products'
D:\Games\df\df_43_05_win/hack/scripts/view-item-info.lua:296: in global 'GetFoodPropertiesStringList'
D:\Games\df\df_43_05_win/hack/scripts/view-item-info.lua:347: in global 'get_all_uses_strings'
D:\Games\df\df_43_05_win/hack/scripts/view-item-info.lua:402: in function <D:\Games\df\df_43_05_win/hack/scripts/view-item-info.lua:382>
```
`GetReactionProduct` return value used incorrectly at [278](https://github.com/DFHack/scripts/compare/master...OwnageIsMagic:patch-1#diff-3cbbb7dbf10255f7809c8745fc5ffa30R278) and …

view-item-info: fix error for `CHEESE_MAT`

---

devel/export-dt-ini.lua

Dwarf Therapist no longer use the ini to get string offsets on windows (other platforms did not use that).

export-dt-ini: remove windows string offsets

---

modtools/create-unit.lua

Fixed invalid reference to `current_soul.unit_id` in the `domesticate` function

Minor fix to modtools/create-unit

---

view-unit-reports.lua

Script to solve the problem of having to manually find combat reports in 'r' for specific unit.
Current unit is unit near cursor in 'v', selected in 'u' list,
unit/corpse/splatter at cursor in 'k'. And newest unit with race when
'k' at race-specific blood spatter.
If this is considered useful enough it can be added to dfhack.init-example in the following scopes (I would prefer it as a single keybinding since 4 lines is too much clutter)
```
keybinding add Ctrl-Shift-R@dwarfmode/ViewUnits view-unit-reports
keybinding add Ctrl-Shift-R@unitlist view-unit-reports
keybinding add Ctrl-Shift-R@dwarfmode/LookAround view-unit-reports
keybinding add Ctrl-Shift-R@textviewer view-unit-reports
```

view-unit-reports: View combat reports for currently selected unit

---

modtools/item-trigger.lua

Previously, item-trigger's inventory update checks only differentiated between equipping and unequipping items. This means that something like
modtools/item-trigger -itemType ITEM_HELM_CAP -onEquip -command [ foo ]
would trigger foo both in cases where a cap was being worn, and in cases where it was simply being held in the unit’s hand.
With this update, the user will now be able to specify the inventory mode alongside onEquip and onUnequip to allow for greater selectivity. Taking the above example, if we wanted to trigger foo only in cases where a cap was being worn, we could specify this via
modtools/item-trigger -itemType ITEM_HELM_CAP -onEquip 2 -command [ foo ]
or
modtools/item-trigger -itemType ITEM_HELM_CAP -onEquip [ 2 ] -command [ foo ]
where ‘2’ is the mode type corresponding to …

item-trigger update: specify inventory mode

---

modtools/item-trigger.lua

A significant rewrite allowing the user to specify any combination of itemType, material and contaminant.
Previously, only one of the above could be used at a time, which greatly restricted the script's flexibility and limited its usefulness to modders.
Also fixed the outdated(?) creature/plant material token format demonstrated in the -help printout, and added a few more examples.

item-trigger: support multiple conditions

---

full-heal.lua

- fix: clothed units no longer exhibit melting body parts after being healed
- fix: resetting unit.status2.limbs_fly_count allows wounded creatures to fly again
- added several missing counters and flags
- added capacity to clear wounds stored in historical figure data
- removed the buggy CleanSelf job assignment

full-heal: several fixes

---

exterminate.rb

Exterminate.rb was updated to include arguments 'this', 'it', 'target', and 'selected'. This pull updates the command's help text.

Update exterminate.rb documentation

---

bodyswap.lua

A revived version of the long defunct "adv-bodyswap" with some added functionality.
This script allows the player to swap their control over to any unit present on the map in adventure mode. Targets are specified either via their unit id or through UI selection prior to running the script (as detailed in the script usage documentation). Unlike previous iterations, units lacking nemesis or historical figure data (such as wild animals) are valid and safe targets, as the script creates this data when it is missing using functions from modtools/create-unit.

Added bodyswap.lua

---

add-recipe.lua

(had to resubmit the PR because I suck & messed up my branches; the previous PR and related discussion is [here](https://github.com/DFHack/scripts/pull/60))
You know how sometimes you can't craft high boots? This is because civilizations pick the different types of armour they can craft randomly during worldgen, and this is done per slot/type, so sometimes you end up with civilizations that are satisfied with low boots and never go higher. Normally there's no fix to this other than editing entity_default.txt in the raws before worldgen, or just embarking again as a different civ and hoping that they're more cultured.
This script helps with that. It can enable unknown crafting recipes, such as high boots, face veils, or thongs, after embark. It can also enable items that can normally never …

add-recipe

---

deathcause.rb

One case of df-structures issue 247 (although no list has been seen yet...).
I've tested it on a random DFFD fortress and have seen it behave the same as the original version on most of the things in the refuse/corpse stockpile as well as on the dead units list.
The "not at hist fig" message wasn't produced in any of the cases, however, nor did I find any body parts belonging to living creatures to actually test the flag change.
However, during the testing I found using deathcause on a living unit resulted in it being dead due to an unknown cause, which led to the changes to the display_death_unit operation, and that change worked correctly, i.e. claiming the unit wasn't dead, compared to the original, which (still, of course), claimed an unknown death cause. Given that the flag change …

Deathcause

---

adaptation.rb
devel/export-dt-ini.lua
emigration.lua
exterminate.rb
fix/dead-units.lua
fix/feeding-timers.lua
fix/stuck-merchants.lua
full-heal.lua
gui/room-list.lua
gui/unit-info-viewer.lua
warn-starving.lua

Adjusted usage of flags1.dead to use flags2.killed in scripts that appear to use the flag to target dead unit rather than inactive ones.
The DT script has updated the comments produced to better reflect the current understanding, but not any address info.
The scripts have gone through rudimentary testing to see that they still work (to e.g. catch typing errors), but not anything beyond that.
It can be noted that gui/unit-info-viewer.lua produced a nonsensical output of strength:agility being in cubic decimeters, resulting in a 1.5:1.1 cubic meter dwarf, but I don't intend to do anything about it beyond this comment.
Relates to df-structures issue 247.
Link:  DFHack/df-structures#247

Dead misuse

---

digfort.rb

If csv has extra empty columns digfort may try to look far outside
designated area. To avoid going outside map limits empty cells needs to
be checked before accessing.
To help user understand the issue I decided to add error message when
designation goes outside map limits.
Fixes 1179

Improve digfort empty cell handling

---

extinguish.lua

This script kills fires affecting units, items, buildings and plants, replacing burning tiletypes with the appropriate extinguished types where necessary and resetting temperatures to a safe level. A target location can be selected using the cursor or specified via its x,y,z coordinates. Alternatively, the -all argument can be used to put out fires across the entire map.
closes DFHack/dfhack#1358

Added extinguish.lua

---

tame.lua

This script takes the highlighted unit and attempts to set the level of training, and toggles the `tame` flag as necessary.
```
tame
====
Tame and train animals.
Usage: `tame -read` OR `tame -set <level>`
:0: semi-wild
:1: trained
:2: well-trained
:3: skillfully trained
:4: expertly trained
:5: exceptionally trained
:6: masterfully trained
:7: tame
:8: wild
:9: wild
```

Adds tame.lua a script for taming/training animals

---

bodyswap.lua

As per the PR title, this minor change makes it possible to bodyswap in arena mode when controlling a unit. Testing has shown that this script can be used copiously in arena mode with no apparent ill effects. Also included is a trivial change in documentation.

bodyswap: made script useable in arena mode

---

unretire-anyone.lua

Running this script during adventure mode setup pulls up a gui from which the user can select a nemesis to add to the "Specific Person" list on the menu. This effectively allows the user to "unretire" and play as any viable historical figure in adventure mode.

Added unretire-anyone.lua

---

modtools/create-unit.lua

- `he` was being passed on to createFigure() as nil, resulting in missing civilisation entity associations in the historical figure data
- Also removed the `compute_health` flag, thereby fixing an issue wherein newly spawned citizens were being immediately carted off to hospital. This flag causes the generation of the unit's health structure to occur a tick after being spawned, which results in the generation of a "Recover Wounded" job if the unit in question is a fortress citizen. `unit.health` is very often nil until a unit is injured, and `compute_health` doesn't appear to be useful for provoking body size recalculation or the like, so the inclusion of this flag appears to have been unnecessary.
- In addition, made nameless creatures created in arena mode retain their race-number name …

create-unit: several fixes

---

bodyswap.lua

Historical figure IDs are normally added to/removed from `df.global.ui_advmode.companions.all_histfigs` throughout the course of the game whenever companions join/leave the adventurer. The other stuff in `df.global.ui_advmode.companions` appears to be set/updated when the companions screen is loaded, and therefore probably doesn't require changing.

bodyswap: update list of companion histfig IDs

---

exterminate.rb

Add a new special case caste called `enemy` so one can target non-fortress guests i.e. goblin invaders  without the tedium of doing 1 by 1 or killing citizens of your fort that happen to be goblins.
I have done limited testing of this with invaders and undead and things but this is feature complete I think.
Also it updates the help text to indicate how to use this feature.

Add special case to exterminate to only target hostile members of a race

---

digfort.rb

when checking for map limits digfort counts each individual line towards height (y) of the designation, even when they are spread among multiple z-levels
this would make it find the tallest (y) level and use that to check, the same way it does with width (x)

account for changes in z

---

linger.lua

This script is intended to restore the "reincarnate" feature that was lost several years ago when dfusion was removed. It is meant to be run after the adventure mode player character has been killed by another unit, and will call the bodyswap script to shift player control over to said unit.
Closes DFHack/dfhack#884.

Added linger.lua

---

modtools/create-unit.lua

Previously, when the script created a historical figure + nemesis record, the historical figure's `unit_id2` record was being set to the unit's id, rather than the nemesis id.

Update create-unit.lua to use nemesis ID

---

modtools/deep-embark.lua

I wrote this following a modder's request for a script that enables players to embark underground. It does this by detecting blocks corresponding to the specified depth (any of the three cavern layers or the underworld), finding one that has a sufficient number of valid walkable tiles in it, and teleporting starting units and equipment there. I developed a workaround for triggering the game to properly reveal tiles centered around the target location which involves placing a glowing barrier tiletype and making it disappear; I'm unaware if there's a more straightforward method to do this, but it works quite well. This script requires the user to set up an `onMapLoad.init` file as detailed in the `-help` printout.

Added deep-embark.lua

---

combat-harden.lua

This script can be used to alter the combat_harden value of a unit (or a whole fort), which effects the emotions that a unit feels when witnessing death (to the point where they feel nothing).
(I originally made this to publish with my own list of scripts, but I figured it was something that might have wide enough appeal to go into DFhack proper.)

Added combat-harden.lua

---

exportlegends.lua

Support for Legends Viewer (and its siblings). Note that no attempts to add 0.47.X additions has been made. That will have to be done by someone more familiar with what needs to be exported separately and what the standard XML provides just fine.
I forgot to add that this fixes DFHack/dfhack#1493.

Added creature_raw names and flags

---

deep-embark.lua

- the script can now be run directly from the DFHack console at any point whilst setting up an embark
- modders should now call this from onLoad.init instead of onMapLoad.init
- a previously set depth can now be overridden by running the script from console again
- added `-clear`, which re-enables normal surface embarks
- updated documentation

deep-embark: implemented proper console support

---

repeat.lua

This allows viewing what commands are set to repeat (by their names).
The idea is to help novice users (like me) to explore what a preinstalled `dfhack` (like from _Lazy Newb Pack_) is doing.

Add `list` option to repeat.lua

---

modtools/create-unit.lua

**new arg**: `-duration`
Enables the user to set a time limit on the existence of created units. The unit vanishes in a puff of smoke once the specified number of ticks has elapsed.
**new arg**: `-locationRange`
Randomly spawn the unit anywhere within a specified number of x, y, z tiles away from the target location, if possible.
**new arg**: `-locationType`
Enables users to specify what counts as a valid tile for unit spawning when used with `-locationRange`. Defaults to `Walkable`, also takes `Open` and `Any`. Units are not created if no valid tiles are present at the location indicated (I inititially made the script place units at the `-location` coordinates in this scenario, but I think that this makes more sense).
These additions are meant to emulate the `IE_TIME_RANGE` and …

modtools/create-unit: added -duration, -locationRange, -locationType

---

on-new-fortress.lua
onNewFortress.lua

The script only checks if `df.global.ui.fortress_age` is `0` and if it isn't, does nothing.
Use this in `onMapLoad.init` with f.e. `ban-cooking`:
onNewFortress ban-cooking tallow; ban-cooking honey; ban-cooking oil; ban-cooking seeds; ban-cooking brew; ban-cooking fruit; ban-cooking mill; ban-cooking thread; ban-cooking milk;
This may make #119 unnecessary.

onNewFortress: runs commands only in a newborn fortress

---

once-per-save.lua

Runs commands the way `multicmd` does, but only unless not already ran once in current save.
Use this in `onMapLoad.ini` with f.e. `ban-cooking`
once-per-save ban-cooking tallow; ban-cooking honey; ban-cooking oil; ban-cooking seeds; ban-cooking brew; ban-cooking fruit; ban-cooking mill; ban-cooking thread; ban-cooking milk;
Only successfully ran commands are saved.
I would love to make this per-fortress instead of per-save but have no idea how.

once-per-save.lua: like multicmd but only if not already ran

---

reveal-hidden-units.lua

A simple script which exposes all sneaking units. This is primarily intended to help adventure mode players deal with [an annoying bug in the new version](http://www.bay12games.com/dwarves/mantisbt/view.php?id=11299), but it's also useful for uncovering ambushers in fortress mode.

Added reveal-hidden-units.lua

---

devel/export-dt-ini.lua

https://github.com/DFHack/df-structures/pull/366 re-add creature_interaction_effect_body_transformationst.race which was removed in https://github.com/DFHack/df-structures/commit/c18cbeb28a8fb4f67e63db0547ac4b221c6903b6 but as a vector instead of an int32_t. Change the name of the offset so DT can see the changed type and adapt.

export-dt-ini: change offset name to reflect changed type

---

resurrect-adv.lua

Written following a request on the forums. Essentially a wrapper for `full-heal.lua`, which most adventure mode players have difficulty using on their player character once dead as it's impossible to select the unit and few know how to obtain the relevant unit ID.
Alternatively, we might modify the latter script to allow it to target adventurers specifically (maybe allow users to specify 'ADVENTURER' in the `-unit` argument or add a separate arg).

Added resurrect-adv.lua

---

exportlegends.lua

entities:
- deities are listed in historical_entity:unknown1b:deities rather than :worship
- export deities and weapons for entity type 'militaryunit' (= mercenary group)
- use new guild_professions from DFHack/df-structures@1cb6a65  
regions:
- evilness is good/evil/neutral
- force_id is hfid of the associated 'force'

exportlegends: export more details for entities and regions

---

workorder.lua

It always annoyed me there is no easy way to automate wool and milk production: there is no good trigger condition we can use (AFAIK). Additionally, while I appreciate the `workflow` plugin, I personally feel it shouldn't be necessary anymore with work order conditions from vanilla DF.
So here it is, consisting of 2 parts:
1. a core functionality to queue manager jobs (*any* jobs, like `orders`-plugin);
2. functions to count creatures that can be milked or sheared.
Current most useful use-case:
```
repeat -time 1 -timeUnits days -command [ workorder ShearCreature ] -name autoShearCreature
repeat -time 1 -timeUnits days -command [ workorder MilkCreature ] -name autoMilkCreature
```
If no amount is given the work order is only created if there are no open orders exceeding the amount to be …

workorder.lua: queue work orders ([j]-[m]-[q]); be smart about milk/shear creature orders

---

modtools/create-unit.lua

Improvement:
- added `-equip`, which allows items to be created and automatically equipped onto units as part of the spawning process.
This lets arena mode logic handle everything. Item sizes, which body part a particular item should be placed on, the handedness of gloves/footwear, the way clothes are layered relative to one another, assessing whether or not a unit is physically able to equip a particular item, etc. As such, this approach has clear advtanges over `modtools/create-item` + `modtools/equip-item`, at least with respect to equipping newly spawned units. Arena mode does however come with some limitations at present, such as an inability to set item quality or to place arrows into quivers.
I tried to make this work in a manner that should be easy for raw modders to understand, …

modtools/create-unit: added -equip

---

exportlegends.lua

The claims-tag closes on the same line.
Examples from before change:
```
<claims>                </claims>
```
or
```
<claims>20,7|20,9|21,7|21,9|21,10|           </claims>
```

Removed unneeded tabs in xml

---

gui/load-screen.lua

I noticed that whenever I selected a game to load, the timestamp had one letter truncated; in my case the box looked much like this:
The timestamp is meant to be NZST, not NZS.

Changed width so a four-letter TZ name can fit

---

workorder.lua

`OneTime` corresponds better with script intention, see [forum discussion](http://www.bay12forums.com/smf/index.php?topic=175717.msg8148008#msg8148008).

workorder: default frequency OneTime from Daily

---

gui/gm-editor.lua

Depends on dfhack/dfhack#1543
This currently replaces the current `i` key functionality with a call to `push(ref_target_type.find(id))` if the ref-target type is available; otherwise, the current functionality with a dropdown allowing a type to be selected is preserved. I'm debating whether to allow something like `shift-i` to continue to show the dropdown in all cases, in case users really want to override the ref-target or something.
Screenshot:

Add ref-target support to gui/gm-editor

---

changelog.txt
digfort.rb

- rewrite docs to prefer ',' over ';' as the csv separator to align with fortplan implementation (both separators still work).
- document interpretation of 'd' according to the current implementation
- remove initial double quote characters to allow .csv files that contain comments and were exported from spreadsheets to work
- replace Windows-specific "Dwarf Fortress.exe" in docs with platform-neutral "dfhack.init" as a "you're in the right directory" marker
- properly increment the y count for lines that only include commas

digfort: compat with exported .csv, fix y incr

---

exportlegends.lua

Fixes DFHack/dfhack#1554.
Fixes DFHack/dfhack#1557
It turned out "df_enums" can't handle enum types whose definitions are buried inside structs, so that case was handled separately.

removed some 'null' entries, converted enum numbers to strings

---

gui/advfort.lua

It's not ideal, but that is how df in fort mode works. Until you do something else the job hangs. Maybe a low priority TODO
Fixes https://github.com/DFHack/dfhack/issues/1611

advfort: Fix Operate Pump job

---

add-recipe.lua
changelog.txt

Right now add-recipe only lets you add recipes for weapons or armor, but not tools. I see no reason why this script shouldn't let you add recipes for tools, so I did just that.
It's particularly useful when you're playing with a modded civ, and then you find out only after starting a new fortress that you don't have stuff like minecarts or stepladders when you want them. It can also let you add recipes for procedurally-generated instruments.
Plus, I took the chance to improve the error messages a bit. Instead of letting the script throw normal LUA error messages when you give it bad arguments, I made it print how to use the script. Or a short error message when you get the name of an item wrong, so you at least know the script ran.
Also, I'm a noob at this, so sorry in advance if I …

Add tools to add-recipe, some error message improvements

---

changelog.txt
exportlegends.lua

Fixes https://github.com/DFHack/dfhack/issues/1416
If no folder name given, default is of similar pattern to `region1-00125-01-01`
`exportlegends all` will use default path
`exportlegends all myfolder_name` will create and use the 
"myfolder_name" folder
`exportlegends all .` will not put the files in a folder. (tested on 
linux)
This works for all arguments.
Tested on Linux and works fine.
**TODO: Test this on windows systems.** It should work but it should also be tested.

Exports legends into folders

---

changelog.txt
internal/quickfort/build.lua
internal/quickfort/common.lua
internal/quickfort/dig.lua
internal/quickfort/place.lua
internal/quickfort/query.lua
quickfort.lua

DFHack/dfhack#499 High-level structure, help text, and input validation.
Each PR for this script should be release-ready in that functionality will have been tested and unimplemented features will display explanatory error messages instead of just erroring out.
I have PRs queued up for settings management, file listing, tokenization, and dig blueprint functionality. I'll submit PRs one a time so review feedback can be focused and so no two open PRs depend on one another (github doesn't really support a chain of PRs that build on one another -- the diffs will be against the target repo instead of the parent PR)

quickfort script skeleton

---

quickfort.lua

DFHack/dfhack#499 Implement quickfort list functionality, including .csv file tokenization (so I can read the modeline in the first cell)

Quickfort list

---

internal/quickfort/list.lua
internal/quickfort/parse.lua

DFHack/dfhack#499 
- use mtime instead of md5hash for update checking
when I originally wrote the list cache, I saw that there was no way to get the file modification time from lua, but I saw the md5hash function and used that. in reqscript I saw how we get the mtime, so I'm switching to that since it's faster and has effectively the same functionality.
- chomp trailing newlines from input
I've discovered that when tokenizing csv file input, the last cell on a line includes the newline character. chomp it off before parsing.
- some fixes to documentation and a change from error() -> qerror()

Quickfort list and parse fixes

---

internal/quickfort/build.lua
internal/quickfort/building.lua
internal/quickfort/place.lua
quickfort.lua

DFHack/dfhack#499 Implement build logic for the quickfort script
The algorithmic logic is just a refactored and generalized form of the place logic. A side effect of the generalization is the improvement to stockpile placing where too-big stockpiles are split into multiple stockpiles instead of just being cropped.
I condensed decision-making properties for all buildings into a giant table structure. It works, but it is huge and unwieldy. If there is a better way to do this, I'd like to hear it : )
All buildings are tested to work with the internal constructBuilding() function. I was pleasantly surprised that it handles finding appropriate materials automatically and integrates wtih buildingplan.
The current code has some limitations that I plan to address in a future PR:
- weapon and …

Quickfort build

---

internal/quickfort/common.lua
internal/quickfort/dig.lua
internal/quickfort/list.lua
internal/quickfort/set.lua
quickfort.lua

- deprecate the force_interactive_build setting since I'm not sure how or when I would implement such a feature, and I don't want the setting to cause confusion
- update the help docs
- handle deprecated settings, type check settings when they are set, and pretty-print the settings list
- clarify the wording in the list output for cursor start comments

Deprecate unimplemented settings and update quickfort documentation

---

internal/quickfort/aliases.lua
internal/quickfort/keycodes.lua
internal/quickfort/parse.lua
internal/quickfort/query.lua
quickfort.lua

DFHack/dfhack#499 Implement query mode logic for the quickfort script
I have a couple questions for this PR:
1) I use a "wiggle the cursor" technique to get the UI to recognize the building underneath the cursor after I set the cursor position. This feels hacky, though. Is there a better way to do this? I've tried:
- DwarfOverlay:simulateCursorMovement
- DwarfOverlay:selectBuilding
- setting the ui.main.mode to something else then back to QueryBuilding
but nothing else seems to work.
2) Is there currently a way to sleep in a Lua script? I could wire it up through LuaApi if not.
After this PR, the quickfort script can be a reasonable replacement for python quickfort. There are still some advanced features I have yet to support, like construction material labels and blueprint …

Quickfort query

---

internal/quickfort/aliases.lua
internal/quickfort/build.lua
internal/quickfort/building.lua
internal/quickfort/common.lua
internal/quickfort/dig.lua
internal/quickfort/place.lua
internal/quickfort/query.lua
quickfort.lua

A hodgepodge of improvements and fixes for problems found while playtesting. Feedback requested for my decision to default stockpile wheelbarrows to 0. Is this controversial? The wiki suggests that wheelbarrows are a net loss for a fort. The player can still change the default in the quickfort.txt config file. The alternative is to default to 1 and require players who want to set it to 0 to use query mode. The problem with that, though, is the interface for setting wheelbarrows in query mode differs based on whether you have the DFHack tweak max-wheelbarrow enabled. And if you do have the tweak enabled, The issue with this, I've found, is that interacting with DFHack input prompts (like the one for setting the number of wheelbarrows) makes query mode unreliable. I'm …

Fix issues found while playtesting the quickfort script

---

ban-cooking.rb

Apparently the casing of enums generated for ruby changed causing a breakage in this script. This change updates the references to the new values
This will fix DFHack/dfhack#1623

Fix various ban-cooking commands

---

internal/quickfort/build.lua
internal/quickfort/common.lua
internal/quickfort/dig.lua

more fixes for bugs found during playtesting:
- fixed tile validity checking for down stairs and channeling (it wasn't allowing digging through saplings and bushes, but it was incorrectly allowing channeling through tree trunks)
- fixed the parser mistaking key sequences with 'x's in them for the extended area syntax: keys(WxH).

Quickfort playtesting fixes

---

internal/quickfort/command.lua
internal/quickfort/list.lua
internal/quickfort/parse.lua
quickfort.lua

use the API and libraries in DFHack/dfhack#1620 to implement reading blueprints from xlsx files. Refactor the blueprint reading logic to handle both csv and xlsx input.
also rename the sheet parameter from -s|--sheet to -n|--name to support more general naming in the future (I'm thinking ahead for multiple blueprints sections per csv file or spredsheet sheet)

quickfort xslx support

---

internal/quickfort/build.lua

use buildingplan to manage the building types that it handles. Eventually, I'd like to extend buildingplan to handle all building types, but this is much better than nothing.

use buildingplan to manage plannable buildings for quickfort

---

quickfort.lua

let the documentation reflect that quickfort is now feature complete.

remove references to quickfort being a pre-release

---

internal/quickfort/build.lua

the only time we can't is when the building is a custom type since our material customizations don't get applied correctly for custom types.

quickfort: set the item vector when we can for efficiency

---

internal/quickfort/aliases.lua

it seems that 'r+' is in prevalent usage to mean "make this a room", even though the actual UI key sequence is 'r+{Enter}'. Our own blueprints plugin generates 'r+' blueprints! This PR adds support for this convention so existing blueprints are not suddenly invalid.

alias 'r+' to 'r+&' in quickfort query blueprints

---

internal/quickfort/building.lua
internal/quickfort/dig.lua
internal/quickfort/place.lua
internal/quickfort/zone.lua

implement setting the priority for dig designations. syntax for dig blueprints is now [letter][number] where if the letter is not specified, 'd' is assumed, and if number is not specified, 4 is assumed.
also fix a bug in has_designation where the uint32 values were interpreted as booleans instead of numbers when they were unset. changed code to be unambiguous.
edit: also fix a bug in my new fancy __index methods where we could overflow the stack if we tried to find a key that doesn't exist.

Quickfort: implement dig priorities

---

internal/quickfort/list.lua
internal/quickfort/parse.lua

fixes DFHack/dfhack#1643
previously, all lines before the first modeline were ignored. now they will be interpreted as a #dig blueprint. this enables compatibility with Python quickfort. later modelines in the same file/sheet are interpreted normally (i.e. later blueprints must have modelines).

interpret modeless first sections as #dig

---

internal/quickfort/build.lua

and print a warning message once about the consequences of not having it
enabled. companion PR to DFHack/dfhack#1656

quickfort: only use buildingplan if it's enabled

---

internal/quickfort/list.lua

print a message about how many more blueprints are in the library at the end of `quickfort list`

quickfort: make the blueprint library discoverable

---

internal/quickfort/dig.lua

this prevents the case where a blueprint has some priorities specified
but not others, and the default priorities are scanned first. the event
block would not get created for the default priorities, then when the
ones with priority set are scanned, the event block would get created
and initialized to 0. the default priority tiles would then have a
priority of 0, which is invalid.

always create priority event block

---

changelog.txt
timestream.lua

Proof of concept for https://github.com/DFHack/dfhack/issues/1638.
This is an expansion of [timestream](https://gist.github.com/IndigoFenix/cf358b8c994caa0f93d5). I fixed the idling bug and made it so that all units on the map and the calendar progress at a constant rate **at any given FPS.** This means that no matter if you have 100 FPS or 20 FPS, your gameplay will remain _mostly_ the same.
What I did was speed up action timers and the calendar based on the ratio between the desired FPS and the current FPS. Unlike `fastdwarf` which sets all actions to be instantaneous, this only speeds them up evenly for everyone.
At first I tried a lazy solution by applying the `DEBUG_MEGAFAST` flag on and off during different frames, but that resulted in the dwarves taking short breaks between their …

timestream: The end of FPS death as we know it

---

changelog.txt
uniforce.lua
uniform-unstick.lua

One of the long-standing issues with military dwarves is that they can often get "stuck" when putting on their uniform, such that they never actually equip their uniform items. This script is an attempt to address that, in a minimally "cheaty" way.
One cause is of the issue is that dwarves are not smart enough to remove a non-uniform piece from a body part to put on their uniform piece. This script can cause dwarves to drop onto the floor all items on a body part which is missing a uniform piece. Another cause is when the assigned item is held by someone or something else, so the script can also force the assigned items to be removed from whatever inventory/container they're currently in and be placed on the floor. The script does not attempt to assign an item if one isn't already (i.e. …

Add script to help "unstick" military dwarves' uniform equiping.

---

changelog.txt
internal/quickfort/common.lua
internal/quickfort/query.lua
quickfort.lua

since I'm sure there are some out there that I didn't plan for
this is also useful for testing where I use query blueprints to mimic creating buildings from the UI
quickfort.txt config file modified in DFHack/dfhack#1670

add flag to allow arbitrary query blueprints

---

changelog.txt
internal/quickfort/build.lua

fix misconfiguration of nest boxes, hives, and slabs that were preventing them from being built from build blueprints. The "prefer blocks" setting was erroneously instructing these building types to look in the BLOCKS vector for their items, and of course nest boxes, slabs, and hives are never found there.

quickfort: fix configuration of nest boxes, slabs, and hives

---

changelog.txt
internal/quickfort/aliases.lua
internal/quickfort/parse.lua

Format is documented in DFHack/dfhack#1682 in aliases.txt, but the gist is that you can now specify name-value pairs when calling an alias, and temporary aliases with those names and values will be pushed on the alias stack for the duration of the call.
For example: in a blueprint, write:
{myalias somevar=somevalue}
and in aliases.txt, myalias can use the variable like it's expanding a subalias like:
myalias: keyskeyskeys{somevar}keyskeyskeys
The first usages of this functionality will be to simplify the quantum stockpile aliases and for test aliases for integration testing

[quickfort] parameterized aliases

---

changelog.txt
internal/quickfort/aliases.lua
internal/quickfort/parse.lua

This PR can be reviewed after #209 is merged.
On the first call to `quickfort list`, quickfort has to scan all the blueprints in the `blueprints/` directory tree to discover and cache the blueprint modelines. If the player's blueprint library is large, this can take a while.
This change significantly improves the performance of the first call to `quickfort list`. For the Starter Pack's blueprint corpus on my system (plus a few copies of dreamfort that I was testing), latency was reduced from 2.5 seconds to 0.5 seconds.

[quickfort] Speed up first call to quickfort list

---

changelog.txt
internal/quickfort/zone.lua

This PR requires parser functionality from #209 to have been merged .
Documentation in dfhack/DFHack#1682 in the quickfort user guide.
Supports zone configuration that is accessible from the submenus in the zone placement screen, e.g. pit/pond toggle, hospital supply counts, etc. We use the new parameterized alias syntax (#209) for the hospital config since there are no hotkeys defined in the UI.

[quickfort] detailed zone config

---

changelog.txt
internal/quickfort/build.lua
internal/quickfort/common.lua
internal/quickfort/orders.lua
quickfort.lua

Depends on changes in DFHack/dfhack#1684
This PR can be reviewed after #212 is merged.
migrate buildings_use_blocks to buildingplan; buildingplan can do it much better

[quickfort] deprecate buildings_use_blocks

---

changelog.txt
internal/quickfort/dialog.lua
internal/quickfort/list.lua
internal/quickfort/parse.lua

and only quote strings if they contain spaces. We only have 80 columns or so and we need to scrounge space.

[quickfort] display missing blueprint labels in dialog list output

---

changelog.txt
internal/quickfort/query.lua

fix query blueprint statistics being added to the wrong metric when both a query and a zone blueprint are run by the same meta blueprint

[quickfort] fix query blueprint statistics being added to the wrong metric

---

assign-preferences.lua

This small correction fixes a problem when adding flours as a food type preference to a unit.
Relevant forum post:
[http://www.bay12forums.com/smf/index.php?topic=110027.msg8205633#msg8205633](http://www.bay12forums.com/smf/index.php?topic=110027.msg8205633#msg8205633)

FIX: handle "flour" food type preference.

---

adaptation.rb

I don't know if modifying others' scripts is considered impolite, if so I apologize. Feel free to disregard this PR.
I added some code to handle the case where the trait "CaveAdapt" does not exist: before my addition the script would have simply ignored the case (I think), while now it can add a new cave adaptation trait to the unit.
Also, "print" statements were being ignored, so I changed those too.

Update script to handle a "fresh" unit with no adaptation suffered yet.

---

assign-profile.lua

There were some things I didn't like in the previous version of this script, and so I did a little bit of refactoring to update the code to what I think it's a more _dfhacky_ style and to improve (I hope) the documentation.

assign-profile: clean up code and clarify documentation

---

assign-attributes.lua
assign-beliefs.lua
assign-facets.lua
assign-goals.lua
assign-preferences.lua
assign-skills.lua

As the title says: given a "unit" passed as an argument to the `assign` function of each of these scripts, use `df.unit:is_instance(unit)` instead of `type(unit) == "userdata"` to assert its type.

Assert df.unit type using the specific is_instance check.

---

assign-preferences.lua

The console command example was setting `OBISIDIAN` (actually, "OBSIDAN", so two errors in one word) while the text result was showing `likes alabaster`. Now it's all set to `ALABASTER`.
Yep, that's all.

Fix typo in docs examples.

---

internal/quickfort/parse.lua
internal/quickfort/query.lua

and clarify the "alias not defined" error message

[quickfort] parse new alias characters in extended tokens

---

internal/quickfort/dialog.lua

- prevent two instances of the dialog from being opened at the same time
This can happen easily if you just run `quickfort gui` twice. One dialog will appear on top of the other and they must be dismissed separately. This is a particular problem when you try to run a query blueprint with a second dialog open, since that dialog will snarf all the keystrokes.
- prevent the details page from being opened or 'orders' from triggering if there is no list item selected
This can happen if the user puts in a search filter that doesn't match anything, then hits the right arrow key or alt-o

[quickfort] gui dialog fixes

---

changelog.txt
internal/quickfort/build.lua
internal/quickfort/building.lua
internal/quickfort/place.lua
internal/quickfort/zone.lua

now that Buildings::setSize doesn't unconditionally deallocate existing extents.
This fixes the issue where non-rectangular extent-based buildings had occupancy incorrectly set in non-extent tiles.
Builds on (and requires) DFHack/dfhack#1729

[quickfort] remove 'extents' hack

---

changelog.txt
gui/workorder-recheck.lua
workorder-recheck.lua

This mini-script allows deactivating a work order, f.e. to stop the job cancellation spam from an order whose conditions are no longer met.

workorder-recheck - set work order to Checking

---

changelog.txt
internal/quickfort/keycodes.lua
internal/quickfort/query.lua

Allows us to define true blank defaults for optional sub-aliases. Before, we needed to just use a key that didn't have any adverse effect.
Documentation in https://github.com/DFHack/dfhack/pull/1749

[quickfort] implement {Empty} keycode for use in aliases

---

changelog.txt
gui/quickfort.lua

For people who look for gui scripts in the `gui/` directory. Otherwise quickfort's gui mode might get missed.

[gui/quickfort] add script for fast access to the quickfort interactive dialog

---

changelog.txt
internal/quickfort/parse.lua

whitespace is now allowed between a marker name and the opening parenthesis in blueprint modelines. for example, `#dig start (5; 5)` is now valid (you used to be required to write `#dig start(5; 5)`)

[quickfort] allow more whitespace in blueprint modelines

---

changelog.txt
internal/quickfort/query.lua

Fixes DFHack/dfhack#1762
by manually changing df.global.ui.main.mode we skipped validity checking the ui normally does on state change. this sometimes resulted in bad data in world->selected_building, which caused buildingplan to crash. using the UI to switch modes avoids this problem.

[quickfort] fix rare crash in buildingplan when switching ui modes

---

quickfort.lua

document dependency on the search plugin as per PR DFHack/dfhack#1760
also update the text in general, including some formatting errors.

[quickfort] update command reference docs

---

changelog.txt
internal/quickfort/parse.lua

the xlsxio parser formats floats in .xlsx spreadsheet cells with a ".0" suffix. this breaks the quickfort dig parser, which expects just an integer. Floats are not used anywhere in quickfort, so we just floor the value and call it a day.

[quickfort] fix raw numeric dig priorities in .xlsx blueprints

---

changelog.txt
gui/quickfort.lua
internal/quickfort/dialog.lua
quickfort.lua

for example: `quickfort gui -l dreamfort notes` will start the dialog pre-filtered for the dreamfort walkthrough blueprints.

[quickfort] add flags for setting initial gui state

---

changelog.txt
internal/quickfort/command.lua
internal/quickfort/dialog.lua
internal/quickfort/list.lua

this removes a point of friction when viewing blueprint help text, like the dreamfort walkthrough. no map changes can be made, so no cursor should be required.

[quickfort] don't require a cursor for #notes blueprints

---

changelog.txt
internal/quickfort/dialog.lua
internal/quickfort/parse.lua

to indicate that the operation was successful and to report how many orders were added. Before, the operation was completely silent with no feedback to the user that something was done.

[quickfort] add feedback message for gui orders

---

changelog.txt
internal/quickfort/place.lua

in #place blueprints.
syntax documentation in DFHack/dfhack#1768

[quickfort] allow blueprints to specify bins/barrels/wheelbarrows for stockpiles

---

changelog.txt
internal/quickfort/build.lua
internal/quickfort/orders.lua
internal/quickfort/parse.lua
internal/quickfort/place.lua

a follow on to #254
this implements generating manager orders for containers specified in `#place` blueprints.
For example, in a place blueprint like this:
```
#place
s2(3x3)
```
two wheelbarrows would be enqueued. For this blueprint:
```
#place
f10(1x9)
```
10 rock pots would be enqueued, even though the stockpile only has 9 tiles.
A stockpile that does not specify a specific number is initialized with the default number of containers, but no manager orders are generated. This prevents huge numbers of containers being generated for regular blueprints that don't do anything special with their stockpile definitions.
This PR also fixes some in-code documentation that was just plain incorrect.
More docs in DFHack/dfhack#1768

[quickfort] enqueue manager orders for containers set in #place blueprints

---

changelog.txt
internal/quickfort/aliases.lua
internal/quickfort/command.lua
internal/quickfort/common.lua
internal/quickfort/dialog.lua
internal/quickfort/list.lua
internal/quickfort/parse.lua
internal/quickfort/query.lua

instead of requiring them to be added to a separate aliases.txt file. This reduces friction for sharing blueprints with custom aliases. It also makes testing much easier since you can define needed aliases along with the test blueprint. It makes alias development much easier for the same reason.
Syntax documentation in DFHack/dfhack#1779, but here's an example I've been using for testing. It scripts the setup of a new dreamfort map (meant to be run over the starting wagon):
- sets manager, bookkeeper, doctor, and broker nobles to the first dwarf
- names hotkeys and sets them to be zoomed to the correct z-level (x and y will need adjustment, and z may need adjustment too depending on number of soil layers, but the pre-naming is handy regardless)
- sets only farmers harvest, gather refuse …

[quickfort] allow aliases to be defined directly in blueprint files

---

changelog.txt
internal/quickfort/query.lua

Now any mode that has an active cursor is acceptable. Before, we required that players start in one of a short list of approved modes that we know how to get back to after the query blueprint is done, but that leads to a bad user experience when you happen to be in a mode that's not on the list. It's even worse when you run a meta blueprint that includes other non-#query blueprints and then runs the #query blueprint. The other blueprints will succeed, then the #query blueprint will fail, leaving a #meta sequence partially applied.
This new approach lets players start in any mode they want to, as long as it has a cursor. we send `ESC` repeatedly until we're back at the default screen, then we just send `q` once to get into query mode. easy peasy, and works everywhere. if we don't know how …

[quickfort] be flexible about start mode for #query blueprints

---

changelog.txt
internal/quickfort/query.lua

- check that the cursor is still on the tile at the end of configuration. this catches cases like configuring a stockpile to take from another, but the movement keys to get to that other stockpile are incorrect
- allow viewscreen focus string to change if the configuration causes the building to be destroyed (or cancels destruction of a building)

[quickfort] #query blueprint sanity check refinements

---

changelog.txt
devel/luacov.lua

DFHack/dfhack#1690
highly modified version of https://github.com/keplerproject/luacov/blob/master/src/bin/luacov that integrates with DFHack facilities and provides a better user interface for report generation.
depends on DFHack/dfhack#1787 for luacov and of course won't produce any actual reports until the DFHACK_ENABLE_LUACOV environment variable is handled in DFHack/dfhack#1789 (this PR needs to be merge before 1789, though, since that PR needs the `devel/luacov` doc header from this PR).
luacov produces text-based coverage reports by default. eventually I plan to investigate integrating with [luacov-reporter-lcov](https://github.com/daurnimator/luacov-reporter-lcov) for HTML report generation via [lcov](https://github.com/linux-test-project/lcov) (but this will require that …

[luacov] add coverage report generation script

---

CMakeLists.txt

this will prevent script tests from being installed. this will allow tests to be merged to master without letting them affect CI in DFHack/dfhack. once we get CI figured out for DFHack/scripts, then we can enable installation of the tests in #262 
DFHack/dfhack#1690

[test] don't install scripts/test files

---

gui/mass-remove.lua

I regularly make mistakes while planning buildings/constructions, and then have to remove them. While DF has a nice way of removing a lot of constructions at once, with the `d->n` menu, it does not have a similar menu for mass removal of buildings. And even if it did, it would probably be a different menu, meaning I'd have to navigate two different menus to remove pretty similar things.
This script allows the user to remove both buildings and constructions really fast. It can also 'unremove' things that are planned for removal, if the user accidentally marks the wrong thing for removal. On top of that, you can suspend/unsuspend jobs for
planned constructions. There are visual aids for what is and isn't marked for removal (since the game doesn't visually mark suspended constructions or …

Add mass-remove.lua, a gui script that helps with marking buildings/constructions for removal

---

changelog.txt
internal/quickfort/build.lua
internal/quickfort/building.lua
internal/quickfort/dig.lua
internal/quickfort/map.lua
internal/quickfort/place.lua
internal/quickfort/zone.lua
test/quickfort/building_unit.lua

- refactor the bounds checking functions in quickfort/map into a proper class
- fix a number of bugs related to processing non-solid extents and cropping extents that are partially out of bounds
- rename `ctx` to `digctx` in quickfort/dig so it isn't confused with the top-level `ctx` (which is also used in that file)

[quickfort] refactor quickfort/building and add unit tests

---

changelog.txt
internal/quickfort/aliases.lua
internal/quickfort/command.lua
internal/quickfort/dialog.lua
internal/quickfort/keycodes.lua
internal/quickfort/meta.lua
internal/quickfort/parse.lua
internal/quickfort/query.lua
internal/quickfort/reader.lua
test/quickfort/aliases_unit.lua
test/quickfort/keycodes_unit.lua
test/quickfort/parse_unit.lua
test/quickfort/reader_unit.lua

- fix handling of numeric keycodes
- don't recheck interface.txt for reloading on every keycode, just once per blueprint
- refactor reader classes and add a TextReader class for reading lines of text. CsvReader now inherits from TextReader
- other bits of random cleanup

[quickfort] refactor keycodes.lua and add unit tests

---

bodyswap.lua

Requires DFHack/df-structures#426.
Fix: 
- Prior party members no longer tag along after bodyswapping and reloading the map.
Improvement:
- Companions of bodyswapping targets are now added to the adventurer party (when swapping into a member of a previous party, for example) and can be swapped into using the in-game tactical party system.

bodyswap: handle companions

---

setfps.lua

Add usage to setfps when called without an argument (or with `-help`). 
Current script produces a traceback error:
```D:\Desktop\DF\df_47_05_win/hack/scripts/setfps.lua:19: attempt to concatenate a nil value (local 'cap')
stack traceback:
D:\Desktop\DF\df_47_05_win/hack/scripts/setfps.lua:19: in local 'script_code'
D:\Desktop\DF\df_47_05_win\hack\lua\dfhack.lua:680: in function 'dfhack.run_script_with_env'
(...tail calls...)```

Add usage to setfps.lua

---

changelog.txt
internal/quickfort/command.lua
internal/quickfort/common.lua
internal/quickfort/dig.lua
internal/quickfort/list.lua
internal/quickfort/parse.lua
internal/quickfort/place.lua
internal/quickfort/query.lua
internal/quickfort/set.lua
test/quickfort/common_unit.lua
test/quickfort/set_unit.lua

solves the following bugs:
- if the config file didn't mention a config var, it wouldn't get reset to defaults when `quickfort reset` was called
- instead of crashing, we now use built-in defaults when the `dfhack-config/quickfort/quickfort.txt` config file is not found
internal changes:
- move the `settings` table from common into set and wraps it in an API so calling code doesn't have to be aware of the internal structure of the table. default values are now stored along with the current value so we can reset to defaults reliably.
- use the new TextReader class to read the config file instead of using `io.open()` directly (enables unit testing)
- move the `valid_modes` table into quickfort/parse. common now only has logging functions.

[quickfort] refactor quickfort/set and add unit tests

---

internal/quickfort/list.lua
internal/quickfort/query.lua

minor fixes; nothing user visible
- clear file_scope_aliases table when rescanning files for listing (prevents table from getting cluttered with data in files that no longer exist)
- use library `same_xyz` instead of duplicate custom fn `same_pos`

[quickfort] internal cleanup

---

changelog.txt
internal/quickfort/dig.lua
internal/quickfort/map.lua
test/quickfort/map_unit.lua

but are out of bounds in the other edge axis (e.g. x=0, y=-1)
found while testing #284
as a byproduct of fixing this bug, this PR significantly simplifies the `map.lua` code.

[quickfort] fix cropping of tiles that lie on a map edge axis

---

changelog.txt
internal/quickfort/command.lua
quickfort.lua

suppresses all console output when running quickfort in functional tests

[quickfort] be more quiet when --quiet is passed

---

changelog.txt
set-timeskip-duration.lua
timeskip.lua

This script allows the player to modify the length of the ~2 week timeskip that precedes the start of a new fortress/adventure mode game. This allows players to do things like retiring a fortress and letting history (slowly) run its course for a century or so before the next fortress/adventure playthrough, or making a new adventurer appear nearly instantaneously after the death/retirement of the previous one.

Created set-timeskip-duration.lua

---

changelog.txt
internal/quickfort/command.lua
quickfort.lua

and alphabetize options in help text and in the code
inspired by the new `blueprint` `--cursor` option. it will also be useful for functional testing so we don't have to muck around with sidebar modes or the game cursor in the test code.
note that it's fine if the cursor is off the map. after cropping, there may still be in-bounds tiles

[quickfort] support --cursor option

---

internal/quickfort/orders.lua

essentially so the file itself can be loaded without automatically calling stockflow methods. This lets the file be included in tests where the test harness is parsing test files before a fortress is loaded.

[quickfort] convert reactions from a global to a singleton

---

gui/blueprint.lua
test/gui/blueprint.lua

depends on DFHack/dfhack#1884 and DFHack/dfhack#1887
and restore previous mode on dismiss
The mode switching logic is very similar to what is used in quickfort's `query.lua` and what was copied to the `mass-remove` script. Does it belong in the library? If so, where?

[gui/blueprint] get into an appropriate mode on display

---

internal/quickfort/dialog.lua

depends on DFHack/dfhack#1885
no behavior changes (other than now handling words that are longer than the maximum width)

[quickfort] use new library wrap function

---

gui/blueprint.lua
test/gui/blueprint.lua

resets and replaces the currently visible ui if the script is launched over an instance of itself.

[gui/blueprint] gracefully handle relaunches while the ui is still active

---

gui/blueprint.lua
test/gui/blueprint.lua

two small fixups:
- combine the two "if bad then Default" checks into one for screen mode management
- ensure we have a sidebar before we get sidebar dims in the tests. we were passing if there was one sidebar or two, but not zero.

[gui/blueprint] refactor and deflake

---

gui/blueprint.lua
test/gui/blueprint.lua

In addition to the dynamic status line that displays the selected area after the initial mark has been set, this commit introduces auto-resize functionality for the action panel. The ResizingPanel subclass will also be used for the upcoming Phases panel, which changes height based on whether phases should be autodetected or set manually.
The sequence I have to follow to get the layout set seems somewhat inefficient and I'm wondering if there is a better way to do it. I have to set the component widget positions after I know their heights, i.e. in `BlueprintUI:postUpdateLayout()`, but the widgets won't know their heights until `BlueprintUI:updateSubviewLayout()` is called, but the widgets *also* need to be re-laid out after their positions have been set so their subframes can be …

[gui/blueprint] show selected area dimensions when moving cursor

---

gui/load-screen.lua

Step 1 of DFHack/dfhack#1888
this is a noop for the current implementation, since the extra parameter will just get ignored, but this allows `gui/load-screen` to continue working when we add the library implementation of `string:split` and remove the override in `gui/load-screen`

[gui/load-screen] prepare to use library string split

---

gui/load-screen.lua

step 3 of DFHack/dfhack#1888
should not be checked in before DFHack/dfhack#1896

[gui/load-screen] remove rogue implementation of string:split()

---

gui/blueprint.lua
test/gui/blueprint.lua

Add an edit widget so generated blueprint names are customizable. A warning is displayed if the generated files might overwrite existing blueprints. Hitting ESC while editing (or hitting ENTER while the edit field is blank) aborts the edit and restores the previous name. The blueprint name can be initialized on the commandline.
I felt like I had to get slightly creative to manage the state of the edit widget. The edit widget is not self-contained in that it can't manage it's own "active" state (it doesn't get notified of the activation hotkey if it isn't already active). I'm not sure if anything needs to change here right now, but it seems like "self-activating" widgets could use some more thought and API design.
There is a soft dependency on DFHack/dfhack#1892. Everything will work fine …

[gui/blueprint] support editable names for blueprint files

---

assign-attributes.lua
assign-preferences.lua
gui/gm-editor.lua
gui/mod-manager.lua
gui/prerelease-warning.lua
gui/settings-manager.lua
gui/unit-info-viewer.lua
install-info.lua

First part of step 5 of DFHack/dfhack#1888
Note that there ended up being one more place (`settings-manager`) that needed the `plain` parameter set to `true` for non-pattern delimiters.
All changes were manually tested by running the scripts with appropriate parameters and confirming coverage with luacov:
```
[DFHack]# assign-attributes -attributes [ STRENGTH 2 ]
[DFHack]# assign-preferences -reset -likematerial [ INORGANIC:ALABASTER PLANT:WILLOW:WOOD ] -likecreature SPARROW -likeitem [ WOOD ITEM_WEAPON:ITEM_WEAPON_AXE_BATTLE ] -likeplant BERRIES_STRAW -liketree OAK -likecolor AQUA -likeshape STAR -hatecreature SPIDER_JUMPING
[DFHack]# gui/gm-editor, scan to something that's not an ID (I used birth_year of a unit) and hit shift-i
[DFHack]# gui/mod-manager (nothing to check since the code …
```

migrate scripts to use common string functions

---

gui/blueprint.lua
test/gui/blueprint.lua

add widgets that allow configuration of the blueprint phases
by default, phase labels are not shown (and their hotkeys are not active) and the 'phases' configuration is set to 'Autodetect'. Once the 'phases' hotkey is hit, 'Autodetect' toggles to 'Custom' and the individual phases are listed. Each can be toggled with their hotkey.
This is the last PR for `gui/blueprint` for milestone 1 of the blueprint overhaul plan (DFHack/dfhack#1842)

[gui/blueprint] allow blueprint phases to be configurable

---

changelog.txt
internal/quickfort/build.lua

most machines (like screw pumps, rollers, gears, etc.) can be built on ramps. teach this little nugget of information to `quickfort`.

[quickfort] fix valid tile detection for machines

---

CMakeLists.txt
changelog.txt

Fixes DFHack/dfhack#1690
Before we merge any scripts tests into the repo, there is one problem I think we need to solve.
Currently, automated CI tests are only run for DFHack/dfhack PRs. This means that a bad test can get checked into DFHack/scripts without blocking the PR that it's a part of, and once the scripts module gets updated in DFHack/dfhack, the bad test will block the next (likely unrelated) PR in DFHack/dfhack. This would be very frustrating for contributors to DFHack/dfhack since they would not be able to do anything about the failures blocking their PRs.
Can we implement test runs for the scripts repo? Or are there other ways to prevent bad tests from getting into the codebase?
Merging the scripts repo back into dfhack would solve the problem, of course, but then the current …

[test] install scripts/test into hack/scripts/test/scripts

---

changelog.txt
questport.lua
reveal-adv-map.lua
reveal-hidden-sites.lua

Whenever a new adventure mode game is started, world tiles in the player's vicinity are flagged as `discovered` and those that are not are hidden from view. This script either reveals or hides the entire adv mode world map by toggling this flag accordingly.

Added reveal-adv-map.lua

---

changelog.txt
internal/quickfort/parse.lua
test/quickfort/parse_unit.lua

undetected by the unit tests since I had just checked `expect.error` instead of `expect.error_match`. unit tests also fixed. New mantra: "`expect.error` considered harmful".

[quickfort] fix error in error message when label not found

---

devel/export-dt-ini.lua

missing rdelta was producing incorrect addresses on Windows

export-dt-ini: fix vtable address

---

internal/quickfort/command.lua
internal/quickfort/list.lua
quickfort.lua
test/quickfort/command_unit.lua

Uses the new `argparse` library functions to parse lists from the commandline. For example, what used to be written as:
```
quickfort run library/dreamfort.csv -n /suites2
quickfort orders library/dreamfort.csv -n /suites2
```
can now be written as:
```
quickfort run,orders library/dreamfort.csv -n /suites2
```
This cuts the dreamfort checklist size down by about 50%. [old](https://docs.google.com/spreadsheets/d/13PVZ2h3Mm3x_G1OXQvwKd7oIR2lK4A1Ahf6Om1kFigw/edit#gid=1459509569) [new](https://docs.google.com/spreadsheets/d/13PVZ2h3Mm3x_G1OXQvwKd7oIR2lK4A1Ahf6Om1kFigw/edit#gid=1637828091)
same enhancement for list_nums and labels. For example:
```
quickfort run 12,13,14
quickfort orders library/dreamfort.csv -n "/surface2, /farming2, /surface3, /farming3, /industry2, /surface4, /services2" …
```

[quickfort] Allow multiple commands, list_nums, and lables on commandline

---

changelog.txt
prioritize.lua
test/prioritize.lua

The prioritize script sets the `do_now` flag on all of the specified types of jobs that are currently ready to be picked up by a dwarf. This will force them to complete the jobs as soon as possible. This script can also continue to monitor creation of new jobs and automatically boost the priority of newly created jobs of specific types.
This is most useful for ensuring important (but low-priority -- according to DF) tasks don't get indefinitely ignored in busy forts. The list of monitored job types is cleared whenever you load a new map, so you can add a line like the one below to your `onMapLoad.init` file to ensure important job types are always completed promptly in your forts:
```
prioritize -a StoreItemInVehicle PullLever DestroyBuilding RemoveConstruction RecoverWounded FillPond …
```

New script: prioritize - monitors job creation and boosts priority for configurable job types

---

build-now.lua
changelog.txt
modtools/build-now.lua

Depends on DFHack/dfhack#1853
Fixes DFHack/dfhack#1857
`build-now` will instantly complete any non-suspended building construction job my mimicking standard game behavior and effects.
All buildings are processed by default, but the area of effect is configurable.
The following operations are handled:
- required building items are teleported to the target location and made part of the building
- partially constructed buildings where some items have already been brought manually are correctly handled
- items actively in transit are detached from the carrying unit and teleported the rest of the way
- items stored in other buildings as clutter are disassociated from the other building and teleported to the target building
- constructions make use of the `no_build_item` flag (a la the …

New script: build-now - instantly completes pending building construction jobs

---

changelog.txt
devel/query.lua
dwarf-op.lua

This switches these scripts over to use the new `safe_pairs()` library function from https://github.com/DFHack/dfhack/pull/1917, and also improves some other things I spotted while I was at it.
@cppcooper feel free to take a look

devel/query + dwarf-op cleanup

---

changelog.txt
prioritize.lua
test/prioritize.lua

Add the `--haul-labor` param to identify types of StoreItemInStockpile jobs and the `--reaction-name` param to identify types of CustomReaction jobs.
all dependencies of this script have been merged; this PR is ready for merge.

[prioritize] Differentiate StoreItemInStockpile jobs by hauler labor and CustomReaction jobs by reaction name

---

assign-preferences.lua

The plugin `stonesense` does not produce the `MatList.csv` file anymore, so I removed the suggestion about activating it in order to get the tokens.

[assign-preferences] Update  docs.

---

assign-beliefs.lua
assign-facets.lua

I noticed that when other scripts changed a trait (facet) or a belief, they then called the function `rebuildNeeds()` of `set-need` to recalculate the needs focus level. So, I added this call to my scripts as well.

[assign-*] Add recalculation of needs after a personality change.

---

changelog.txt
internal/quickfort/query.lua

Produce a useful error message instead of a code error when a bad query blueprint key sequence leaves the game in a mode that does not have an active cursor

[quickfort] gracefully handle error state for bad query blueprint key sequences that leave the game without a cursor

---

changelog.txt
internal/quickfort/api.lua
internal/quickfort/command.lua
internal/quickfort/dialog.lua
internal/quickfort/meta.lua
quickfort.lua
test/quickfort/api_unit.lua
test/quickfort/command_unit.lua
test/quickfort/quickfort_unit.lua

single API that exposes all of quickfort's blueprint actions ("run", "orders", "undo")
Question: should the API docs be just in the `quickfort.lua` file or should it be added to the online docs? Right now I just provide a link in the online docs to the source tree where the API is documented.
also fixes a bug that crept into the last release that broke the `--verbose` flag.

[quickfort] implement API for applying blueprint data passed in Lua tables

---

changelog.txt
gui/blueprint.lua

no unit tests for this since we can't control the display height from the test harness, but I did confirm that the existing tests now pass for both large and small screens.

[gui/blueprint] hide help text when the screen is too short to display it

---

changelog.txt
internal/quickfort/dig.lua

interpret `#build`-blueprint-style track alias names as single-tile carved track specifications in `#dig` blueprints.
and fix a few track-related bugs along the way:
- allow tracks to be built on hard, natural rock ramps
- allow dig priority to be properly set for track designations
- fix incorrect directions for tracks that extend south or east from a track segment pair specified with expansion syntax (e.g. T(4x4)). each of the tiles incorrectly had an additional direction enabled towards the center of the extent. that is, the track segments extending east from the origin tile also had south enabled, and the track segments extending south had east enabled.
+@drummeur

[quickfort] implement single-tile track aliases

---

changelog.txt
internal/quickfort/zone.lua

- fix parsing of multi-part extended zone configs (e.g. when you set custom supply limits for hospital zones AND set custom flags for a pond)
- fix incorrect field name for plaster powder in a hospital zone
will fix docs for the incorrect field name in an upcoming PR for the dfhack repo

[quickfort] zone parser fix

---

internal/quickfort/build.lua
internal/quickfort/dig.lua
internal/quickfort/zone.lua

There are no building jobs to check, so it's a noop in this situation. I originally added this call because I mistook "jobs belonging to buildings" for "jobs for building buildings"

[quickfort] remove useless calls to checkBuildingsNow()

---

changelog.txt
internal/quickfort/parse.lua
test/quickfort/parse_unit.lua

Implement feature discussed in passing in DFHack/dfhack#1998
This will allow `#>` and `#<` to take a number indicating how many levels to move up or down. This is especially useful in meta blueprints that work with multi-level sub-blueprints and the meta blueprint has to adjust its own z-level counter to compensate for what the sub-blueprints do.

[quickfort] extended syntax for z-level changes in quickfort blueprints

---

setfps.lua

I realized that this doesn't update on its own while looking at timing stuff in-game. No idea if it's used anywhere, but it seems prudent to keep it accurate.

Makes setfps also update fps_per_gfps

---

gui/advfort_items.lua

Fixes DFHack/dfhack#1618
This pull request adjusts `advfort_items.lua` to always append the available items for a job in their `job_item_idx` order. This fixes `Stud with <metal>` and `Encrust with Gems` jobs so that they won't delete both reagents.

Fix dfhack #1618 (advfort encrust/stud deletes items)

---

.github/workflows/build.yml

for build actions.  GitHub deprecated the git:// protocol, and our actions were failing with:
```
Run git clone git://github.com/dfhack/dfhack $HOME/dfhack --depth 1 --branch develop
Cloning into '/home/runner/dfhack'...
fatal: remote error: 
The unauthenticated git protocol on port [9](https://github.com/DFHack/scripts/runs/5667904791?check_suite_focus=true#step:6:9)418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Error: Process completed with exit code [12](https://github.com/DFHack/scripts/runs/5667904791?check_suite_focus=true#step:6:12)8.
```
e.g. https://github.com/DFHack/scripts/runs/5667904791?check_suite_focus=true

migrate to non-deprecated URL formats in git clone

---

changelog.txt
internal/quickfort/build.lua
internal/quickfort/building.lua
internal/quickfort/command.lua
test/quickfort/building_unit.lua

for example, bridges that open to the north now open to the south when rotated 180 degrees. before this change, the bridge position would be transformed, but the bridge would continue to open in the original, untransformed direction.
full coverage functional tests are coming in a dfhack repo PR.

[quickfort] adjust direction affinity when transforming buildings

---

autonick.lua
changelog.txt

three real changes, whoops.
- first, listens for -h and --help options. help is also displayed if commands are used, as autonick has none.
- second, ~~add a dialogue to confirm that the user actually wants to nickname, suppressable with -f / --force~~ require the use of the command `all` to proceed, eg `autonick all`. together with 1, this resolves https://github.com/DFHack/dfhack/issues/2050.
- third, report the number of dwarves given nicknames and if autonick.txt has ran out of names, suppressable with -q / --quiet.
something that might be nice (but that i haven't done yet) is to raise an error if the user is not in fort mode, since it doesn't really make sense to run it anywhere else. ~~another possible improvement would be to assume -f if no console exists, so existing configs don't …

add options to autonick

---

changelog.txt
internal/quickfort/build.lua
internal/quickfort/config.lua
internal/quickfort/parse.lua
internal/quickfort/transform.lua
quickfort.lua

automatically adjust cursor movements on the map screen in `#query` and `#config` modes when the blueprint is transformed. e.g.  `{Up}` will be played back as `{Right}` when the blueprint is rotated clockwise and the direction key would move the map cursor
refactors the transformation code so it can be reused by query and config modes.

[quickfort] adjust cursor movements when blueprint is rotated

---

changelog.txt
gui/blueprint.lua
test/gui/blueprint.lua

DFHack/dfhack#1842
GUI support for new features in DFHack/dfhack#2072 and UI unit tests.
We were also missing the toggle for the `zone` phase, which I had in an old branch but never committed. That is included here.
The list of phases is starting to get long, and it will get even longer soon, so the UI was reorganized so the phase toggles don't take up so much room.

Myk blueprint phases

---

changelog.txt
devel/eventful-client.lua

Usage:
devel/eventful-client help
devel/eventful-client add <event type> <frequency>
devel/eventful-client add all <frequency>
devel/eventful-client list
devel/eventful-client clear
:help:  shows this help text and a list of valid event types
:add:   add a handler for the named event type at the requested tick frequency
:list:  lists active handlers and their frequencies
:clear: unregisters all handlers
Note this script does not handle the eventful reaction or workshop events.

New script: devel/eventful-client

---

internal/quickfort/api.lua
internal/quickfort/command.lua
quickfort.lua
test/quickfort/command_unit.lua
test/quickfort/quickfort_unit.lua

the quickfort execution context is getting just too big and complicated. When I add blueprint shadows in the UI, it will gain more variables. Already I've run into maintenance issues when I add a new context element but forget to update all the calls to `init_ctx()`.
This change moves `init_ctx()` to take named params in a map instead of a long long parameter list.
No user-visible changes.

[quickfort] migrate command.init_ctx to take named params

---

internal/quickfort/aliases.lua
internal/quickfort/config.lua
test/quickfort/aliases_unit.lua

before, the aliases module kept state for which aliases were on the stack. This PR moves state into a context table that is owned by the calling code.
The global state became an issue when I started considering simultaneous blueprint calculations and early cancellation of blueprint processing for asynchronous UI preview refreshes. The alias stack changes dynamically during processing according to which parameters are defined for sub-aliases (see [docs](https://docs.dfhack.org/en/stable/docs/guides/quickfort-alias-guide.html#sub-aliases)).
Note there is no changelog entry for this since there is no user-visible change in behavior.

[quickfort] make aliases module reentrant

---

changelog.txt
internal/quickfort/api.lua
quickfort.lua
test/quickfort/api_unit.lua

before, the `data` param passed to the quickfort API had to contain a coordinate map. a common case for using the API, though, is to apply a one-cell blueprint. we can simplify the syntax for such usage by allowing data to be just a simple string, and interpreting it as `{[0]={[0]={[0]=string}}}`

[quickfort] accept string data params for one-cell blueprints

---

devel/block-borders.lua
devel/unit-path.lua
gui/blueprint.lua
gui/guide-path.lua
gui/liquids.lua
gui/mass-remove.lua
gui/mechanisms.lua
gui/pathable.lua
gui/power-meter.lua
gui/room-list.lua
gui/siege-engine.lua
gui/stamper.lua
gui/teleport.lua

Use new sidebar-setting code in `guidm.MenuOverlay`, use the new `guidm.MenuOverlay:renderMapOverlay()` function where convenient, and standardize error message phrasing when the user is on the wrong viewscreen (for those scripts that care).
Updates to:
- devel/block-borders.lua
- devel/unit-path.lua
- gui/blueprint.lua
- gui/guide-path.lua
- gui/liquids.lua
- gui/mass-remove.lua
- gui/mechanisms.lua
- gui/pathable.lua
- gui/power-meter.lua
- gui/room-list.lua
- gui/siege-engine.lua
- gui/stamper.lua
- gui/teleport.lua

Use new library code in gui scripts

---

devel/block-borders.lua

Fixes DFHack/dfhack#2123
now if a cursor is visible when starting `devel/block-borders`, it will start in cursor mode. Otherwise, it will start in cursor-less mode.
This reverts an accidental behavior change introduced in #377

respect current cursor mode in block-borders

---

modtools/fire-rate.lua

The modtool allows for a modder to alter the fire rate of ranged weapons based on different criteria.
I'm aware that several people have created similar tools, but nobody's submitted anything to be included in DFhack. Since I've just published a mod including one I made for it, I thought I might as well offer it as a contender.
Compared to some of the other modtools it does feel like a bit of a misfit (like for example, most don't replace the game mechanics with its own), but that down to what's required to make it work.
One thing the script is lacking is a mode that replicates vanilla-style fire rate rolls. I attempted to do some science to figure out how it works, but I couldn't figure out how to replicate the results with my limited maths abilities. If the lack of this style of rolls …

Add modtools/fire-rate

---

deteriorate.lua

although items aren't garbage collected for a few ticks, we can at least hide them from the player immediately so they can see that the script did something.

[deteriorate] hide items while waiting for garbage collection

---

gui/confirm-opts.lua

DFHack/dfhack#2164
DFHack/dfhack#2155
New hotkey on the settings menu that allows unpausing if the confirm plugin is currently paused.
text is disabled (grayed out) if confirm is already unpaused.
I also made the dialog a little taller to accommodate the extra line.
When not paused:
When paused:
No changelog entry since this is part of the confirm plugin change in the dfhack repo (where the changelog entry is)

[gui/confirm-opts] allow unpausing from the settings menu

---

changelog.txt
list-agreements.lua

+ handling of Deity names (as mentioned in DFHack/scripts#390)
+ age of petitions
+ added status 'expired' for outstanding petitions more than 1 year old
+ race specific guild professions
+ formatting characters to reduce mid-wo
rd wrapping
- consolidated functions for output and name lookup
- minimised repeated work within if...elseif... blocks

list-agreements overhaul

---

assign-minecarts.lua
changelog.txt
gui/quantum.lua
internal/quickfort/orders.lua
internal/quickfort/set.lua
test/assign-minecarts.lua
test/gui/quantum.lua

Fixes DFHack/dfhack#2156
Depends on DFHack/dfhack#2147
Easy creation tool for quantum stockpiles. I factored out minecart assignment into a separate tool so it can be used independently. I'm planning on referencing it from the dreamfort docs so players don't have to manually assign minecarts anymore.

New scripts: gui/quantum and assign-minecarts

---

build-now.lua
changelog.txt

Fixes DFHack/dfhack#2180
This allows `build-now` to complete buildings that were just designated with `buildingplan`

[build-now] cycle buildingplan before scanning buildings

---

changelog.txt
gui/quickfort.lua
internal/quickfort/command.lua
internal/quickfort/preview.lua
internal/quickfort/transform.lua
test/gui/quickfort.lua

Fixes DFHack/dfhack#2018
Depends on DFHack/dfhack#2147
UI for controlling repetitions and transformations in quickfort blueprints.
There is some UI behavior that is unique to this script that could use some feedback about whether it works. The repetitions counter can be modified by multiple hotkeys or edited directly. Is that obvious from the presentation?
Separate hotkey labels for each transformation type crowded the UI a little too much, so I collapsed them into just a generic "Ctrl+Arrow" label. Does that work?
The transformations get "auto-reduced" so the transformation list doesn't get too long. Longer transformation sequences will get automatically replaced with shorter equivalent sequences. Is that confusing?
Finally, the repetition and transformation settings get saved between …

[gui/quickfort] implement interactive controls for repetitions and transformations

---

gui/petitions.lua

Changes:
* determine names of historical figures in petitions
* hide petitions older than a year by default (AFAIK that's the only way to determine a petition expired)
* correctly build the date diff string for intervals greater than a year
* show type of Residency petition
* make the window bigger
(this addresses most of [#dfhack/2171](https://github.com/DFHack/dfhack/issues/2171) )

Various improvements in petitions.lua

---

changelog.txt
workorder.lua

The game actually allows creating work orders without a manager, the text "A manager is required to coordinate work orders" is meant as a warning. It only makes sense to allow it in this script too.

remove `has_manager` requirement from workorder.lua

---

internal/quickfort/dig.lua

Fixes DFHack/dfhack#2183
Don't display chopping designations as an error if there is nothing to chop. It's just a noop. Gathering too.

[gui/quickfort] Don't call chopping air an error

---

caravan.lua
changelog.txt

Helps in cases of endless unloading at the depot.

Implemented new 'unload' command in caravan script.

---

changelog.txt
gui/quickfort.lua
internal/quickfort/command.lua
internal/quickfort/orders.lua
internal/quickfort/parse.lua
test/quickfort/parse_unit.lua

- format text better in the gui/quickfort orders dialog so it's not so wide
- ensure built cage orders get combined with the rest of the wooden cages
- report that we're running quickfort in --dry-run mode when previewing orders

[quickfort, gui/quickfort] improve orders dialog presentation

---

changelog.txt
warn-stealers.lua

Requires the onUnitNewActive fix being worked on.
`warn-stealers start` in onMapLoad.init will warn when creatures that can steal food, drinks, or items become visible.

Add warn-stealers

---

changelog.txt
emigration.lua

The comparator in the master code is incorrect.
Dorf stress is negative for happy dorfs and positive for unhappy ones. Line 33 creates a threshold that is, therefore, above 100 for happy dorfs and below 100 for unhappy ones.
Line 90 in master asks for a 0-100 roll to be *below* this threshold for emigration to occur. This means that happy dorfs will *always* emigrate (contra line 14) and unhappy ones are increasingly unlikely to the unhappier they get.
You can observe this behaviour in a new fort: I saw six out of seven dorfs leave almost instantly.

Fix emigration logic

---

gui/blueprint.lua
gui/gm-editor.lua
gui/quickfort.lua
test/gui/workorder-details.lua

so they can work with both the docs and develop branches
also fix a bug in the workorder-details test where an extra order was being removed if you happened to run the tests with orders already in the queue.

migrate scripts to the new EditField:setText() api

---

docs/gui/launcher.rst
gui/launcher.lua

Fixes DFHack/dfhack#2224
Requires the [docs](https://github.com/DFHack/dfhack/tree/docs) branch of DFHack/dfhack.
Tab autocomplete is implemented, but the cross-indexing of commands via tags can't be (usefully) implemented until we go through and tag everything.
Enter to run the current command and show the output, shift-enter to run it and close the dialog. Dialog also auto-closes if the command brings up any screens of its own.
Screenshot:

[gui/launcher] first iteration of the in-game help browser and command launcher

---

docs/gui/launcher.rst
gui/launcher.lua

- unconditionally tee output to the terminal so the command output is recorded and is accessible for copy/paste
- simplify launcher command edit field by removing the edit stack (before, you could "un-autocomplete", but this behavior was confusing, complicated the code, and was difficult to explain. Moreover, it's just not very hard to retype/re-search-for what was there originally). (also the Alt-Left hotkey was appropriated by the EditField for "Home" functionality, so the launcher feature was inaccessible anyway, and it's just not worth it to find another hotkey for it.)
- let Ctrl-C clear the EditField that has focus. This lets the same hotkey clear the search text if that's where the focus is.
- if there is text already typed into the command EditField, use it as the initial search …

[gui/launcher] usability improvements

---

gui/launcher.lua

and dynamically rewrap if the window is resized with a help entry visible.
if the window is resized, scroll position is lost, but this matches current behavior for command output text anyway..
depends on DFHack/dfhack#2281

[gui/launcher] wrap text from helpdb for the current window size

---

docs/assign-attributes.rst
docs/assign-beliefs.rst
docs/assign-facets.rst
docs/assign-goals.rst
docs/assign-preferences.rst
docs/assign-skills.rst
docs/dwarf-op.rst
docs/extinguish.rst
docs/repeat.rst

to make them easier to read (they're already hard to understand with that syntax, but at least there are examples that show how they should look)

[docs] remove quotes around literal square brackets

---

gui/launcher.lua

- restore introductory help text when the command is cleared
- direct users to the `tags` command to browse tools in categories

[gui/launcher] implement feedback items

---

changelog.txt
internal/gm-unit/editor_skills.lua

Fixes https://github.com/DFHack/dfhack/issues/2308 
Fixes #424

Fix property name for ignored keys in skill editor

---

changelog.txt
docs/gui/create-item.rst
gui/create-item.lua

Don't lure casual players who just want to cheat in a few items into creating bars of vomit. Restrict materials to "normal" game items by default.

[gui/create-item] make --restricted default, add --unrestricted opt

---

changelog.txt
docs/modtools/create-unit.rst
modtools/create-unit.lua

Mostly, made naming more accurately reflect the game's behavior. Added option to generate "wild" name (i.e. civless name) by passing `-name` empty. Made nemesis records created without a civId have proper save data. Fixed some argument checks and added more so civ_id has to actually be for a civilization and group_id can't be a civilization (also implies they can't be the same). Made history event generation take current year into account, and add history event for histfig joining group as well, to better emulate game behavior (using void migrants as reference).

create-unit: rework naming; add nemesis civless save data; add arg checks

---

changelog.txt
gui/launcher.lua

update `get_first_word` routine to handle commands that start with a colon.

[gui/launcher] show help for :lua commands

---

changelog.txt
docs/unsuspend.rst
unsuspend.lua

DFHack/dfhack#2333
resume and unsuspend always had functionality overlap (with unsuspend's implementation being superior). now with the overlay framework, unsuspend take take on all of resume's functionality and we can turn down resume.

[unsuspend] port resume's suspended building overlay to the overlay framework

---

unsuspend.lua

so the unsuspend overlay doesn't get a useless draggable frame for repositioning its non-existent widget UI

use the overlay framework's new overlay_only attr

---

docs/modtools/extra-gamelog.rst

The link labelled as "Soundsense" is pointing to "Stonesense" forum thread.
Here directing it at the correct thread.

[extra-gamelog.rst] Soundsense link points to the wrong forum thread.

---

docs/gui/launcher.rst
gui/launcher.lua

Some keys were removed and causing errors in the full display (see also dfhack/dfhack@6a61c750e)

Update gui/launcher hotkeys for v50

---

docs/gui/pathable.rst
gui/pathable.lua

Depends on DFHack/dfhack#2539, DFHack/dfhack#2540, and DFHack/dfhack#2541
`gui/pathable` is now an `always_enabled` overlay widget so it can appear over the map but still allow the map to be interacted with normally (e.g. dragged around with the middle mouse button).
dialog elements now use library widgets instead of drawing directly to the screen so elements are mouse-interactive
The panel can be resized and dragged around the screen
hotkeys were changed to avoid conflicts with default keybindings, like `d` used to toggle drawing, but now that's a map scroll key. Moved all the hotkeys to Ctrl equivalents.

update gui/pathable to work with the new maps

---

devel/tile-browser.lua

- don't scan past the end of the textures array
- be more responsive to input by recalculating the displayed textures on render, not on feed

better tile browser

---

gui/launcher.lua

v50 moved the FPS counter to the bottom of the screen, so it no longer overlaps with the minimal launcher

gui/launcher: Stop hiding FPS counter in minimal mode

---

changelog.txt
devel/inspect-screen.lua
docs/gui/pathable.rst
gui/cp437-table.lua
gui/launcher.lua
gui/pathable.lua
gui/prerelease-warning.lua
gui/quickcmd.lua

let the game run uninterruped while DFHack tools are on the screen and allow DFHack tool windows to swap z-order. this allows, for example, map elements to be interacted with and the map itself to be dragged around while tool windows are up.
Depends on DFHack/dfhack#2556

Convert gui tools to ZScreens

---

unsuspend.lua

`bld` could be nil, but we were attempting to index it before checking. Filling in an empty table resolves this, and we check for a valid property where relevant.

Prevent indexing a nil table in unsuspend.lua

---

devel/tile-browser.lua
docs/devel/tile-browser.rst

Fixes DFHack/dfhack#2589
depends on DFHack/dfhack#2591 for the tile render width in Label

support larger textures in devel/tile-browser

---

changelog.txt
unsuspend.lua

We need to only show the overlay when paused in ascii mode since otherwise there's no way to see what's underneath.
in graphics mode, we can show the overlay all the time since it only takes up a small part of the tile and the majority of the building tile is still visible. it's also very useful to be able to see suspension state of buildings at all times.

make the unsuspend overlay always on in graphics mode

---

changelog.txt
gui/gm-editor.lua

[gui/gm-editor] fix use of invalid keybinding on help screen

---

exterminate.lua

Fixes two issues with exterminate.lua
`exterminate this` was killing the unit selected but returning a vague error to the user.
`exterminate DWARF --include-friendlies` and others were falsely claiming no units of the race were present on the map.

Fix issues with exterminate this and friendlies commands

---

stripcaged.lua

The type annotations give the following error when the dfhack tui window is loaded (not the one in the gui):
Parse error: param item any
Parse error: param opts table
Myk pointed out that this is due to the script parser looking for @module etc., so I've removed the type annotations for now.

Fix parser error by removing lsp type comments

---

changelog.txt
gui/quickfort.lua

so players can more easily lay them down multiple times right click or esc still exits as normal
Fixes DFHack/dfhack#2672

[gui/quickfort] don't close when applying a blueprint

---

gui/launcher.lua

Closes: https://github.com/DFHack/dfhack/issues/2503
Adds three label states to the launcher indicating the sidebar is showing either `All scripts`, `Suggestions`, or `Similar scripts`.

Add launcher autocomplete label

---

docs/locate-ore.rst
locate-ore.lua

Closes https://github.com/DFHack/dfhack/issues/2426
locate-ore now takes a `--all` option, which allows it to look at undiscovered veins/ores.

Make locate-ore work on discovered veins by default

---

.github/workflows/build.yml

This removes the Ruby steps from the CI.
Not sure if this should go in after all of them are migrated, but while it was on my mind I opened a PR.

No need to lint turned-down ruby

---

build-now.lua
changelog.txt

it doesn't handle clearing shrubs yet, though
depends on DFHack/dfhack#2734
related to DFHack/dfhack#2614

[build-now] use new tiletypes API to build dirt roads

---

changelog.txt
docs/prioritize.rst
prioritize.lua

so it's immediately effective when enabled

[prioritize] watch default job types when enabled

---

gui/launcher.lua

Fixes DFHack/dfhack#2772
when it's already open and gui/launcher is run with parameters
this allows gui/launcher to be used effectively from gui/control-panel when the user clicks on successive items to show their help

[gui/launcher] alter commandline in active window instead of closing

---

docs/gui/confirm.rst
gui/confirm.lua
gui/control-panel.lua

Sister PR to [#2721](https://github.com/DFHack/dfhack/pull/2721) to enable confirm
- Rename `gui/confirm-opts` to `gui/confirm`
- Use a Window/ZScreen in `gui/confirm`
- Add `confirm` to System Services in control-panep

Enable confirm

---

changelog.txt
docs/fix/protect-nicks.rst
fix/protect-nicks.lua

It turns out that the source issue of the nickname being erased is that DF no longer sets the historical figure name.
So simply looping on the active units and resetting the nickname with "dfhack.units.setNickname" fixes the same issue, alongside with other problems such as the nickname missing from many places, and being lost when retiring a fort.

Revamp protect-nicks to instead set the nickname to the historical figure

---

gui/liquids.lua

This fixes the pathing issues with gui/liquids. Specifically when spawning or removing magma.

Reindex pathfinding on liquids spawn

---

devel/visualize-structure.lua

For instance, passing `screen.parent` to this script is equivalent to `screen:_field('parent')`, which effectively yields a `viewscreen**`. This is represented in Lua as an object with a single `value` field containing the actual viewscreen pointer. However, there is no way to dereference this pointer via `utils.df_expr_to_ref()`. That behavior is fine for non-pointer primitives, since there is nothing to dereference, so this change introduces a special case for pointer primitives only.

devel/visualize-structure: dereference primitive double-pointers

---

deep-embark.lua

Change embark hotkey name, and update viewscreen checking code.
Tested and confirmed working when run from DFHack console and from `onLoad.init` - both on a fresh embark, and reclaiming an abandoned fort.

deep-embark: Update for v50

---

docs/gui/mass-remove.rst
gui/mass-remove.lua

Fixes DFHack/dfhack#2880
Fixes DFHack/dfhack#2742
significant overhaul of the code to solve a number of bugs and use standard library functionality.
note that `dfhack.job.removeJob` appears to cause crashes when used on DestroyBuilding jobs, so this version of `gui/mass-remove` does not offer "Unremove" functionality. It handles the primary use case of removing buildings, though.
Fixed case of unremoving destroy construction jobs (the previous code only handled the case where jobs were not yet assigned and it was still just a dig designation). unremoving constructions does actually work, but I commented it out in this PR for parity with unremove building.
When a building construction job is suspended, now the entire building is highlighted instead of just the center tile.

update gui/mass-remove for v50

---

changelog.txt
gui/dig.lua

Add check for `nil` `tile_type` to try to avoid whatever is happening in https://github.com/DFHack/dfhack/issues/2893
I still couldn't reproduce the original bug but this should avoid it.
Also updated the `getDesignation` code to auto matically convert downstair designations at the top of the stairs to updown.

Check for tile_type being nil to avoid out of bounds index error, and also respect stair designations

---

caravan.lua
changelog.txt
docs/caravan.rst

Adds an overlay to the caravan script that adds some functionality/info to the trade screen:
(Shift+Scroll is vanilla but a lot of people don't know about it. I see people get especially frustrated with the amount of scrolling on this page)
The ctrl+shift click actions seem to work super well!
Couple limitations/caveats with it as is right now:
- I can't find a way to calculate what the new height of the scrollbar should be after collapsing categories/bins programmatically. This means I have to manually calculate it. Based on the number of categories showing or the number of items contained in the collapsed items. I've tested it quite a bit and it seems to work pretty reliably but it would be nice to find a better solution.
- Because of some of the issues created by the preceding point, I …

Caravan overlay

---

gui/confirm.lua

Write confirm config to `dfhack-config/confirm.json` any time a confirm is enabled or disabled. Will be linked to a related dfhack/dfhack PR
Related to https://github.com/DFHack/dfhack/issues/2815

Persist confirm config

---

changelog.txt
devel/query.lua

Adds the ability to scan for jobs corresponding to the highlighted map coordinate, if there is no explicit job selected

Extends devel/query --job

---

changelog.txt
forbid.lua
unforbid.lua

`item::pos` is usually invalid for items in containers, which was causing `canWalkBetween()` to return false and items in reachable containers to get forbidden by `forbid`, or skipped by `unforbid`.

forbid/unforbid: calculate position for contained items correctly

---

changelog.txt
devel/query.lua

Table lookups now use `df_shortcut_env` instead of `df_expr_to_ref` This fixes a problem trying to index some vectors (probably all)

Revises query.lua to use df_shortcut_env

---

combine
combine.lua

Combine combines both combine-drinks and combine-plants and adds a lot of new features.
It can combine any food stuff in the selected stockpile or all stockpiles on the map.
I need to know who made the original combine-drinks and combine-plants scripts to know where credits is due.
Some parts of the scripts may be able to be merged, though I've already merged and shortened the script from 600 lines down to 300 by merging functions and using dynamic variables.
There may be requests to decouple eggs from fish or cheese from roasts as well as adding extracts/Liquid_misc as a valid itemType to be merged/combined. For now though, it seems that dwarves are very dilligent in combining milk buckets with barrels and alike, but milk/honey bought from merchants can be merged.
The script will not …

combine. The merged combine-drinks/plants with greater functionality

---

changelog.txt
gui/dig.lua
internal/dig/shapes.lua

[Demo.webm](https://user-images.githubusercontent.com/4482627/220819399-771243e2-503d-44fd-b7ef-e6a26b20bc10.webm)
**Points Driven**
Previously, shapes would be defined by the bounds of the 'view rectangle' marked by the user's mouse. Now, shapes are defined by points (currently just 2, although this paves the way for n-point shapes), and the view rectangle is defined by the bounds of the shape (and any extra points).
This allows for shapes 'bigger' than the rectangle defined by the initial points, which allows for thicc lines despite the user marking an e.g. 1x10 shape.
**Real Lines have Curves**
New shape type: Line Segment, also introduces the new concept for `gui/dig` "extra points", these points are for modifying the shape that's defined by the 'main' points. Currently this is used …

Refactor gui/dig a bit, support 'stamping' shapes and lines/curves

---

changelog.txt
gui/dig.lua

A reddit comment got me thinking and I realized a nice UX feature is being able to use the `v` shortcut to drop an extra point for a curve whil placing the second point of a line. 
It actually works really well and I think is really intuitive.

Update dig to allow dropping an extra point before placing second point.

---

changelog.txt
gui/dig.lua
internal/dig/shapes.lua

Allows setting a point and selecting mirror directions (vertical, horizontal, diagonal). Points will be mirrored across the planes defined by the point. The user can choose to 'save' the mirrored points which makes them into regular draggable points that can be transformed, moved, etc...
This works pretty well, but the interface is maybe a ltitle clunky. Should look in to UI improvements soon.
- `Line` shapes have been updated to draw the line both ways, this will guarantee creating symmetrical lines in cases where the Bresenham's algorithm has to 'choose' tiles arbitrarily when tie breaking.
- Updated bezier algorithm to fix rounding errors that created asymmetric curves
- Changed 'Transform' hotkey to `Y` (conflicted with thickness)
- Added optional guide line crosshair for mouse pos to …

Dig mirror mode, S-curves, various fixes

---

changelog.txt
suspendmanager.lua

When trying to determine if a job was suspended by `buildingplan`, suspendmanager was retrieving the job using `dfhack.buildings.findAtTile(job.pos)` instead `dfhack.job.getHolder(job)`. It's likely inefficient, but can also be wrong as `job.pos` is sometimes off by one.
This PR switches to `dfhack.job.getHolder` to fix this.

Fix suspendmanager building identification sometimes being wrong

---

changelog.txt
docs/exterminate.rst
exterminate.lua

Fixes DFHack/dfhack#3107
also update docs and respect kill method for `this` and `undead` targets. also print out how many units were killed for `undead`

[exterminate] add vaporize kill method

---

changelog.txt
docs/warn-starving.rst
warn-starving.lua

this also skips reports for residents, which is debatable. should we report on residents? Moreover, should isFortControlled be returning false for residents?
Fixes DFHack/dfhack#3117

[warn-starving] no reports for non-fort-controlled units

---

changelog.txt
gui/gm-editor.lua

Three small inprovements:
- Don't clobber previous window frame when opening a new one
- Enable jumping to matinfos
- Auto-fit the key column

gm-editor: Small usability tweaks

---

changelog.txt
gui/gm-editor.lua

When a fort is loaded jump to the first of:
- the coord if the current target or the selected value is a coord
- the `pos` of the current target
- the `centerx`, `centery`, `z` of the current target
- the `pos` of the selected value
- the `centerx`, `centery`, `z` of the selected value
The last two allow browsing lists like world.units.active or world.buildings.all and pressing g to jump to each item in the list without opening them.
Items in containers/being carried won't be located currently - I can add a (recursive) holder/container ref lookup if there is interest.

gm-editor: Add ``g`` shortcut to locate a target or selected value on the map

---

changelog.txt
gui/gm-editor.lua

Fixes DFHack/dfhack#3171
- new global `read_only` var
- read only state is saved in `config.data.read_only`
- frame position now saved in `config.data.frame`
- config saving moved to `save_config` fn
- keybinding `Ctrl-D` added to toggle `read_only`
- titles of all views updated on change
- added `dev`/`edit` and `safe`/`read` args to clear/set `read_only` on start
- insert/delete/set fns do nothing when `read_only` set
- `editSelected` allows only navigation when `read_only` set
One outstanding issue is that views opened using the `dialog` argument are not added to the `views` global array, so cannot have their `frame_title` updated by other views. I think to fix this I'd need to open the main view before showing the input dialog, which may mean moving the dialog code up into GmEditorUi …

gm-editor: add read-only mode with persistent state

---

gui/prerelease-warning.lua

so now we can name our builds like `r2rc1` and not scare the user with dire warnings about mislabeled releases

[prerelease-warning] parse our new interim release candidate naming scheme

---

changelog.txt
combine.lua
docs/combine.rst

PR for https://github.com/DFHack/dfhack/issues/3215.
Combine ammo, for bolts and arrows. categories: type + material + quality (+ created by). Created by is used for masterwork items.
Items which are marked for melting, is forbidden or hidden are excluded from being combined. This is in addition to the existing restrictions.
Edit: Added https://github.com/DFHack/dfhack/issues/3220.

Combine ammo and body parts

---

changelog.txt
suspendmanager.lua
unsuspend.lua

Previously, suspendmanager had a single function for all the suspension reasons (blocking, building plan, underwater). The first one is computed by suspendmanager, but the last two are external suspension factors. When suspending jobs, all three were taken in account, meaning that suspendmanager would actively suspend jobs that were about to be suspended by these external factors.
This was effectively getting in the way of completing jobs, like one that were half under water that would blink on and off, without dwarves even attempting the job.
This PR splits the check between the jobs that "should be suspended" (only internal factors), and the ones that "should stay suspended" (internal + external factors), and only take in account the first one when suspending jobs.
Fix …

Fix suspendmanager preentively suspending jobs

---

changelog.txt
gui/prerelease-warning.lua

before:
after:
but now the widgets are clickable, the window is resizable, etc. The extra bit of space on the right is for the scrollbar for longer text messages.
Fixes DFHack/dfhack#3281
Depends on DFHack/dfhack#3285 (or the PR that I'll eventually factor this bit of code out into) for `ZScreenModal`

modernize gui/prerelease-warning

---

changelog.txt
docs/exportlegends.rst
docs/open-legends.rst
exportlegends.lua
open-legends.lua

no visual progress bar yet, so this does not implement DFHack/dfhack#2292
however, it does produce a usable xml file, which might be useful now that vanilla has some export functionality.
the vanilla "Export XML" button does not appear to be triggerable via the usual means (setting mouse gps coordinates and simulating a button click), so all the logic that keeps everything in a single directory is now less useful than it was. eventually, the button may be triggerable via a keybinding again, and we can restore much of the code removed in this PR.
as it is, the exported XML file is now written to the top level DF game dir since that's where the vanilla file is.
A better solution might be to wrap all this in a GUI and control the process CWD dynamically as the script walks the player through …

get exportlegends basically working

---

changelog.txt
docs/gui/create-item.rst
docs/modtools/create-item.rst
gui/create-item.lua
modtools/create-item.lua

- changed argument parsing to use `processArgsGetopt` so all options now have short forms
- removed `--multi` option, replaced with `--count`; default is now to prompt for number, but if count is set, that will override (required to support legacy HACK_WISH functionality)
- fixed filters for water, lye, potash, pearlash, coal, and ash
- liquids now spawn in barrels/buckets as appropriate
- all item creation capabilities are now accessible in CLI form via `modtools/create-item`
- fixed some logic around corpse piece offsets
Fixes DFHack/dfhack#3243
Fixes DFHack/dfhack#3280
code was reformatted to use standard indents; diff best viewed while ignoring whitespace changes: https://github.com/DFHack/scripts/pull/687/files?diff=unified&w=1

[gui/create-item] refactor and fix up

---

changelog.txt
internal/quickfort/dig.lua

DFHack/dfhack#3352
in discussion whether this is enough to consider the issue fixed.

[quickfort] don't consider itemless tiles as errors for blueprints that affect items

---

changelog.txt
internal/quickfort/build.lua

Strictly, these buildings need a gear assembly nearby to support them, but I think quickfort can assume that you're doing it "right" (otherwise the machine will deconstruct after being built).
Fixes DFHack/dfhack#3350

[quickfort] accept more tile types for placing machines

---

changelog.txt
gui/create-item.lua

the restrictive filter was not allowing leather for armor items. it should be.

[gui/create-item] allow armor to be made out of leather

---

changelog.txt
docs/gui/sandbox.rst
docs/makeown.rst
gui/sandbox.lua
makeown.lua

Borne from my research for `modtools/create-unit`. This gives the player direct access to the arena creation interface while in fort mode. Game is force-paused while this interface is open (since otherwise your dwarves will immediately slaughter each other in "No Quarter" combat).
~~TODO:~~ I think this script is "good enough" for now, and there are other things I need to work on. I filed the last two items as issues.

new script: gui/sandbox

---

assign-minecarts.lua
changelog.txt
docs/assign-minecarts.rst

it just needed to get the vehicle list from its new location. also, we don't need to do any UI shenanigans anymore to refresh the vehicle list. it's always populated now.

[assign-minecarts] update to v50

---

changelog.txt
docs/gui/autodump.rst
gui/autodump.lua

so piles of discarded trader goods after a wagon scuttling are usable. This could also potentially be done as a "fix" script since piles of unusable items that you are being blamed for anyway seems like a bug.

[gui/autodump] add option to clear the trader flag upon teleport

---

changelog.txt
suspend.lua
suspendmanager.lua
unsuspend.lua

Rework the internals of suspendmanager to make it more flexible.
The current implementation of suspendmanager main methods is "shouldBeSuspended(job)"/"shouldStaySuspended(job)". However, in many cases it's by analysing another job that we can determine that a job should be suspended. For example, if a wall would close a dead-end, it's detectable when looking at the dead-end, not directly the job closing it. Similarly, when a multi-tile construction job would erase a designation work, it can be efficiently detected by looking at the designation work, not the construction job.
This PR reworks suspendmanager to be a class with a main instance kept between frames. The class keeps hold of a table<job_id,reason> maintaining the list of suspended jobs. The suspension is always in two …

[suspendmanager] Make it a class - track the job statuses

---

internal/quickfort/building.lua

fundamental layout logic shared by build, place, and zone modes. it turned out that we were never handling overlapping zones correctly. they were incorrectly occluding one another if they weren't all declared on the same tile (that is, a multi-type zone was ok, but independent zones that partially overlapped was not).
now, both overlapping and non-overlapping (buildings, stockpiles) use cases are handled properly

[quickfort] handle buildings that can overlap (i.e. zones)

---

internal/quickfort/command.lua
internal/quickfort/orders.lua

and order them by quantity
this makes the generated orders much easier to manage, especially when multiple blueprints-worth of orders is being added at the same time (e.g. the initial dreamfort step of `quickfort orders library/dreamfort.csv -n "/surface2, /farming2, /surface3, /industry2, /surface4"`)

[quickfort] coalesce orders from multiple blueprints

---

changelog.txt
docs/gui/quickfort.rst
docs/quickfort.rst
gui/quickfort.lua
quickfort.lua

Fixes DFHack/dfhack#2974
Fixes DFHack/dfhack#2647
Fixes DFHack/dfhack#2420

[quickfort] docs and misc updates

---

changelog.txt
docs/suspendmanager.rst
suspendmanager.lua

Fixes https://github.com/DFHack/dfhack/issues/3049
Fixes https://github.com/DFHack/dfhack/issues/3157
Add a new suspension reason for suspendmanager, focused on improving situations such as building a high wall or filling a corridor. The detection works by finding a "dead end" (tile with a single walkable neighbour), and suspending any job that would prevent its access by following the "corridor" leading to it.
Note: I'm pretty sure it's doable to refine this detection and make it replace the fuzzy "risk based" detection, but all my previous attempts where far too complicated and unreliable, so keeping both for now seems like a good choice.

[suspendmanager] Suspend blocking jobs when building high walls or filling corridors

---

internal/quickfort/build.lua
internal/quickfort/building.lua
internal/quickfort/notes.lua
internal/quickfort/place.lua
internal/quickfort/zone.lua

so dwarves actually use the locations for their intended purposes
also fixes a few bugs that came up in Dreamfort testing
- stop data from one blueprint entity from leaking into the parent database entry (e.g. a name assigned to one door could get assigned to *all* doors on the blueprint)
- remove unneeded occupation initialization. the game does this for us on first display
- bounds check the number of desired location items the same way the game does -- [0,999]
- initialize `assigned_unit_id` properly when no unit is assigned
- add missed reverse link for locations back to their component zones

[quickfort] fix location generation

---

changelog.txt
gui/quickfort.lua

I found this inconsistency when testing the walkthrough for the new pump_stack library blueprints.
The "cursor lock" assumed you were using a keyboard cursor, which is no longer true. it was using cursor setting logic to jump you back to the lock position instead of viewport moving logic.

[gui/quickfort] move "cursor lock" from keyboard semantics to mouse

---

changelog.txt
modtools/spawn-liquid.lua

The enum for water is interpreted as a boolean. can this be fixed in the structures? I vaguely remember that we tried that in the past and failed.

[modtools/spawn-liquid] account for wonky interpretation of liquid type

---

changelog.txt
docs/workorder.rst
workorder.lua

this solves the cancellation spam issue where autoMilk/autoShear jobs are queued, but then the animals are butchered.
It also keeps the manager orders cleaner by only having one job instead of many. Before, if you still had a milk order open, but a new animal became milkable, an additional milk job would be ordered in a new order. this could result in many 1/1 milk jobs appearing in the manager orders list.

[workorder] modify existing orders if __reduce_amount is true

---

internal/gm-unit/editor_skills.lua

where we really want static symbols
this allows keybindings to behave correctly in a SDL2 world

[gui/gm-unit] use string-based hotkeys instead of action keybindings

---

changelog.txt
gui/sandbox.lua

checking `graphics` is not a reliable metric. checking specific flags allows the following races to be spawned:
```
BIRD_OSTRICH
OSTRICH MAN
SHEEP
BIRD_CHICKEN
BIRD_DUCK
BIRD_PEAFOWL_BLUE
DEER
DEER_MAN
MOOSE
MOOSE MAN
LION
LION_MAN
GIANT_LION
ELK
ELK_MAN
```
Fixes DFHack/dfhack#3445

[gui/sandbox] check specific flags instead of the graphics field

---

changelog.txt
workorder.lua

reverse engineered by ab9rf
this also corrects overcounting in autoShearCreature, but to a much lesser extent (since pets are shearable and that was the main contributor to over-counting)

[workorder] align milkable check with DF logic

---

changelog.txt
combine.lua

this might be a fair compromise until we get better measurements of container capacities. It will still allow stacks to automatically "float" to the "natural" maximum

[combine] reduce max stack sizes in containers to 30

---

devel/export-dt-ini.lua

Changed in 50.08-r2
Codedependent on Discord reports that this is enough to make the script work. I haven't tested it myself.

devel/export-dt-ini: rename `game_extra` global back to `game`

---

suspendmanager.lua

When a construction is located on a non walkable tile (typically open air), it's never at risk of blocking other, as it can't get worst. Skip them in from the RISK_BLOCKING suspension reason.
Fixes [#3491](https://github.com/DFHack/dfhack/issues/3491)

[suspendmanager] Don't suspend construction on unwalkable tiles

---

changelog.txt
suspendmanager.lua

When a wall is built, the shape of the tile changes to one that is not walkable. However, when other unpassable buildings are created such as windows or statues, the shape of the tile does not change. In this case, `suspendmanager` then fails to recognize risky tiles and does not behave correctly. This PR fixes this by also reading the building on the tile.
Before:
After:

[suspendmanager] Take in account already built buildings

---

changelog.txt
gui/autodump.lua

we need to cancel the job before moveToGround will teleport it.

[gui/autodump] properly teleport items in jobs

---

build-now.lua
deep-embark.lua
modtools/create-unit.lua

Follow-up to https://github.com/DFHack/df-structures/pull/612
First half for fixing https://github.com/DFHack/dfhack/issues/3526
Since the semantic change in the structure PR, "walkable" is equivalent to "able to stand on". Many tools had this check written as "not an open tile", which is now redundant with the "walkable" attribute. Remove the redundant checks.
Note: I've only tested deep-embark with these changes, but I think it's quite safe

[cleanup] Remove redundant checks for opentiles

---

gui/control-panel.lua

DFHack/dfhack#3559
DFHack/dfhack#3584

[gui/control-panel] convert keystroke pref to a cpp pref

---

changelog.txt
suspendmanager.lua

Add a job overlay to `suspendmanager`. When suspendmanager is enabled, it hides the "Suspend/Resume construction" button with a text overlay and include the toggle for enabling and disabling `suspendmanager`. This overlay either explains why the job is suspended or simply indicate that it is not suspended.
The reason for overlaying the button is that once enabled, suspendmanager will not take in account anymore any choice that the player makes here. This overlay makes this explicit, while providing feedback on its choice and a way to act on it.
No overlay at all for buildingplan jobs in the waiting list.
Fixes https://github.com/DFHack/dfhack/issues/3413

suspendmanager job overlay

---

changelog.txt
suspendmanager.lua

The suspendmanager overlay rendering was skipped when irrelevant, but the inputs were still taken in account, so when a construction without the suspendmanager overlay was selected, pressing ctrl-m or clicking the label area would still toggle suspendmanager.

Fix suspendmanager enabling/disabling itself unexpectedly

---

changelog.txt
docs/unsuspend.rst
suspendmanager.lua
unsuspend.lua

Use the new icon for jobs suspended by suspendmanager, to make them less attention grabbing and create an easier to read global situation when there are jobs that are actually in need of attention (transient or repetitive issues).
Needs [#3602](https://github.com/DFHack/dfhack/pull/3602)
Fixes [#3554](https://github.com/DFHack/dfhack/issues/3554)

Use a separate icon for jobs suspended by suspendmanager

---

internal/quickfort/dig.lua

no changelog since this is essentially only a cosmetic fix and the issue can only be triggered in very special circumstances (map block completely unallocated)

[quickfort] don't error if the map block is unallocated

---

changelog.txt
devel/lsmem.lua
docs/devel/lsmem.rst

It's now possible to list ranges containing a given address, or ranges matching a given filename.
Also mark the script as available.

devel/lsmem: add filtering capabilities

---

changelog.txt
docs/exportlegends.rst
exportlegends.lua

- now exportlegends can automatically run when you click on the vanilla "Export XML" button
- controllable via a toggle in case you just want vanilla
- you can still run `exportlegends` manually from the commandline if you just want the extended data file
- live status readout showing current export target and overall percent complete
- player prevented from leaving legends mode while export is running
- legends mode UI is still usable while data is being exported
Depends on DFHack/dfhack#3647
Fixes DFHack/dfhack#2292
Fixes DFHack/dfhack#2936

[exportlegends] add overlays to integrate into legends UI

---

exportlegends.lua

make exportlegends widget more distictively dfhack

---

changelog.txt
suspendmanager.lua

On any "corridor" shape with a branching, suspendmanager currently fails to detect that it was about to be enclosed. This was pleasantly fixable by storing the building leading to a dead-end, and keeping this list across the various dead-end detections. This way, on a T shape, the first pass of either of the two extremities will suspend the extremity branch as before, but the second pass now suspends the remainder of the shape since it does not any more consider the first dead-end as an exit candidate.
Before:
The corridor leading to the shape is not suspended, and the shape will not be properly finished
After:
Only the actual extremities of the shape are allowed to be built.
Fixes [#3548](https://github.com/DFHack/dfhack/issues/3548)

suspendmanager: improve detection on "T" and "+" shapes

---

suspendmanager.lua

Minor internal cleanup:
- Consistently use `utils.invert`
- In the dead-end detection, don't retrieve the current build by its position, but by the explored building in the current iteration, and do the exploration by updating both the exit position and corresponding building

suspendmanager: internal cleanup

---

changelog.txt
starvingdead.lua

so undead sieges can end
also clean up some unused variables

[starvingdead] vanish the undead instead of marking them inactive

---

docs/workorder-recheck.rst
workorder-recheck.lua

This repairs the `workorder-recheck.lua` script and adds an overlay to the work order conditions screen.

Make `workorder-recheck` work again

---

changelog.txt
gui/gm-editor.lua
gui/launcher.lua

this comes up when you set a frame position, resize the DF window by a lot, then bring up the tool again.

[gui/launcher, gui/gm-editor] recover gracefully when saved frame positions are offscreen

---

gui/civ-alert.lua
gui/control-panel.lua
gui/cp437-table.lua
gui/design.lua
gui/launcher.lua
unsuspend.lua

Will work with https://github.com/DFHack/dfhack/pull/3663 only.

use dynamic texture mechanism

---

changelog.txt
docs/fix/retrieve-units.rst
fix/retrieve-units.lua

[fix/retrieve-units] prevent unit from being added to active vector twice

---

changelog.txt
internal/quickfort/build.lua
internal/quickfort/place.lua

to support work on `gui/quantum`

[quickfort] allow stockpiles/workshops to be linked by id

---

changelog.txt
emigration.lua

remove emigrating citizens from work details and assigned workshops
also fix an uninitialized variable in the test for whether the emigration target is the current fort. this prevents dwarves from "emigrating" to the fort site.
Fixes DFHack/dfhack#3569

[emigration] clean up after emigrating citizens

---

internal/caravan/common.lua
internal/caravan/movegoods.lua
internal/caravan/predicates.lua
internal/caravan/trade.lua

Also includes prep work for predicate filters, but the widgets are hidden for now.
Fixes DFHack/dfhack#3656

[caravan] make search field per-goods list

---

changelog.txt
internal/quickfort/dig.lua

When applying a blueprint over existing designations, or when undoing a blueprint, any designations that have been converted into jobs will still be "alive". so if you used to have a channel designation and you convert it to a stairs designation with a blueprint, a dwarf could come by and dig a channel anyway. This PR clears out designation-related jobs associated with the tiles that are being modified.
Depends on DFHack/dfhack/#3713

[quickfort] cancel old dig jobs when tile designation is changed

---

changelog.txt
docs/set-orientation.rst
set-orientation.lua

mark set-orientation as available

---

changelog.txt
gui/quickfort.lua

since the details are no longer opened with the right arrow like they used to be
also remove reference to old config modes

[gui/quickfort] close dialog with ctrl-D instead of left arrow

---

gui/mod-manager.lua

[gui/mod-manager] clarify error message when a mod cannot be found

---

changelog.txt
gui/sandbox.lua

where there are invalid plant indices in the Wood vector
Fixes DFHack/dfhack#3556

[gui/sandbox] protect against out of range vector access in modded games

---

gui/control-panel.lua

- make it clear that hiding the console only applies to windows
- add the string "mortal mode" to the mortal mode preference
- clarify key event suppression

[gui/control-panel] reword preferences label and help text

---

docs/autofish.rst

Fixed autofish docs showing the incorrect minimum fish default value. (the default is 75, not 50)

Autofish: Docs update, incorrect values

---

autofish.lua
docs/autofish.rst

Makes changes necessary to replace the "count raw fish" switch on the command line into a settable option, instead of a toggle.
Other minor changes to output as well.

Allow raw fish option to be set from command line

---

changelog.txt
internal/caravan/movegoods.lua

extend code that sees inside of bins to also cover barrels and pots. liquid and powders are not individually tradeable and are considered part of the barrel/pot.

[caravan] trade non-liquid/powder goods inside of barrels and pots

---

changelog.txt
devel/inspect-screen.lua

so it's easier to determine what screen percentage vanilla UI widgets are bound to

[devel/inspect-screen] show total grid sizes

---

unsuspend.lua

In the switch to dynamic textures, the "kept suspended" white cross texture position was changed from 3 to 1, making the cross red instead of white (https://github.com/DFHack/scripts/pull/798/files#diff-d5774fd6bdc7eb51dd274343c52ae384d20ad8ec2ff8ad0e9f7adb8253989a56R157)
It looks like an unintentional change in the refactor, restore the texture position to the white cross.

Quickfix: Restore the "kept suspended" color

---

changelog.txt
docs/suspendmanager.rst
suspendmanager.lua

This change to suspendmanager deals with https://github.com/DFHack/dfhack/issues/3601. I've added a new suspension reason `UNSUPPORTED` and added some checks relating to it. The way it works is based on an observation: each tiletype shape that can provide support provides it in one of two ways - either it supports like a wall (all 6 ortho axes as well as orthogonally on the layer above, with an invisible floor), or it supports like a floor (orthogonally on the same level). The only other thing that can provide support is a support building (pillar), which provides support to floors above it or walls both above and below.
I have tested this to a standard that I hope is rigorous enough although @plule says he's willing to take a shot at testing some other cases I may have missed.

Misc improvement: `suspendmanager.lua` has new suspension reason for unsupported constructions.

---

changelog.txt
docs/startdwarf.rst
startdwarf.lua
test/startdwarf.lua

Fixes https://github.com/DFHack/dfhack/issues/3789
depends on https://github.com/DFHack/dfhack/pull/3816 and https://github.com/DFHack/df-structures/pull/664 (on linux, at least)

reinstate startdwarf and add scrollbar overlay

---

changelog.txt
suspendmanager.lua

When looking at neighbours with getTileType and getMapBlock, we may be looking out of bound.
Check for nil before using the return value

suspendmanager: Fix nil access of tile type and map block

---

changelog.txt
docs/drain-aquifer.rst
drain-aquifer.lua
gui/control-panel.lua

satisfies feature request from Reddit

[drain-aquifer] more control over which levels get drained

---

add-recipe.lua
changelog.txt
docs/add-recipe.rst

[add-recipe] reinstate

---

gui/control-panel.lua

ref: https://github.com/DFHack/dfhack/pull/3851

[gui/control-panel] adjust to new location of full text search var

---

burial.lua
changelog.txt
docs/burial.rst

Reworked the burial script to create minimal tombs for each coffin building, allowing things to be buried in them.
Also modified the options to allow for designating dwarf-only, pet-only, or general purpose tombs.

Burial update

---

changelog.txt
prioritize.lua

since so many jobs can bork the DF job scheduler. print a warning instead.

[prioritize] refuse to automatically prioritize dig jobs

---

changelog.txt
docs/gui/quickfort.rst
internal/quickfort/build.lua

but skip floors being built on top of floors and ramps on top of ramps. this allows blueprints to continue to be idempotent
Fixes https://github.com/DFHack/dfhack/issues/3792

[quickfort] allow constructions to be built on top of constructions

---

changelog.txt
full-heal.lua

Items::remove may not work properly
Fixes https://github.com/DFHack/dfhack/issues/3846

[full-heal] destroy the corpse like autodump-destroy

---

changelog.txt
gui/overlay.lua

there are so many overlays now so we need to be more selective
also fix the problem where if there was an overlay behind the gui/overlay window, it would get mouse clicks before the tool window itself.

[gui/overlay] filter overlays by context, not just by screen

---

changelog.txt
docs/gui/gm-editor.rst
gui/gm-editor.lua

change from click to edit to click to select, double-click to edit. this should help prevent accidental modifications to the data and make zooming to location and selecting ids for dereferencing easier

[gui/gm-editor] move from click to edit to double click to edit

---

changelog.txt
warn-stranded.lua

if an adjacent tile is walkable. this avoids warning for, for example, units walking under waterfalls or through variable depth water

[warn-stranded] don't warn for units on unwalkable tiles

---

gui/design.lua

depends on https://github.com/DFHack/dfhack/pull/3970

[gui/design] show tooltip even when mouse is outside of map

---

changelog.txt
docs/trackstop.rst
trackstop.lua

Add overlay for changing dump direction and friction of track stops after construction. If this is accepted, I can do a follow-up to remove the old trackstop.cpp stuff.
https://github.com/DFHack/scripts/assets/2104555/8390e43f-b9cf-472f-8529-fcc43422137e
Some screenshots showing how it looks with various suspend manager/building plan states:
Also adds rollers overlay (same position, size, most of the same options):
https://github.com/DFHack/scripts/assets/2104555/7778ef61-b9b3-443f-ba91-6102ab34d81a
The directions _appear_ to be flipped here but I double checked them against freshly built ones. When you press the arrow up and build the result is "FromSouth" and so on.

Add trackstop and rollers overlays

---

changelog.txt
docs/unforbid.rst
unforbid.lua

also adds option to disable ignoring tattered items.
this is very much a first pass with minimal testing :)
Fixes https://github.com/DFHack/dfhack/issues/3967

unforbid: ignore tattered items by default

---

changelog.txt
gui/control-panel.lua

remove always-on system tools and `autolabor`
as discussed here: https://discord.com/channels/793331351645323264/807444515194798090/1169034531999862897

[gui/control-panel] remove some tools from the lists

---

forbid.lua
unforbid.lua

As discussed on Discord there is very little reason for scripts not to use IN_PLAY instead of items.all.
Related:
https://github.com/DFHack/dfhack/issues/4025
https://github.com/DFHack/dfhack/issues/4027

Change items.all to items.other.IN_PLAY for forbid scripts

---

changelog.txt
internal/caravan/common.lua
internal/caravan/trade.lua

just like you already can on the bring goods to depot screen
Fixes https://github.com/DFHack/dfhack/issues/4022

[caravan] search within containers on trade screen

---

changelog.txt
gui/control-panel.lua

since when you *know* they're stranded and you're remedying the situation, but you don't want to permanently ignore them, then 4x a day is too often to dismiss the popup.

[gui/control-panel] reduce frequency of warn-stranded check

---

ban-cooking.lua
changelog.txt

The creature ID is currently nil due to being an uninitialized variable, causing ban-cooking to error if a creature alcohol has the [EDIBLE_COOKED] token. This replaces the uninitialized variable with the one containing the creature ID.

Fix creature alcohol in ban-cooking.lua

---

changelog.txt
warn-stranded.lua

Did some testing on this. It definitely works to ignore citizens gathering fruit. I haven't ran into any issues of false positives so far, but we should still keep an eye on it

Ignore all fruit gatherers when checking stranded

---

changelog.txt
docs/uniform-unstick.rst
uniform-unstick.lua

- reformat and clean up code
- fix handling of --multi option and add docs for it
- remove interaction with pre-v50 sidebar that no longer exists
- remove old in-script docstring
- add check for conflicting enabled labors (mining, woodcutting, hunting)
- add overlay for accessing functionality from the squad equipment screen
Fixes https://github.com/DFHack/dfhack/issues/4105

reinstate uniform-unstick

---

changelog.txt
confirm.lua
docs/confirm.rst
docs/gui/confirm.rst
gui/confirm.lua

Fixes https://github.com/DFHack/dfhack/issues/4107
Fixes https://github.com/DFHack/dfhack/issues/3282
Fixes https://github.com/DFHack/dfhack/issues/3106
Fixes https://github.com/DFHack/dfhack/issues/2814

update confirm to use overlays and Lua-based confirmation prompts

---

changelog.txt
confirm.lua
docs/confirm.rst

Fixes https://github.com/DFHack/dfhack/issues/3912

[confirm] implement prompt for trade agreement screen

---

changelog.txt
docs/gui/launcher.rst
gui/launcher.lua

but not too large so it doesn't bog down. only most recent 32k
if we kept the full scrollback buffer of 256k, then every command would take a second longer to run because of text processing and buffer copying. 32k seems like a good compromise.
From suggestion on reddit: https://www.reddit.com/r/dwarffortress/comments/18x651d/comment/kg3q55n/?utm_source=share&utm_medium=web2x&context=3

[gui/launcher] keep persistent scrollback buffer

---

docs/reveal-hidden-sites.rst
reveal-hidden-sites.lua

no changelog entry since the structures were just changed in this release

[reveal-hidden-sites] adjust code to use new field names

---

changelog.txt
confirm.lua
gui/confirm.lua
internal/confirm/specs.lua

- reinstate trade screen prompts (I simplified the "confirm trade" logic since the things it previously warned against weren't actually dangerous)
- reinstate prompt for delete uniform
- reinstate prompt for convict criminal
- add frame debugging features when placing detection frames
- recover from screen resizes that push detection frames out of skew

[confirm] refactor registry and reinstate remaining confirmation prompts

---

changelog.txt
internal/confirm/specs.lua

as requested on Reddit: https://www.reddit.com/r/dwarffortress/comments/18x651d/comment/kg4omsa/?utm_source=share&utm_medium=web2x&context=3
the confirmation prompt will only come up if there are already results on the map.

[confirm] add prompt for re-running embark site finder

---

confirm.lua

for greater visibility, and so you can see exactly what's behind it

[confirm] make intercept frames blink while debugging

---

changelog.txt
confirm.lua
internal/confirm/specs.lua

as requested (several times) in the reddit thread: https://www.reddit.com/r/dwarffortress/comments/18x651d/what_buttons_do_you_wish_had_an_are_you_really/
this required a few extensions to the confirm architecture. nothing terrible, but indicative that this is a particularly hard case to handle.

[confirm] add prompt for exiting the uniform customization page without saving

---

changelog.txt
docs/gui/mass-remove.rst
gui/mass-remove.lua

differentiate types of buildings (stockpiles vs. planned constructions vs. regular buildings) and make removal independently configurable for each type
also ensure that nothing is selected before we start removing things -- removing the selected building/zone causes a crash
suspend functionality removed since it didn't seem to fit in with the other options. Also, `suspendmanager` would just immediately undo what was suspended. We might need a better answer to this in the future.
as prompted by the Reddit thread: https://www.reddit.com/r/dwarffortress/comments/18x651d/what_buttons_do_you_wish_had_an_are_you_really/
Fixes: https://github.com/DFHack/dfhack/issues/4084
Fixes: https://github.com/DFHack/dfhack/issues/3369

rewrite gui/mass-remove to be more user friendly

---

changelog.txt
docs/gui/teleport.rst
gui/teleport.lua

mouse driven box selection
if a unit is already selected in the UI, will act on that unit by default
visual marker of selected units (same approach as `gui/autodump`)
can remove units from the selected list
filterable by citizens, hostiles, and non-citizen friendlies
double click to teleport to tile
filter settings are saved across invocations

reinstate (read: rewrite) gui/teleport

---

autofish.lua
control-panel.lua
devel/prepare-save.lua
emigration.lua
fix/protect-nicks.lua
hermit.lua
internal/control-panel/common.lua
once-per-save.lua
prioritize.lua
source.lua
starvingdead.lua
suspendmanager.lua
test/prioritize.lua
warn-stranded.lua

Depends on https://github.com/DFHack/dfhack/pull/4153
most scripts had a straightforward conversion
once-per-save was doing a lot of undocumented stuff that is no longer necessary, so it got largely rewritten
made persistence in `prioritize` more efficient by not confusing the json serializer with a map that looks like a sparse list
changed persistence format of `devel/prepare-save`, but the persistence appears to be for human readability and is not read by the script
warn-stranded had a format change and will lose history. the persistence key name was changed so that old data won't mess up the new formats. this is only the list of stranded units that you are ignoring, though, so the impact to players is low. I wish I had caught the non-standard persistence format in code review : /

migrate scripts to new persistence API

---

docs/gui/control-panel.rst
gui/control-panel.lua

and more explanatory text for why the list is empty when trying to enable tools outside of fort mode

[gui/control-panel] confirmation prompts for reset to defaults

---

changelog.txt
fix/stuck-instruments.lua

even when there are no dangling general refs
also clean up encoding for console output

[fix/stuck-instruments] handle incorrectly set in_job flag

---

changelog.txt
gui/launcher.lua

Fixes: https://github.com/DFHack/dfhack/issues/4174

[gui/launcher] make launcher autocomplete case insensitive

---

EmbarkAnywhere_v50.lua
LiquidEmbarkAnywhere_v50.lua

here's an embark anywhere attempt script this should let one embark anywhere... still need gui widget support to handle the new mouse only cursor controls

script concept for embark anywhere on DF50

---

changelog.txt
suspendmanager.lua

fixes report on Discord: https://discord.com/channels/793331351645323264/807444467140788254/1196241682933485578

[suspendmanager] handle case where building footprint is invalid

---

changelog.txt
docs/gui/settings-manager.rst
gui/settings-manager.lua

option to auto-apply saved settings for new embarks
widget in both embark difficulty screen and fort settings
Fixes: https://github.com/DFHack/dfhack/issues/4064

[settings-manager] save and load difficulty settings

---

changelog.txt
empty-bin.lua

it was using the container position directly instead of calling dfhack.items.getPosition, so carried items (which may have incorrect or invalid positions) was messing up the logic.
as referenced on Reddit: https://www.reddit.com/r/dwarffortress/comments/195llnp/comment/khwp7xq/?utm_source=share&utm_medium=web2x&context=3

[emtpy-bin] fix emptying carried containers

---

changelog.txt
control-panel.lua
docs/control-panel.rst
docs/gui/settings-manager.rst
gui/settings-manager.lua
internal/control-panel/registry.lua

Fixes https://github.com/DFHack/dfhack/issues/3778

[gui/settings-manager] load, save, and autoload standing orders

---

changelog.txt
gui/design.lua

when a start position hasn't been selected yet.
inadvertently discovered in https://github.com/DFHack/dfhack/issues/4189

fix invalid dims display for stockpiles

---

gui/embark-anywhere.lua

and clean up mask checking code
Fixes: https://github.com/DFHack/dfhack/issues/4184

[gui/embark-anywhere] auto-dismiss screen after confirm

---

changelog.txt
docs/item.rst
item.lua

This adds a generic item manipulation tool, allowing to bulk forbid/dump/melt items based on various criteria or remove the aforementioned designations. Also provides an API to serve as backend for other scripts.

add `item` bulk forbid/dump/melt tool

---

changelog.txt
warn-stranded.lua

which are their own pathability group for some reason

[warn-stranded] don't warn on units going down open hatches

---

changelog.txt
gui/design.lua

fixes DFHack/dfhack#4202 by moving the assignment of `points` to after the center dragging logic which was manipulating self.marks

move down `local points` assigment on gui/design

---

changelog.txt
item.lua

@myk002 Turns out your one-line change breaks things: `types` is not a sequence, the keys are item type ids matching the filters, hardly continuous...

[item] fix enumeration of (present) item type ids

---

changelog.txt
gui/design.lua

This solves #4234 by moving the center dragging logic up and adding a separate check for no movement movement case for dragging marks.
Now clicking on the center mark a second time without moving will let the function flow and enter mark editing mode.
Fixes: https://github.com/DFHack/dfhack/issues/4234

Fix `gui/design` conflicting center point behavior

---

devel/scan-vtables.lua

since there are some symbols that are not in `dwarfort`:
-  `<vtable-address name='enablerst' value='0x7ffff6ce6008'/>`
-  `<vtable-address name='renderer_2d_base' value='0x7ffff6ce6020'/>`
-  `<vtable-address name='renderer_2d' value='0x7ffff6ce6108'/>`
-  `<vtable-address name='enabler_inputst' value='0x7ffff6ce6200'/>`
-  `<vtable-address name='MacroScreenLoad' value='0x7ffff6ce64e0'/>`
-  `<vtable-address name='MacroScreenSave' value='0x7ffff6ce6548'/>`
-  `<vtable-address name='renderer_offscreen' value='0x7ffff6ce65c8'/>`
-  `<vtable-address name='widgets::folder' value='0x7ffff6ce6bc0'/>`
-  `<vtable-address name='widgets::filter' value='0x7ffff6ce6c20'/>`
-  `<vtable-address name='widgets::multifilter::indiv_filter' value='0x7ffff6ce6c88'/>`
-  `<vtable-address …

[devel/scan-vtables] pick up unique vtable addresses only in g_src

---

modtools/reaction-trigger.lua

this is not a full implementation since the event will stay enabled at frequency 0 even if the reactions are cleared, but at least this will prevent the event from being enabled for users that don't even use the script (which is the majority)

[modtools/reaction-trigger] don't enable events until we need them

---

docs/gui/notify.rst
gui/notify.lua
gui/petitions.lua
internal/notify/notifications.lua

supports the following notifications:
-  traders_ready: Notifies when traders are ready to trade at the depot.
- petitions_agreed: Notifies when you have agreed to build (but have not yet built) a guildhall or temple.
- agitated_count: Notifies when there are agitated animals on the map.
- invader_count: Notifies when there are active invaders on the map.
configurable with a dialog similar to `gui/confirm`
Fixes: https://github.com/DFHack/dfhack/issues/4269
Fixes: https://github.com/DFHack/dfhack/issues/4207

[gui/notify] initial implementation

---

changelog.txt
combat-harden.lua
docs/combat-harden.rst

reinstate combat-harden

---

changelog.txt
item.lua

prevent errors on items without a `quality` field

[item] fix accessing quality field on items with no quality

---

changelog.txt
gui/blueprint.lua

Fixes https://github.com/DFHack/dfhack/issues/4298 by changing to a key not currently in use.

Change the playback start position hotkey to "o"

---

changelog.txt
fix/retrieve-units.lua

for real this time. The first fix was correct in spirit, but had a typo where we need to pass unit.id and instead passed unit

[fix/retrieve-units] *really* prevent duplicate units from being added to the active vector

---

changelog.txt
docs/gui/launcher.rst
gui/launcher.lua

so as not to conflict with the hotkey for `gui/design`. now that we (correctly) pass focus through, more hotkeys are active when gui/launcher is up

[gui/launcher] swap dev mode hotkey to alt

---

changelog.txt
docs/fix/stuck-worship.rst
fix/stuck-worship.lua
internal/control-panel/registry.lua

when they have multiple deities
addresses DF bug https://dwarffortressbugtracker.com/view.php?id=10918

[fix/stuck-worship] new tool: prevent units getting stuck worshipping

---

add-thought.lua
devel/export-dt-ini.lua

ref: https://github.com/DFHack/df-structures/pull/721

adjust to structures change

---

gui/notify.lua
internal/confirm/specs.lua

use tooltip enums in confirm
hide the notification panel when tooltips are shown that would be hidden by the notification panel
Fixes https://github.com/DFHack/dfhack/issues/3773

[confirm, gui/notify] use new tooltip enum identifiers

---

changelog.txt
gui/launcher.lua

and show history search edit field when history search is active in minimal mode
Fixes: https://github.com/DFHack/dfhack/issues/4326

[gui/launcher] fix up/down arrow keys being captured in minimal mode by unrendered widgets when in minimal mode

---

changelog.txt
docs/gui/launcher.rst
gui/launcher.lua

and fix up transparent hole in window background
hotkey was *not* conflicting with `gui/design`. It was a consequence of the bug fixed in https://github.com/DFHack/dfhack/pull/4330

[gui/launcher] restore dev mode hotkey to Ctrl-D

---

docs/gui/launcher.rst
gui/launcher.lua

This reverts commit 9694a80e3c9595848b8510ebdd411f45e9a767c4 from https://github.com/DFHack/scripts/pull/1009
Do not merge until 50.12 is released

Revert "temporarily revert to not using tab for 50.11 compat"

---

docs/ban-cooking.rst

in particular, add this sentence to explain why `mill` and `thread` types don't seem to do anything:
Note that in the vanilla game, there are no items that can be milled or turned
into thread that can also be cooked, so these types are only useful when using
mods that add such items to the game.

[ban-cooking] reformat and clarify documentation

---

changelog.txt
internal/quickfort/build.lua

now that the `orders` overlay makes the workshop profile state accessible to the player

[quickfort] support labor and skill profile properties

---

agitation-rebalance.lua
docs/agitation-rebalance.rst

move everything to smooth probabilities instead of triggering 100% after a threshold is crossed
remove armoky info and content
bump the global key to reset the persisted state format

agitation-rebalance v2

---

gui/teleport.lua
internal/confirm/specs.lua

Fixed typos of "seize" in confirm, and focus_string for gui/teleport being "autodump".

Fix "seize" typo in confirm, focus_string in gui/teleport

---

gui/unit-syndromes.lua

use dfhack.units.getReadableName, better formatting, etc.

[gui/unit-syndromes] make list items more readable

---

changelog.txt
docs/gui/aquifer.rst
gui/aquifer.lua

for interactive aquifer visualization and editing

add gui/aquifer

---

docs/open-legends.rst
open-legends.lua

allow returning to previous game mode, but add behavior changes to minimize chances players will accidentally shoot themselves in the foot:
- disable autosaves
- skip prompt to save game when re-entering legends mode
Fixes https://github.com/DFHack/dfhack/issues/4424

[open-legends] support --no-autoquit

---

changelog.txt
emigration.lua

Fixes https://github.com/DFHack/dfhack/issues/4443

[emigration] remove emigrating units from burrows

---

agitation-rebalance.lua
changelog.txt

also change culling behavior to prefer units near the beginning of the list over units near the end of the list. this allows partially-culled invasions to include animal people instead of just their war animals
Fixes https://github.com/DFHack/dfhack/issues/4448

[agitation-rebalance] fix bad logic for deciding whether to divert an invasion

---

internal/control-panel/registry.lua

Adds a control-panel line that sets the targets for peafowl similarly to other poulry.

Add peafowl to gui/control-panel poultry list

---

changelog.txt
internal/quickfort/dig.lua

only designate one canonical tile of a multi-tile tree for chopping when designating a multi-tile tree

[quickfort] better chop designation behavior

---

changelog.txt
docs/gui/create-item.rst
docs/gui/sandbox.rst
gui/sandbox.lua
modtools/create-item.lua

- `gui/sandbox` needed updates to how it initialized/restored the mode from adventure mode
- `gui/create-item` needed help finding the adventurer when there was no unit selected

update gui/sandbox and gui/create-item for adventure mode

---

changelog.txt
docs/item.rst
item.lua

[item] don't match spider webs

---

extinguish.lua

`plant_flags.is_burning` isn't used by DF anymore, renamed `plant_flags.unused_01`. Commented out the code.
Not sure if existing code is sufficient, or something else needs to be done.
DFHack/df-structures/pull/753

extinguish.lua: plant_flags.is_burning no longer used

---

changelog.txt
internal/gm-unit/editor_skills.lua

Fix gm-unit for skills above level 20

---

gui/advfort.lua
internal/quickfort/build.lua
internal/quickfort/place.lua
internal/quickfort/zone.lua
trackstop.lua

ref: https://github.com/DFHack/df-structures/pull/763

update to canonicalized structures

---

changelog.txt
internal/quickfort/place.lua

implemented for zones and forgot to implement for stockpiles.

[quickfort] fix stockpile label merge logic

---

gui/teleport.lua
internal/control-panel/common.lua

and some random cleanup
ref: https://github.com/DFHack/dfhack/pull/4664

use new helpdb has_tag api

---

confirm.lua

ref: https://github.com/DFHack/dfhack/pull/4671

[confirm] use new general dialogs.showYesNoPrompt

---

changelog.txt
docs/quickfort.rst
gui/quickfort.lua
internal/quickfort/list.lua
quickfort.lua

from both gui and commandline
rewrite blueprint load dialog to use ZScreenModal instead of FramedScreen
depends on https://github.com/DFHack/dfhack/pull/4671 for the deletion confirmation dialog
Fixes: https://github.com/DFHack/dfhack/issues/4480

[quickfort] implement blueprint deletion

---

gui/launcher.lua
internal/control-panel/common.lua
internal/control-panel/registry.lua

ref: https://github.com/DFHack/dfhack/pull/4674

use new mortal mode API

---

bodyswap.lua
changelog.txt
docs/bodyswap.rst

Also adds automatic re-centering on the unit you bodyswapped to!

Fix bodyswap to work on the latest adv-beta

---

gui/advfort.lua
internal/quickfort/build.lua
trackstop.lua

ref: https://github.com/DFHack/df-structures/pull/782

adapt to canonicalized structures

---

changelog.txt
lever.lua

note: the removed lever descriptions are not part of the documented behavior.

make `lever.lua` module capable

---

changelog.txt
control-panel.lua
internal/control-panel/common.lua

DF v50.13
DFHack 50.13-r2.1
---
In one of my games, I used the DFHack GUI control-panel to enable the `automilk` and `autoshear` repeating commands. Later, after having saved and resumed, I noticed that milk was not being gathered. Checking the control-panel showed both those repeats disabled. I am new to DF and DFHack (and Lua), so I don't know if this was the expected behavior, but I thought I would investigate.
I do not have anything set to "autostart" (which is for new embarks?). It looks like it also acts as a kind of override to the default-enabled definition when the "default" is requested (nil/missing "enabled" parameter in apply_command calls). An autostart configuration changes the behavior with respect to default-disabled commands: if the user enabled a default-disabled command …

control-panel repeats persistence

---

changelog.txt
internal/quickfort/build.lua
internal/quickfort/building.lua

and don't call farm plot obstructions errors even if it's the entire plot. it's common to lay down grids of farm plots, and it's ok if some don't make it due to stony ground

[gui/quickfort] don't call partial obstructions errors

---

changelog.txt
prioritize.lua

We had slaughter, but not butcher.
probably because hunting is rarely used and so it didn't come up in testing.

[prioritize] add ButcherAnimal to default prioritization list

---

changelog.txt
docs/devel/luacov.rst

depends on https://github.com/DFHack/dfhack/pull/4754

reinstate devel/luacov

---

gui/launcher.lua

removes an O(N^2) operation at game load, significantly speeding up load time
Thanks, @chdoc for prompting me to get luacov running again!

[gui/launcher] move history deduplication from load time to search time

---

docs/timestream.rst
timestream.lua

this allows us to remove special processing for noble counters, caravans, and all the individual season ticks that we were previously watching out for

[timestream] simplify code by ensuring we hit every season tick

---

changelog.txt
warn-stranded.lua

e.g. mothers carrying babies while they gather fruit from trees or mothers carrying babies while mining in inaccessible areas

[warn-stranded] ignore riders, only warn for ridees

---

changelog.txt
prioritize.lua

this pattern (which is in clear violation of the `next` function contract) happened to work on Linux, but not on Windows
ref: https://github.com/DFHack/dfhack/issues/4774

[prioritize] don't modify map as we iterate through it

---

gui/unit-syndromes.lua

`isGreatDanger` check is redundant since `isDanger` already checks it.

gui/unit-syndromes.lua: isDanger already implies isGreatDanger

---

changelog.txt
docs/list-waves.rst
list-waves.lua

supports deceased citizens and differentiates citizens that joined via petition
also prints names of wave members by default
several new options for filtering output
depends on https://github.com/DFHack/dfhack/pull/4816

[list-waves] use historical events for better representation of actual migration record

---

ban-cooking.lua
changelog.txt
docs/ban-cooking.rst

Increase the efficiency of ban-cooking by breaking the iteration of the material search when it finds the material ID being looked for (specifically 'STRUCTURAL' in this case).
The 'seeds' option now bans cooking for all seed producing plants and growths instead of just items that produce seeds and are brewable. The previous method could cause replantability to be lost for plants with cookable seed producing items, affecting milling in vanilla and other industries in mods. It may be a good idea to split this into two functions in the future, since the documentation only mentions that this function bans cooking seeds and not the items that produce them. This is also the only option that affects two significantly different groups of items, which is a bit inconsistent.

Efficiency increase for ban-cooking and change to 'seeds' option

---

changelog.txt
docs/gui/autodump.rst
gui/autodump.lua

Prevent `gui/autodump` from attempting to dump into or select within unallocated tiles (e.g., below HFS), which causes a script error. Also prevent dumping into hidden tiles.
Prevent dumping into walls. Set proper projectile flags so falling items don't get destroyed on impact.

Fix gui/autodump dumping into walls, etc.

---

changelog.txt
makeown.lua

we were neglecting to copy the generated name to the histfig, causing the unit to lose their name in legends mode

[makeown] set histfig name as well as unit name

---

changelog.txt
timestream.lua

there are more job types to handle here, but the algorithm is not yet known

[timestream] appropriately speed up eating and drinking

---

changelog.txt
docs/locate-ore.rst
locate-ore.lua

the code previously assumed that there was a single mineral block event per map block, but that is just not true
changed to scan for specific tiles belonging to each vein instead of just selecting any mineral tile in the vicinity
Fixes: https://github.com/DFHack/dfhack/issues/2751

[locate-ore] ensure we choose an appropriate mineral tile

---

timestream.lua

Fixes: https://github.com/DFHack/dfhack/issues/4823

[timestream] handle job timers

---

timestream.lua

better code based on better understanding of how unit timers work
discord discussion: https://discord.com/channels/793331351645323264/807444467140788254/1268654463930073098

[timestream] better account for unit actions with small timers

---

changelog.txt
gui/settings-manager.lua

when the player has no saved embark profiles
Fixes: https://github.com/DFHack/dfhack/issues/4811

[gui/settings-manager] fix position of settings restored message

---

docs/gui/journal.rst
gui/journal.lua
internal/journal/shifter.lua
internal/journal/table_of_contents.lua
internal/journal/text_editor.lua
test/gui/journal.lua

Add table of contents and undo/redo features to the `gui/journal` script.
Notable features:
- adding line starting from `#` give 1-th level ToC header. `##` and more give more indented ToC links
- `Ctrl+O` toggle ToC
- visible "Shifter" button to show/hide ToC
- ToC panel can be resized by mouse
- click in ToC entry scroll to given header in the text
- `CTRL+Z` undo, `CTRL+Y` redo
Bugfixes:
- 2846 numbers are not longer interpreted as cursor moves
- add buttons to insert new header of 1/2/3 indentation (to ToC panel?)
- stop render text on resize, it is slow
- consider hiding ToC panel (now panel without STYLE_FRAME can not be resized)

Add table of contents to Gui/journal

---

changelog.txt
timestream.lua

[timestream] more tick triggers according to reverse engineering

---

gui/journal.lua
internal/journal/table_of_contents.lua
test/gui/journal.lua

Show a simple tutorial for gui/journal on first use.
There are 2 tutorials:
1. Main text are tutorial. Its render one line below the text input. Its render only on first usage of the journal in given fort. Dissapearing when user provide any text to the text area
2. Table of contents tutorial - visible always when there is no section in text
Also, from now the table of contents panel is visible by default.

Show a simple tutorial for gui/journal on first use

---

gui/journal.lua
internal/journal/table_of_contents.lua

fixed some issues found during playtesting
- ToC help collided with hotkey hints
- ToC help had trailing newlines, causing spurious display of scrollbar
- ToC could be resized too small and hotkey hints were hidden
- HotkeyLabel widgets had too large of a hitbox
- ToC hotkey labels were visually enabled even when non-functional
@wiktor-obrebski FYI

[gui/journal] layout and widget behavior fixes

---

docs/timestream.rst
timestream.lua

Adjusting the calendar this way would bypass the tick trigger boundaries that we so carefully respect throughout the rest of the code. `timestream` had a default value of 1.0 for this setting, which did not skew the calendar. if anyone were to manually set this setting, though, there'd be trouble.
this brings us down to one settable setting, which is kind of weird, but the feature is too dangerous to leave in.

 [timestream] remove independent calendar speed settings

---

timestream.lua

discord discussion: https://discord.com/channels/793331351645323264/807444467140788254/1269323622300782715
DF scans the item vector with a stride of 50 and a start index based on the current tick. This PR ensures that every relevant tick is represented at least once per 1000 ticks so that no item is starved.
This change increases the CPU utilization of timestream from 9% to 10.5%, so a good next step would be to port this tool to c++

[timestream] ensure item scanning is not starved

---

changelog.txt
docs/embark-anyone.rst
embark-anyone.lua

Allows you to embark as any civilization, including dead and non-dwarven ones through a unretire-anyone style UI.
Currently suffers from some issues with counting sites, especially with non-dwarven civs. This is ultimately a cosmetic issue, but I'd be interested if anyone has a more accurate method of doing this.

Embark Anyone

---

changelog.txt
timestream.lua

Fixes: https://github.com/DFHack/dfhack/issues/4848

[timestream] ensure we don't skip unit birthdays

---

changelog.txt
empty-bin.lua

I made a mistake in the sequence of logical operators, so the command did not work on LIQUID_MISC.

fixed wrong logical operator sequence

---

changelog.txt
docs/idle-crafting.rst
idle-crafting.lua

This tool allows idle dwarfs to automatically satisfy their crafting needs. 
This isn't ready yet, but given that it involves quite a bit of reverse engineering and guesswork, I think this is the time to get some reviews.

new tool: idle-crafting

---

changelog.txt
internal/design/shapes.lua

Fixes: https://github.com/DFHack/dfhack/issues/3927
Simple line now counts properly:
Symmetrical double-line now counts property:
Counts properly even w/incresed line thickness:
Single point curved line still counts properly:
Dual point curved line still counts properly:
Freeform line which is open now counts properly:
Freeform line which is closed now counts properly:
Even the xtra thikk, freeform lines now count properly:

[gui/design] Update Line & Freeform tools to not overcount tiles

---

changelog.txt
docs/agitation-rebalance.rst
docs/caravan.rst
docs/confirm.rst
docs/devel/dump-tooltip-ids.rst
docs/devel/input-monitor.rst
docs/devel/spawn-unit-helper.rst
docs/fix/dead-units.rst
docs/fix/empty-wheelbarrows.rst
docs/fix/sleepers.rst
docs/gui/journal.rst
docs/gui/launcher.rst
docs/gui/settings-manager.rst
docs/gui/teleport.rst
docs/gui/tiletypes.rst
docs/list-waves.rst
docs/modtools/set-need.rst
docs/modtools/syndrome-trigger.rst

Here are some spelling fixes for `scripts`.
I made separate commits for a couple of "code" references (an enum member, and a DFHack path). The new spellings for these seem to be correct:
- `df.need_type[2]` gives `PrayOrMeditate`
- `syndrome-trigger` is under `modtools` in code and docs

docs spelling fixes

---

changelog.txt
internal/control-panel/registry.lua

and document the synergy with `cleanowned-nodump`

[gui/control-panel] highlight tailor's no dump option

---

changelog.txt
gui/quickfort.lua
internal/quickfort/zone.lua

ref: https://github.com/DFHack/dfhack/issues/4881
depends on: https://github.com/DFHack/dfhack/pull/4889

[quickfort] integrate with preserve-rooms

---

changelog.txt
docs/position.rst
position.lua

Adds an option (`-c`, `--copy`) to copy the current cursor position to the system clipboard.
Also implements display of the current historical era.
Fort site position isn't implemented yet. We might want to handle adventurer world position along with that (refer to #1194 for how that's done w/r/t travel map).

position.lua: additional info, option to copy cursor pos

---

changelog.txt
deep-embark.lua

e.g. when using `gui/embark-anywhere` to embark on the ocean or on a steep mountainside

[deep-embark] work properly in embarks with no wagon and no land

---

changelog.txt
docs/position.rst
position.lua

Print current site world coords, or adventurer (if applicable). Also swapped out uses of `math.floor` for `//`. Decreased padding zeros for current year from 5 to 3 digits (which is still sufficient to distinguish it from a month or day).
Script is now tagged `adventure`. It needs testing by someone on the adventurer beta. (Needs to be run inside site, outside site, travel mode, and dead.)
Moved some changelog entries in the template section to the proper spot (if nobody fixes that before this PR merges).

Position.lua: site/adv world coords

---

changelog.txt
docs/notes.rst
gui/journal.lua
internal/journal/table_of_contents.lua
internal/journal/text_editor.lua
notes.lua
test/gui/journal.lua

This PR introduce notes feature that allows to add simple notes to the game map.
Features:
- `notes add` to add new note to the map (in place of keyboard cursor)
- enable `notes.map_notes` overlay to render notes on the map as green pins
- click on map notes to open note details and edit screen
- click few times to toggle between notes if they are all in the same tile
- the overlay has been written with performance in mind (and profiled)
TODO:

`notes` script

---

assign-minecarts.lua
changelog.txt

Fixes: https://github.com/DFHack/dfhack/issues/4914

[assign-minecarts] handle case where minecart is assigned but is missing

---

changelog.txt
docs/fix/dry-buckets.rst
fix/dry-buckets.lua

Fixes: https://github.com/DFHack/dfhack/issues/4854

`fix/dry-buckets`: prompt DF to recheck aid requests when we empty a bucket

---

armoks-blessing.lua
changelog.txt
docs/rejuvenate.rst
rejuvenate.lua

- set related histfig data when we set unit data
- don't allow player to set age into childhood/babyhood
- set max age as per the age ranges in the unit's caste
- reuse the rejuvenate logic in `armoks-blessing`, which had a copied, inferior implementation
Includes #1284
Fixes: https://github.com/DFHack/dfhack/issues/4894

[rejuvenate]: ensure histfig data stays consistent and respect age-related caste data per race

---

rejuvenate.lua

Fixed mothers attempting to seek their units that were babies by removing the unit id from the ANY_BABY table. Also made those grown babies act like adults by updating some flags.
Fixes: https://github.com/DFHack/dfhack/issues/4894

Fixed mothers attempting to seek their units that were babies

---

changelog.txt
exterminate.lua

still takes IDs on the commandline, though

[exterminate] show descriptive names for races

---

necronomicon.lua

because the vector indices are not guaranteed to be the same as the ids (though it appears that they usually are)

[necronomicon] use find methods instead of array indexing

---

docs/gui/journal.rst
internal/journal/text_editor.lua
test/gui/journal.lua

Corresponds with: ~~https://github.com/DFHack/dfhack/pull/4933~~ https://github.com/DFHack/dfhack/pull/4935
@wiktor-obrebski FYI

[gui/journal] migrate TextEditor to use new text navigation keys

---

changelog.txt
internal/quickfort/notes.lua

Thanks, [Erendir](https://discord.com/channels/793331351645323264/1017471248567124049/1289672651354406973)!

[quickfort] deduplicate notes blueprints if run on repeat

---

changelog.txt
docs/fix/dry-buckets.rst
docs/fix/stuck-worship.rst
fix/stuck-worship.lua
internal/control-panel/registry.lua

Stop `fix/stuck-worship.lua` from spamming the console every time it shuffles prayer.

Silence stuck-worship.lua spam

---

changelog.txt
docs/gui/gm-editor.rst
gui/gm-editor.lua

and an option to turn it off in case of need to browse garbage
also update docs with more examples
depends on https://github.com/DFHack/dfhack/pull/4977 for `_type._union` check
edit: added feature: show red `[union structure]` badge when viewing a union structure

[gui/gm-editor] support stringification of language_name fields

---

changelog.txt
docs/fix/wildlife.rst
fix/wildlife.lua
internal/control-panel/registry.lua

Fixes: https://github.com/DFHack/dfhack/issues/4456

initial implementation of fix/wildlife

---

gui/civ-alert.lua
internal/confirm/specs.lua
uniform-unstick.lua

Depends on https://github.com/DFHack/dfhack/pull/4980

use new squads focus strings

---

changelog.txt
docs/fix/loyaltycascade.rst
fix/loyaltycascade.lua
makeown.lua

and allow fix/loyaltycascade to work on non-dwarves

[makeown, fix/loyaltycascade] clear enemy status cache for makeown

---

changelog.txt
makeown.lua

should finally fix the "converted creature attacks fellow citizens" issues
also sanitizes the professions of both the unit and the histfig

[makeown] remove converted units from current conflicts

---

gui/notify.lua

ref: https://github.com/DFHack/df-structures/pull/808

migrate main_hover_instruction identifiers to new names

---

changelog.txt
internal/confirm/specs.lua

The `df.main_hover_instruction` enum was updated [here](https://github.com/DFHack/df-structures/commit/04e2b185f2a2e09388079e7a1f37b7b016dca46f#diff-05529cd0f67c2aa615be427227c4060f584d82ff55924ed7ee5bd917a5849faf). Updating references to this enum in confirm to fix some confirm dialogs not working due to referencing the old enum values.

Fix confirm hover instructions

---

gui/manipulator.lua

will re-enable once the tool is in production shape

remove gui/manipulator overlay hotkey hint while in dark launch

---

changelog.txt
internal/quickfort/build.lua

merge prep for #1332 and #1336
Fixes: DFHack/dfhack#5012

Fix blueprinted constructions over stairs

---

changelog.txt

Added line to changelog related to PR #1332
- `gui/quickfort`: fix build mode evluation rules to allow placement of various furniture and constructions on tiles with stair shapes or without orthagonal floor.

Update changelog.txt related to PR #1332

---

changelog.txt
emigration.lua

Fixes: https://github.com/DFHack/dfhack/issues/5011

Persist the last cycle tick in `emigration` for a more consistent gameplay experience

---

changelog.txt
rejuvenate.lua

due to the less than comparison, age must be converted to a number or else any attempt to use that argument causes the script to fail with "attempt to compare string with number".

Convert age argument to number in rejuvenate.lua

---

fix/wildlife.lua

Fixes: https://github.com/DFHack/dfhack/issues/5044

[fix/wildlife] don't vaporize caged or restrained wildlife

---

changelog.txt
internal/notify/notifications.lua

unless they are
Fixes: https://github.com/DFHack/dfhack/issues/5037

[gui/notify] don't mark visitors as hostile

---

changelog.txt
gui/design.lua

thank you @nibirubingus for bringing my attention to this in #1345

[gui/design] handle zone painting for dims tooltip

---

changelog.txt
exportlegends.lua

Loading multiple worlds or timelines in legends mode originally did not reset the state, allowing stale data to be used in filtering. This resulted in incorrect results being presented.
This patch resets `racefilter` state on world or map load to ensure the state remains up to date.
Map loading is checked to prevent issues with `open-legends` which is able to access legends mode without reloading the world.

Fix usage of stale state in legends racefilter

---

.gitattributes

from the [gitattributes](http://kernel.org/pub/software/scm/git/docs/gitattributes.html) man page
> union
> Run 3-way file level merge for text files, but take lines from both versions, instead of leaving conflict markers. This tends to leave the added lines in the resulting file in random order and the user should verify the result. Do not use this if you do not understand the implications.

Configure `merge=union` for `changelog.txt` to reduce merge conflicts

---

gui/design.lua

forgot this last time - this removes it from `gui/overlay`

make `gui/design.rightclick` fullscreen

---

changelog.txt
docs/immortal-cravings.rst
immortal-cravings.lua

so goblins and other naturally immortal races can benefit
also use getReadableName for output messages
Fixes: https://github.com/DFHack/dfhack/issues/5097

[immortal-cravings] match active caste flag instead of curse flag

---

changelog.txt
docs/caravan.rst
internal/caravan/pedestal.lua

Fixes: https://github.com/DFHack/dfhack/issues/5041

[caravan] add filter for written works

---

changelog.txt
docs/gui/settings-manager.rst
gui/settings-manager.lua

also include the reserved_barrels setting when importing/exporting standing orders
Fixes: https://github.com/DFHack/dfhack/issues/5004

[gui/settings-manager] add overlay for editing reserved_barrels setting

---

changelog.txt
fix/dry-buckets.lua

Fixes: https://github.com/DFHack/dfhack/issues/5148

[fix/dry-buckets] don't empty buckets for in-use wells

---

changelog.txt
fix/wildlife.lua

so players aren't confused if they happen to have the viewscreen nearby
Fixes: https://github.com/DFHack/dfhack/issues/5123

[fix/wildlife] don't poof wildlife that is currently onscreen

---

changelog.txt
internal/gm-unit/editor_profession.lua

Fixes: https://github.com/DFHack/dfhack/issues/5122

[gui/gm-unit] refresh map sprite when profession is changed

---

changelog.txt
internal/unit-info-viewer/skills-progress.lua

Fixes: https://github.com/DFHack/dfhack/issues/5098

[gui/unit-info-viewer]: use xp formula instead of limited range of enum values

---

changelog.txt
gui/sitemap.lua

as requested on Steam: https://steamcommunity.com/app/2346660/discussions/0/604144025816107092/

[gui/sitemap] show visitor and invader affiliations

---

changelog.txt
internal/caravan/common.lua

Fixes: https://github.com/DFHack/dfhack/issues/5168

[caravan] fix wood detection logic for trading

---

changelog.txt
gui/design.lua

I found myself sometimes needing to "exit twice" to exit out of a dig designation that didn't have a selection started.
- optionally, boot DF from scratch
- monitor .selection_pos with gm-editor
- `gui/gm-editor buildreq.selection_pos`, Alt-a to enable live updates
- if needed, set .selection_pos to (0,0,0) to simulate a fresh DF start
- the values can be edited in gm-editor, or
- `:lua ~buildreq.selection_pos:assign(xyz2pos(0,0,0))`
- start one of the other (non-building placement) modes covered by RightClickOverlay (e.g. dig designation), but don't start a selection
- trigger LEAVESCREEN or right-click
- **Expect**: selection mode is exited
- **Result**: selection mode remains active
- the gm-editor window will show that .selection_pos was changed to (-30k,-30k,-30k)
- a second trigger …

RightClickOverlay: check focus before clearing selection_pos

---

devel/scan-vtables.lua

fixes crash on Linux when bringing up the squad assignment panel

add temporary workaround for widgets::widget

---

changelog.txt
internal/notify/notifications.lua

After 15 irl mins, a notification pops up, telling you how many mins it has been since last save. Clicking this notification opens a Yes/No prompt that asks if you wish to quicksave. This can be turned off same as all the other notifications.

Add a save reminder to notifications panel

---

changelog.txt
docs/pref-adjust.rst
pref-adjust.lua

This feature returns the list of Likes for a selected dwarf.
This script may be useful if:
* a user wants to view a quick list of likes for a dwarf
* a user wants to view the list of likes after updating a dwarfs likes
* Other scripts may find this helpful, as this functionality is not otherwise exposed via dfhack

Feat: Add "show" to pref-adjust

---

changelog.txt
internal/advtools/convo.lua

This also fixes the extra options not appearing in the conversation menu in the "Ask directions" screen

Fix df.talk_choice_type def not being up to date for internal/convo.lua

---

changelog.txt
gui/rename.lua

Changing the language of a unit's name caused an error here, preventing the name from being fully set on the unit.

[gui/rename] fix typo causing error on language change

---

changelog.txt
internal/control-panel/registry.lua

for Windows users. until https://github.com/DFHack/dfhack/issues/4292 is fixed

remove craft-age-wear tweak from the control panel

---

gui/civ-alert.lua
gui/launcher.lua
gui/manipulator.lua
gui/quickfort.lua
internal/caravan/movegoods.lua
internal/caravan/pedestal.lua
internal/caravan/trade.lua
internal/gm-unit/editor_civilization.lua

https://github.com/DFHack/dfhack/issues/5226

change hotkeys that conflict with EditField's Ctrl-a

---

advtools.lua
autocheese.lua
changelog.txt
docs/advtools.rst
docs/autocheese.rst
docs/hide-tutorials.rst
hide-tutorials.lua
internal/control-panel/registry.lua

Reverts DFHack/scripts#1390 and reinstates new features

Revert "temporarily back out new features"

---

docs/gui/spectate.rst
gui/spectate.lua

@TymurGubayev here's the stub for the config UI for https://github.com/DFHack/scripts/pull/1365

add stub gui/spectate

---

devel/scan-vtables.lua

ensures that we always scan from upper memory ranges to lower so we get the complete structure instead of one that might have been truncated due to hitting the end of the memory range
also gets rid of the janky two-pass scanning

[devel/scan-vtables] clean up logic and ensure scan order

---

idle-crafting.lua

so we don't end up with huge null arrays in the json.
loader works with both old and new formats. improvement is transparent to the end user

[idle-crafting] convert the keys of the allowed table to strings for persistence

---

changelog.txt
internal/notify/notifications.lua

Fixes: https://github.com/DFHack/dfhack/issues/5253

[gui/notify] colorize moody dwarf warnings

---

changelog.txt
internal/confirm/specs.lua

the name isn't perfectly faithful to what is displayed, but it's much more useful than no description at all
Fixes: https://github.com/DFHack/dfhack/issues/5024

[gui/confirm] show a description of the order you are about to delete

---

internal/caravan/trade.lua
internal/confirm/specs.lua

enum -> bitfield
should fix errors in trade dialogs/overlays and confirm click detection on trade screen

[caravan] adapt to changes in goodflag structure

---

changelog.txt
docs/gui/sitemap.rst
gui/sitemap.lua

uses new spectate API to register follow target in spectate follow history

[gui/sitemap] implement shift click to follow

---

changelog.txt
docs/prioritize.rst
prioritize.lua

and print number of already-prioritized jobs when prioritizing all jobs of a specified type

[prioritize] don't include already prioritized jobs in output of -j

---

gui/spectate.lua

* set a stress level instead of the whole table
* place the list widget deeper than the toggle buttons

spectate.lua: fix individual stress levels

---

changelog.txt
modtools/spawn-liquid.lua

With `liquid_type` Magma and `liquid_level` 0, the `flow_forbid` flag was being set, creating unexpectedly unpathable tiles.
This change makes it so setting the liquid_level to zero with any type results in a `liquid_type` of water, the default for empty tiles, as well as with the `flow_forbid` flag unset.
Fixes https://github.com/DFHack/dfhack/issues/5284

Prevent flow_forbid from being set without liquid present

---

changelog.txt
docs/gui/design.rst
gui/design.lua

ensure vanilla tooltip is hidden when ours is enabled
depends on: https://github.com/DFHack/dfhack/pull/5316
Fixes: https://github.com/DFHack/dfhack/issues/5281

[gui/design] toggle vanilla dimensions flag on overlay toggle

---

changelog.txt
idle-crafting.lua

Assigning crafting jobs to nobles holding meetings leads to those jobs being incompletely canceled (both references are removed, but the job is not canceled) ([discord discussion](https://discord.com/channels/793331351645323264/807444467140788254/1346542301865971814))

`idle-crafting` :  do not assign crafting jobs to nobles holding meetings

---

gui/notes.lua
internal/notes/note_manager.lua
notes.lua
test/gui/journal.lua
test/gui/notes.lua
test/overlay/notes.lua

Add tests for `notes` overlay and for `gui/notes` script.

Add tests for notes overlay script

---

changelog.txt
colonies.lua
devel/light.lua
devel/query.lua
devel/tree-info.lua
docs/extinguish.rst
docs/firestarter.rst
docs/gui/create-item.rst
docs/launch.rst
docs/modtools/create-item.rst
docs/putontable.rst
docs/toggle-kbd-cursor.rst
gui/advfort.lua
gui/blueprint.lua
gui/companion-order.lua
gui/create-item.lua
gui/tiletypes.lua
hfs-pit.lua
launch.lua
modtools/create-item.lua
putontable.lua
source.lua
stripcaged.lua
teleport.lua
toggle-kbd-cursor.lua

Make use of `gui.dwarfmode` cursor fns in a number of scripts. Also `same_xyz` where possible.
Added a `pos` arg for `gui/create-item` to define output position. Made `modtools/create-item` respect "opts.pos" being passed into `hackWish`.
Fixed up tiletypes in `hfs-pit`. Outdated numbers were being used instead of enums, causing weird behavior.
`toggle-kbd-cursor` now ignores adv mode. It would just reposition the look cursor if left as-is, and we can't easily toggle adv look mode. (Simulated input required.)
Added `adventure` tag to `extinguish` and `firestarter` since guidm changes made them function. (Other scripts like `colonies` will function, but aren't particularly useful due to lack of persistence.) `toggle-kbd-cursor` gets `fort` tag since it only functions in fort/arena. …

Use guidm cursor fns

---

colonies.lua
devel/light.lua
docs/colonies.rst
gui/companion-order.lua
launch.lua
teleport.lua

mostly obsolete docs, some tag updates

light cleanup

---

changelog.txt
rejuvenate.lua

Fixes: https://github.com/DFHack/dfhack/issues/5320

[rejuvenate] update portrait, sprite, and labors when converting to adult

---

changelog.txt
docs/idle-crafting.rst
idle-crafting.lua

Note: this also introduces a check that a unit still has crafting needs before it gets assigned a crafting job.

`idle-crafting`: ignore happy units until their needs are strong

---

changelog.txt
gui/journal.lua

can happen if keys are mashed in just the right way
Fixes: https://github.com/DFHack/dfhack/issues/5367

[gui/journal] don't pass pause events through the ui

---

changelog.txt
docs/fix/loyaltycascade.rst
docs/makeown.rst
fix/loyaltycascade.lua
makeown.lua

Fixes: https://github.com/DFHack/dfhack/issues/1422

[fix/loyaltycascade, makeown] remove unit from current conflict activities

---

changelog.txt
list-agreements.lua

Fixes DFHack/dfhack#3551
I've done some basic tests, but I don't have a fortress against which to thoroughly validate that this works as expected.

Fix logic for calculating petition age

---

changelog.txt
gui/sandbox.lua

Thank you to u/[zainonn](https://www.reddit.com/user/zainonn/) on [reddit](https://www.reddit.com/r/dwarffortress/comments/1jqeg12/comment/mn2i8k2/?context=3) for finding this issue (left over from the Great Reorg)

[gui/sandbox] fix inorganics raws scan

---

changelog.txt
docs/starvingdead.rst
emigration.lua
starvingdead.lua

and ensure we don't decay too often
Fixes: https://github.com/DFHack/dfhack/issues/5399

[starvingdead] properly handle state loading

---

changelog.txt
docs/gui/mod-manager.rst
gui/mod-manager.lua

Closes DFHack/dfhack#3985
Depends on: https://github.com/DFHack/dfhack/pull/5395

`gui/mod-manager`: Add a window showing the active mods in a world

---

gui/family-affairs.lua
gui/manipulator.lua
gui/sitemap.lua
gui/unit-info-viewer.lua

ref: https://github.com/DFHack/dfhack/pull/5431

adapt to longer strings returned from getReadableName

---

gui/sitemap.lua
gui/unit-info-viewer.lua
prioritize.lua

in particular, `gui/sitemap` now has 2 rows per unit

refine display of readable names

---

changelog.txt
gui/design.lua
internal/design/shapes.lua

gui/design
Add new option to draw N-point stars.
* The default has 5 points, use 'B'/'b' to increase/decrease points.
* They can be hollow or filled, and inverted.
* The next-point offset can be increased/decreased using 'N'/'n' which particularly affects 7 point stars and above to make them spikier or smoother, but can also be used to decrease to 1 to make symmetrical polygons or increase to N which only paints the vertexes.
* The orientation can be changed by adding a main axis point using 'v' and moving this to point in the desired direction.

gui/design: add option to draw N-point stars, hollow or filled or inverted, and change the main axis to orient in any direction

---

changelog.txt
docs/modtools/moddable-gods.rst
modtools/moddable-gods.lua

modernized API and fixed logic
Fixes: https://github.com/DFHack/dfhack/issues/4417

[modtools/moddable-gods] rewrite and update

---

changelog.txt
remove-stress.lua

While in its current implementation remove-stress will over time bring down long-term stress, it seems much more intuitive to just immediately remove the long-term stress.

remove-stress also removes long-term stress, which also immediately removes stressed and haggard statuses

---

changelog.txt
gui/blueprint.lua

ref: https://github.com/DFHack/dfhack/issues/4994

[gui/blueprint] add zone to the phase list

---

changelog.txt
internal/design/shapes.lua

Prevent line thickness from extending outside the map boundary

Fix line thickness extending outside map

---

deteriorate.lua

[deteriorate] fix usable parts check

---

changelog.txt
internal/gm-unit/editor_counters.lua

for 51.12 compatibility
should have been included in 51.12 release but we missed it

remove `think_counter` from `gui/gm-unit`

---

changelog.txt
gui/mod-manager.lua

mod-manager.lua: do not except on missing mod metadata

---

changelog.txt
gui/journal.lua

obvious typo causing unintended performance lost in journal.lua
`collapsed` is typo-ed as `colllapsed` which is always nil
since `not colllapsed` is always true, unintended performance lost when `table_of_contents_panel` is collapsed.
https://github.com/DFHack/scripts/blob/8a2c8e7b13d703da672532d408e4250dd11a86c9/gui/journal.lua#L75
```lua
shifter.Shifter{
view_id='shifter',
frame={l=0, w=1, t=1, b=2},
-- the intended name is collapsed here
collapsed=not toc_visible,
on_changed = function (collapsed)
self.subviews.table_of_contents_panel.visible = not collapsed
self.subviews.table_of_contents_divider.visible = not collapsed
-- if statement always true because it's spelled "colllapsed"
if not colllapsed then
self:reloadTableOfContents()
end
self:ensurePanelsRelSize()
self:updateLayout() …
```

bug fix: journal.lua minor performance lost due to typo "colllapsed"

---

changelog.txt
embark-anyone.lua

Test the current viewscreen to ensure that it is the choose_start_site viewscreen, before trying to use it.
The bug: if the embark-anyone script is executed on any viewscreen **other than** the embark viewscreen, it aborts with a stack trace.
This bugfix makes it cleanly abort with a reasonably-descriptive error message.
This was found while diagnosing Issue #5509, but is not related.
Minimal changes to the script.

embark-anyone.lua bugfix: Test the current viewscreen

---

changelog.txt
make-legendary.lua

prevent `make-legendary` from assigning skill -1

---

changelog.txt
internal/caravan/pedestal.lua

Two minor fixes to `internal/common/pedestal.lua`.  No user-visible changes, except that removing items from a pedestal using the DFHack interface will work correctly.
Well-tested.  *Extensive* comments in each commit.

Pedestal fixes3

---

changelog.txt
uniform-unstick.lua

* added quivers, backpacks, and flasks/waterskins to uniform analysis
* the ``--drop`` option now only evaluates clothing as possible items to drop
* the ``--free`` option no longer redundantly reports an improperly assigned item when that item is removed from a uniform
* the ``--drop`` and ``--free`` options now only drop items which are actually in a unit's inventory
* the ``--all`` and ``--drop`` options, when used together, now print the separator line between each unit's report in the proper place
There are notes in the commits' log messages.
I listed all of these changes as Fixes; arguably the first and second are Misc Improvements.

Minor fixes to uniform-unstick

---

changelog.txt
docs/fix/archery-practice.rst
fix/archery-practice.lua
internal/control-panel/registry.lua

This is a new tool to temporarily mitigate the issue of ranged units not being able to practice at the archery range ('Soldier (no item)' issue). It scans inside the quivers of units in squads that are currently training, combines training ammo items until it reaches a stack size of 25, and drops any surplus ammo items on the ground so that each quiver will contain only one training ammo item.
An entry was added in `internal/control-panel/registry.lua` to execute this script every 449 ticks.
Limitation: unlike `combine`, this tool ignores item material, quality, and maker to simply combine whatever training ammo is contained inside the quiver.

add new tool `fix/archery-practice`

---

ban-cooking.lua
changelog.txt

This patch allows ban-cooking to ban honey/brewable materials added by creatures other than honey bees. This includes vanilla bumblebees, though their honey is not currently obtainable in vanilla. However, there are mods that make bumblebees hiveable, as well as adding other types of hiveable bees.

Support for modded honey in ban-cooking

---

autocheese.lua
changelog.txt
husbandry.lua
idle-crafting.lua
immortal-cravings.lua

Depends on https://github.com/DFHack/dfhack/pull/5567

adapt Lua tools to use new API functionality for creating and assigning jobs

---

docs/fix/archery-practice.rst
internal/control-panel/registry.lua

Also adds a line in the tool's documentation to state that the bug should already be fixed in 52.05.

Make `fix/archery-practice` disabled by default
