DFHack/scripts

gui/gm-editor.lua
added shift-esc to fully exit from editor
added 'gui/gm-editor toggle' to toggle editor (by mifki's req). This saves position in editor.
=> changes to gui/gm-editor.lua:

combine-plants.lua
(Finally) fixed a recursion bug in the original script that prevented it from recursing into sub-containers.
=> Fix combine-plants recursion bug

season-palette.lua
season-palette is a simple script that allows automatic switching of the color palette with the changing seasons. It also provides a Lua function that allows loading arbitrary color palettes.
=> Add season-palette

autofarm.rb
Shamelessly lifted from @theit8514 
https://github.com/theit8514/dfhack/commit/1e5bca087f4e68eb8f807b9569c986858e412cc2
Tested and confirmed to work in 43.03 at least no worse than the current version
=> autofarm: make surface farms detect local biome

add-thought.lua
=> Made string emotions actually work for add-thought

modtools/change-build-menu.lua, modtools/if-entity.lua
change-build-menu provides a simple API for adding or removing buildings from DF's build sidebar. if-entity runs a command if the current entity matches the given ID.
=> Add "change-build-menu" and "if-entity".

autofarm.rb
This reverts commit 0e19cb73b2eddb76e3d68e1131d28e28ba3dcc85, reversing
changes made to 35cd74b0688565e8b37275d20d99911c7f5b2c7e.
Doesn't work the way I thought.
=> Revert "Merge pull request #10 from ab9rf/autofarm-dev"

add-thought.lua
Also removes flags because that became a complex object
=> add-thought explicit number conversion

unforbid.rb
Started it with a mandatory 'all' param in case other options are wanted in the future.
=> Add unforbid script to unforbid all items.

full-heal.lua
there was a .job_type missing in line 151 causing it to throw errors.
=> fix to small issue in full-heal.lua

digfort.rb
simple check for a line to be #< or #> edit then added a case for it.  It now will go up or down z based on the symbol.
=> incorporated Z change into digfort

autounsuspend.rb, unsuspend.rb
Minor documentation fix for: https://github.com/DFHack/dfhack/issues/1167
=> Fix documentation for autounsuspend to correct which jobs get unsuspended

gui/gm-editor.lua
Fixes dfhack/dfhack#1193 - lethosor
=> Add type name to edit box headers

devel/export-dt-ini.lua
De-hardcode the flag part of DT ini. Values did not actually change, but it should safer for the future.
=> export-dt-ini: Compute flag values from DFHack's data

exportlegends.lua
sort xml nodes like they are in DF 0.44.xx legends.xml so it is easier to process legends.xml and legends_plus.xml parallel
=> exportlegends.lua - sort xml nodes

gui/gm-unit.lua
Better wound description, hidden non-working buttons added some comments
=> Some work on gm-unit

devel/export-dt-ini.lua
New offsets for the next version of Dwarf Therapist.
=> export-dt-ini: add tool offsets

modtools/create-unit.lua
Minor changes only. Required for #55 as per lethosor's suggestion.
=> create-unit: modifications to allow use of createNemesis() function by external scripts

deathcause.rb, digfort.rb, show-unit-syndromes.rb
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/dfhack/scripts).
=> Apply fixes from CodeFactor

remove-stress.lua
=> remove-stress: also remove tantrums, depression, and obliviousness

lua.lua
Part of https://github.com/DFHack/dfhack/pull/1331 that I forgot to commit and push earlier.
=> Support '^' prefix to call printall_recurse

devel/export-dt-ini.lua
Required by https://github.com/Dwarf-Therapist/Dwarf-Therapist/commit/4f13317c0e24678e7103f5258ef652d56cf84a2c from PR https://github.com/Dwarf-Therapist/Dwarf-Therapist/pull/122.
=> export-dt-ini: add item base flags offset

modtools/force.lua
Mega**B**east to Mega**b**east
=> Fixed Typo in modtools/force.lua

full-heal.lua
also:
- added module support
- removed historical figure death dates upon resurrection
- removed ghost data
- stopped wagon resurrection
- fixed a minor issue with post-resurrection hostility
closes Dfhack/dfhack#1242
=> full-heal: added "-all", "-all_civ" and "-all_citizens" args

growcrops.rb
- Added support for "all", growing all planted crops
- Split code up for easy-to-follow flow
- Commented code
=> Added growcrops all

combine-drinks.lua
i.e.
```
found 12 drinks
removed 1 drinks
```
=> Update combine-drinks.lua to have simliar default output to combine-plants

exportlegends.lua
This will be used in my new tool, but obviously other programs can use it.
=> Added rivers to the exportlegends custom xml export.

gui/create-item.lua
This script had `--@ module = true` but lacked module mode support. This fixes that.
=> gui/create-item: added moduleMode check and made functions global

tame.lua
needed to set the civ_id on the tamed animal or it won't be seen by autobutcher.
=> fix tame to work with autobutcher

gui/companion-order.lua
Not sure if it was a typo or if things were changed between versions of DF, but this line was causing an error when the Leave command was executed. I've changed it to the correct value, so the script no longer crashes when that command is used.
=> Fix error in gui/companion-order's Leave command

gui/gm-unit.lua
Add attribute editor to the gui/gm-unit editor
=> gm-unit: add attribute editor

exportlegends.lua
extends exportlegends.lua to export information about identities uses by historical figures
=> export identity information

modtools/create-item.lua
modtools/create-item specifies -matchingGloves and -matchingShoes params for creating item pairs, this commit properly support them on dfhack 0.47.02-alpha0
=> modtools/create-item: support stated params

exportlegends.lua
=> fixed body abuse event and abstract temples

color-schemes.lua, gui/color-schemes.lua
**Hello**
I've posted not long ago here [r/dwarffortress](https://www.reddit.com/r/dwarffortress/comments/fcxe65/dfhack_colorschemes_gui/) about my new script and I'm ready to do a pull request.
Both scripts `color-schemes` and `gui/color-schemes` are commented and have a help string.
I'm open to questions/suggestions/remarks ! :)
=> Color-schemes script and gui

exportlegends.lua
Probably only dependent on what's accepted in df-structures, but cannot rule out that something is in the pull request.
=> handled new compounds, warning on legends compound elements

gui/advfort.lua
=> Update advfort.lua to new version of df

exportlegends.lua
NOTE: This script relies on mapping made in currently pending DFHack/df-structures#386 being available.
The indication that a DFHack beta may be imminent resulted in a desire to ensure these additions have a chance to be considered, even though the structures work hasn't been processed yet.
=> added export of vague relationship data.

exportlegends.lua
fixes https://github.com/DFHack/dfhack/issues/1540
=> fixes exportlegends maps error 1540

exportlegends.lua
=> cleaned up interaction string export

catsplosion.lua, changelog.txt
=> handled single caste creatures

exportlegends.lua
https://github.com/DFHack/df-structures/pull/389
=> adapted to changed structures

exportlegends.lua
Before:
```
<item_type>weapon</item_type>
<item_subtype>short sword</item_subtype>
...
<item_type>earring</item_type>
<item_subtype>-1</item_subtype>
```
With update:
```
<item_type>weapon</item_type>
<item_subtype>short sword</item_subtype>
...
<item_type>earring</item_type>
```
=> Make <item_subtype> optional instead of -1 when no subtype

exportlegends.lua
Fixing issue https://github.com/DFHack/dfhack/issues/1552
=> Removing empty claims (#1552)

modtools/create-unit.lua
Improvements:
- added `-skills`: allows skills to be added to the created unit 
- added `-profession`: allows a unit type token to be applied to the created unit
- added `-customProfession`: allows a custom profession name to be given to the unit
=> modtools/create unit: added -skills, -profession, -customProfession

exportlegends.lua
This matches the other tags.
This was added last month so should not break old code:
https://github.com/DFHack/scripts/commit/2b4b9ae73f21a4253312cf61b97ecfd479a49928
=> Switched circumstance-tag from PascalCase to snake_case

changelog.txt, remove-stress.lua
Added argument -value [ integer ] to set stress to this value (if current stress is higher) instead of -1,000,000.
=> Added an argument to remove-stress.lua to set stress to value

modtools/moddable-gods.lua
Removed unused-but-nevertheless-required domain and description arguments, added support for neuter gender, removed a line that just wasn't doing anything anymore, made "depictedAs" actually do something
EDIT: May be a crash upon use, don't merge just yet.
=> Fixes moddable-gods up

gui/advfort.lua
This is intended for better user experience as sometimes civ can have no recipes/iron/etc...
Fixes https://github.com/DFHack/dfhack/issues/1604
=> advfort: add auto/manual civ selection

quickfort.lua
DFHack/dfhack#499 Implement the quickfort set command and reading from the dfhack-config/quickfort/quickfort.txt config file
=> Quickfort set

quickfort.lua
DFHack/dfhack#499 Define primary data structure and implement blueprint tokenization
=> Quickfort tokenization

internal/quickfort/place.lua
Once I implemented query mode in #171, I realized that I didn't have to refactor the stockpiles plugin in order to expose the logic to iterate through stockpile settings -- I could just generate a query blueprint and initialize the stockpiles through the UI!
Although initializing in C++ would execute faster and would avoid screen movement as we move the cursor around, there is a high risk that I would break something in the stockpiles plugin if I were to reorganize its thousands of lines of code. It may be worth it someday to do it "properly" in C++, but with query mode, that day doesn't have to be today.
=> implement stockpile setting init with query mode

internal/quickfort/building.lua
as per http://www.bay12forums.com/smf/index.php?topic=176889.msg8174898#msg8174898
=> quickfort: allow extents to be connected diagonally

internal/quickfort/list.lua, quickfort.lua
This allows searching in `quickfort list` by blueprint mode or substring.
=> Quickfort list filter

internal/quickfort/list.lua
the data here *used* to have a modeline variable. not anymore. update code to reflect that.
=> fix typo in list filtering code

internal/quickfort/build.lua
so we'll be ready for when there are 3 required params. until the new API is live, this will just be sending a few extra params that will get ignored.
=> align with upcoming buildingplan api

changelog.txt, quickfort.lua
Companion to https://github.com/DFHack/dfhack/pull/1661
See https://github.com/DFHack/dfhack/issues/1653
=> Integrate quickfort docs into main docs

changelog.txt, internal/quickfort/build.lua
fixes floor hatches, floor grates, and floor bars
=> [quickfort] fix valid tile detection for floor hatches and kin

internal/quickfort/build.lua
so they will be applied for all building creation code paths
merge after DFHack/dfhack#1676
=> [quickfort] migrate post construction fixup functions to core

changelog.txt, internal/quickfort/build.lua, internal/quickfort/orders.lua
Requires changes to dfhack/buildings.lua in DFHack/dfhack#1683
=> [quickfort] support for bookcases, display cases, and offering places

gui/workshop-job.lua
=> use new isSuitableMaterial API in gui/workshop-job

changelog.txt, fix/corrupt-equipment.lua
For https://www.bay12games.com/dwarves/mantisbt/view.php?id=11014
Closes dfhack/dfhack#1678
Note that this requires https://github.com/DFHack/dfhack/commit/fb44b26b47eca729646e316efc22cfe2a138691e
=> Add fix/corrupt-equipment

gui/advfort.lua
Also added support for pressure plates, maybe...?
=> Fixed advfort hatches (which were broken)

changelog.txt, internal/quickfort/meta.lua
print out blueprint names that a ``#meta`` blueprint is applying so it's easier to understand what meta blueprints are doing
=> [quickfort] more output while applying #meta blueprints

.gitignore
does this need a changelog entry?
=> git ignore kdevelop project and build files

changelog.txt, internal/quickfort/command.lua, internal/quickfort/common.lua, internal/quickfort/parse.lua
useful for scratch space or personal development notes.
documentation coming in a DFHack/dfhack PR
=> [quickfort] new blueprint mode: ignore

changelog.txt, internal/quickfort/zone.lua
DFHack/dfhack#1758
fix silly oversight
=> [quickfort] create zones active by default

internal/quickfort/command.lua, internal/quickfort/dialog.lua, internal/quickfort/parse.lua
in addition to prettifying the command status, now if a command
fails when run from the gui, I'll know what it was trying to do.
=> [quickfort] refactor command formatting and use it in gui

changelog.txt, internal/quickfort/command.lua, internal/quickfort/list.lua, quickfort.lua
=> [quickfort] use new processArgsGetopt() for parameter parsing

changelog.txt, digfort.rb
step 2 in the DFHack/dfhack#1644 deprecation plan
=> [digfort] add deprecation warnings to digfort

internal/quickfort/place.lua, internal/quickfort/query.lua
just a few lines here and there that didn't quite get merged right when I split my work across the dev branches.
=> [quickfort] fix a few minor merge errors

internal/quickfort/aliases.lua, internal/quickfort/query.lua, test/quickfort/aliases_unit.lua
=> [quickfort] refactor quickfort/aliases and add unit tests

internal/quickfort/notes.lua, test/quickfort/notes_unit.lua
=> [quickfort] refactor quickfort/notes and add unit tests

devel/luacov.lua
- remove duplicate printing of stats file name
- correct message about when the report will be empty
=> [luacov] edit message output in the devel/luacov script

changelog.txt, internal/quickfort/map.lua, test/quickfort/map_unit.lua
fix an off-by-one error in map edge detection
=> [quickfort] refactor quickfort/map and add unit tests

changelog.txt, devel/block-borders.lua
Inspired by some map-block-related comments, e.g. in dfhack/dfhack#1806
Requires https://github.com/DFHack/dfhack/commit/5e09fd882da8998b739461776db340f8eddce232
=> Add devel/block-borders

gui/blueprint.lua
so DFHack/dfhack#1849 will pass CI
=> [gui/blueprint] add dummy gui/blueprint so plugin docs will build

fix/drop-webs.lua, fix/webs.lua
A script to cause floating webs to fall
=> Add fix/drop-webs.lua

changelog.txt, clear-webs.lua
Following a [request on the forums](http://www.bay12forums.com/smf/index.php?topic=178462.0), here's a simple script for clearing the map of webs, similar to `clear-smoke.lua`. I also made it reset the 'webbed' counter on units, for players looking to free their dwarves from giant cave spiders and the like.
=> Created clear-webs.lua

gui/blueprint.lua, test/gui/blueprint.lua
=> [gui/blueprint] report created filenames

test/gui/blueprint.lua
to hopefully prevent merge conflicts for simultaneous code reviews
=> [gui/blueprint] add in comment lines to separate future tests

deep-embark.lua, flashstep.lua, gui/teleport.lua, teleport.lua, test/teleport.lua
=> [teleport] use new common functionality in the Units module

internal/quickfort/command.lua
brought to my attention by falknor on discord
=> [quickfort] display an error for unexpected extra arguments

changelog.txt, gui/blueprint.lua, test/gui/blueprint.lua
allows the player to point and click with the mouse to select start and end tiles
=> [gui/blueprint] mouse support

gui/mass-remove.lua, internal/quickfort/query.lua
=> [quickfort, gui/mass-remove] use new library guidm.enterSidebarMode()

changelog.txt, gui/advfort.lua
Removed out-of-date and unused changelog. Add nicer workshop display. Fixes https://github.com/DFHack/dfhack/issues/1880
=> Advfort.lua tidyup and small fixes

workorder.lua
@quietust 
fields given names in https://github.com/DFHack/df-structures/commit/253dfb374cca068843809022dc27605b1b8d99e3
=> [workorder] use newly id'd manager_order_condition_item fields

gui/gm-editor.lua
```
gui/gm-editor dfhack
```
Before:
After:
=> make gm-editor's search case-insensitive

test/quickfort/list_integration.lua
depends on DFHack/dfhack#1871 for the actual test files
=> [quickfort] add integration tests for quickfort list

changelog.txt
=> [quickfort] update changelog

changelog.txt, devel/query.lua
=> Adds json option to devel/query

changelog.txt, warn-starving.lua
implements/resolves DFHack/dfhack#1809.
unfortunately my computer is busted at present so i haven't been able to test this, but i believe it should all be correct?
=> add warn-starving sanity option

changelog.txt, gui/blueprint.lua, test/gui/blueprint.lua
Part of milestone 2 of DFHack/dfhack#1842
supports new functionality in DFHack/dfhack#1963
=> [gui/blueprint] support new --splitby option

changelog.txt, gui/blueprint.lua, test/gui/blueprint.lua
DFHack/dfhack#1842
depends on DFHack/dfhack#1965
Finally the work put into `CycleHotkeyLabel` is starting to pay off : )
=> [gui/blueprint] support format param

gui/blueprint.lua, test/gui/blueprint.lua
part of milestone 2 for DFHack/dfhack#1842
GUI support for the new `--playback-start` param introduced in DFHack/dfhack#1968
the start position can be set anytime before the blueprint range is finalized. after being set, the selected start position will appear as a flashing blue 'X' on the screen (as long as the tile position is onscreen). While the start position is being selected, the "action text" at the top of the blueprint panel changes to "Select the playback start" and the "cancel" text changes to "Cancel selection" (if it's not already saying that due to an in-progress blueprint range selection).
if the range of the blueprint is in the middle of being set, the cursor location is saved and restored after the start position is set.
an error is shown if the blueprint range is …
=> [gui/blueprint] allow blueprint start pos to be interactively set

changelog.txt, internal/quickfort/build.lua
like DF itself allows. this will be tested in an upcoming dfhack repo ecosystem test PR.
=> [quickfort] allow grates, bars, and hatches to be built on flat floor

test/quickfort/quickfort_unit.lua
using new default for preserve_engravings
=> [quickfort] fix unit tests

firestarter.lua
Fixes dfhack/dfhack#2001
Script broke after dfhack/df-structures@253dfb374cca068843809022dc27605b1b8d99e3
=> firestarter: fix field names

devel/eventful-client.lua
this will allow a user to visually verify if the arguments are sane
=> output more info in devel/eventful-client handlers

gui/blueprint.lua, test/gui/blueprint.lua
DFHack/dfhack#1842
Also update the unit tests (which caught a lot of real bugs during the migration!)
=> [gui/blueprint ] use new fancy library widgets

changelog.txt, internal/quickfort/build.lua, internal/quickfort/building.lua
Fixes DFHack/dfhack#2116
now correctly detects valid tiles where natural or constructed ramps are involved
=> [quickfort] fix building on top of natural ramps for constructions and bridges

changelog.txt, gui/gm-editor.lua
=> Revert enter passthrough from gui/gm-editor

build-now.lua
https://github.com/DFHack/dfhack/issues/2174
=> Fix for build-now walls flashing red

internal/quickfort/common.lua, internal/quickfort/dig.lua, internal/quickfort/preview.lua
instead of the leftover custom implementation
=> [quickfort] use library ensure_key

changelog.txt, gui/dfstatus.lua
Also made the flags check use a more compact style which comes with a micro-optimisation
=> Make gui/dfstatus not count items owned by traders

changelog.txt, gui/unit-info-viewer.lua
=> [gui/unit-info-viewer] display unit size in cubic centimeters

changelog.txt, gui/workflow.lua
=> [gui/workflow] restore functionality to status screen hotkeys

changelog.txt, lua.lua
as proposed on Discord.
Other history files will be moved in the dfhack repo.
=> move lua.history to dfhack-config/lua.history

gui/autobutcher.lua
companion to DFHack/dfhack#2256
=> adapt gui/autobutcher to plugin changes

changelog.txt, gui/quickfort.lua, internal/quickfort/list.lua, test/gui/quickfort.lua
before, we just showed a stack trace.
Brought to my attention by a friendly reddit user
https://www.reddit.com/r/dwarffortress/comments/wuuz3v/comment/im22bbw/?utm_source=share&utm_medium=web2x&context=3
=> [quickfort] show error message when blueprints directory not found

changelog.txt, internal/gm-unit/editor_skills.lua
and restore the list filter when skills are adjusted with those hotkeys
depends on DFHack/dfhack#2272
=> Fix gui/gm-unit skill adjustment hotkeys

gui/advfort.lua, internal/advfort/advfort_items.lua
it's not a user-facing script. It's just library code for gui/advfort
=> [gui/advfort] move gui/advfort_items into internal/

docs/gui/launcher.rst, gui/launcher.lua
=> [gui/launcher] use Label's scrollbar instead of faking our own

changelog.txt, devel/query.lua, docs/devel/query.rst
Increase the default maxlength value and prints a message when queries are truncated.
=> Improves devel/query usability

gui/launcher.lua
=> [gui/launcher] reuse the current view to avoid flicker on command run

gui/launcher.lua
Not just if the new parent screen is a dfhack screen.
As discussed on Discord.
=> [gui/launcher] dismiss launcher if parent screen changes

changelog.txt, gui/blueprint.lua, gui/quantum.lua, gui/quickfort.lua
=> use the new getMousePos API

docs/add-recipe.rst, docs/add-thought.rst, docs/animal-control.rst, docs/armoks-blessing.rst, docs/assign-attributes.rst, docs/assign-beliefs.rst, docs/assign-facets.rst, docs/assign-goals.rst, docs/assign-preferences.rst, docs/assign-skills.rst, docs/gui/advfort.rst
=> address feedback on the docs

changelog.txt, warn-stealers.lua
=> Change NEW_UNIT_ACTIVE to UNIT_NEW_ACTIVE in warn-stealers

gui/blueprint.lua, test/gui/blueprint.lua
Fixes DFHack/dfhack#2306
also get rid of the unused in-script help text
=> [gui/blueprint] support new --smooth option

gui/blueprint.lua
=> [gui/blueprint] support new rooms phase

gui/blueprint.lua, test/gui/blueprint.lua
=> [gui/blueprint] support nometa param

gui/blueprint.lua, test/gui/blueprint.lua
=> [gui/blueprint] support new "group" split strategy

docs/gui/launcher.rst, gui/launcher.lua
=> [gui/launcher] add docs for the on-screen keyboard

devel/query.lua
- Fixes debug line typo
- Updates help doc print
- Fixes typo in --tile selection printout
=> Updates devel/query

changelog.txt, dwarf-op.lua
=> Updates dwarf-op help doc, and fixes processing bug for names

docs/empty-bin.rst
=> Update empty-bin.rst to mention other container types

gui/advfort.lua, gui/blueprint.lua, gui/cp437-table.lua, gui/load-screen.lua, gui/quantum.lua, gui/settings-manager.lua, test/gui/blueprint.lua
=> adapt script code to newly correct mouse events

docs/gui/overlay.rst, gui/overlay.lua
=> add gui/overlay

test/gui/blueprint.lua
To get tests to pass for DFHack/dfhack#2462
=> update tests for View.visible change

changelog.txt, docs/gui/launcher.rst, gui/launcher.lua
DFHack/dfhack#2329
depends on DFHack/dfhack#2462
=> [gui/launcher] implement minimal mode

changelog.txt, docs/emigration.rst, emigration.lua
and interpret enable and disable
https://github.com/DFHack/dfhack/issues/2338
Depends on https://github.com/DFHack/dfhack/pull/2473
=> [emigration] persist and reload state

changelog.txt, docs/prioritize.rst, prioritize.lua
and interpret enable and disable
DFHack/dfhack#2338
Depends on DFHack/dfhack#2473
=> [prioritize] persist and reload state

gui/overlay.lua
=> migrate gui/overlay to the new draggable panels

changelog.txt, devel/hello-world.lua
depends on DFHack/dfhack#2500
screenshot:
=> update example code in devel/hello-world.lua

unsuspend.lua
still needs proper tile graphics for the X, though.
skip buildingplan integration if buildingplan isn't available
=> allow unsuspend overlay to work in v50

changelog.txt, devel/inspect-screen.lua, docs/devel/inspect-screen.rst
=> update devel/inspect-screen for the new world order

changelog.txt, devel/tile-browser.lua, docs/devel/tile-browser.rst
=> add graphical tile texture browser

docs/prioritize.rst, prioritize.lua
largest change: remove job type that no longer exists (StoreItemInHospital) from the default list.
=> [prioritize] update code and docs

gui/autobutcher.lua
make into draggable, resizable window
make list highlight easier to read
=> update autobutcher gui

devel/find-offsets.lua
Goes with https://github.com/DFHack/df-structures/pull/501
=> Update world.units.bad field name in devel/find-offsets

changelog.txt, gui/cp437-table.lua
movable window, widgets to manage rendering, state, and text cursor
depends on DFHack/dfhack#2551
=> update gui/cp437-table to use modern widgets

devel/inspect-screen.lua, devel/tile-browser.lua, docs/gui/gm-editor.rst, gui/autobutcher.lua, gui/cp437-table.lua, gui/gm-editor.lua, gui/launcher.lua, gui/overlay.lua, gui/pathable.lua, gui/prerelease-warning.lua, gui/quickcmd.lua
depends on DFHack/dfhack#2558 and DFHack/dfhack#2564
=> ZScreen updates

docs/superdwarf.rst, superdwarf.lua
There's a bit of cleaning I'm yet to do, I'll mark the PR as ready once it's done
=> Fix argument handling in superdwarf

dfhack-quickstart-guide.lua, docs/dfhack-quickstart-guide.rst, docs/gui/launcher.rst, gui/launcher.lua
Fixes DFHack/dfhack#2592
Displays the contents of hack/docs/docs/Quickstart.txt in game, in paged format.
Depends on the guide being written, which is in progress.
=> dfhack-quickstart-guide

docs/load-save.rst, dwarf-op.lua, gui/load-screen.lua, load-save.lua, lua.lua
doesn't make these tools work, though
=> change references to data/save to just save

allneeds.lua, changelog.txt, docs/allneeds.rst
Taking over the work at https://github.com/DFHack/scripts/pull/90 and enacting all the comments Lethosor made.
=> Add allneeds.lua script

make-monarch.lua
This updates the entity link to use `assignment_vector_idx`, which is new in 50.xx
=> Update make-monarch to use assignment_vector_idx

changelog.txt, internal/quickfort/build.lua
=> [quickfort] fix placement check for coverable tiles

docs/quicksave.rst
=> update docs for quicksave

docs/gui/launcher.rst, gui/launcher.lua
so output from previous commands isn't lost when you're running multiple commands
=> [gui/launcher] keep a separate command output buffer

devel/hello-world.lua, gui/launcher.lua, gui/overlay.lua
and fix a few bugs with frames in gui/overlay
=> use new frame styles

changelog.txt, gui/quickcmd.lua
clearly I didn't finish the conversion the first time
Fixes DFHack/dfhack#2698
=> [qui/quickcmd] change ZScreen-Screen to a regular ZScreen-Window

autofish.lua
Oops. This is what I get for trying to code tired. 😛 
- fixed a bug causing autofish to not count raw fish.
- fixed persistent data not being loaded and updated, causing state desyncs.
- reduced update frequency to 7 days.
- fixed running main code when sending disable command.
- comment cleanup.
=> Autofish bugfixes

build-now.lua, changelog.txt
constructions no longer override the tile above with floor if there's already something there.
=> build-now fix

changelog.txt, gui/create-item.lua
there we go, all nice and clean in a separate branch after downloading the github desktop app
=> re-add corpsepiece stuff to separate branch (gui/create-item corpsepiece spawning functionality)

changelog.txt, docs/forbid.rst, docs/unforbid.rst, forbid.lua, unforbid.lua
Closes: https://github.com/DFHack/dfhack/issues/2417
Also this can be closed now too: https://github.com/DFHack/dfhack/issues/2421
=> Add underwater check to unforbid all

changelog.txt, gui/create-item.lua
added search functionality to the creature selection window, as well as those for body parts, tissues, and general creature materials
=> filter creature list prompts

catsplosion.lua, changelog.txt
as found by AndrielChaoti on Discord
=> restrict catsplosion to live, active units

changelog.txt, docs/gui/control-panel.rst, docs/gui/overlay.rst, gui/control-panel.lua, gui/overlay.lua
everything else moves to gui/control-panel
Fixes DFHack/dfhack#2774
=> focus gui/overlay on widget repositioning

docs/gui/launcher.rst, gui/control-panel.lua, gui/launcher.lua
=> [gui/launcher] use new tabs for help text/command output pages

changelog.txt, docs/gui/launcher.rst, gui/launcher.lua
so you can still pause and unpause, even while typing a command
=> [gui/launcher] allow double spacebar to pause/unpause the game

changelog.txt, docs/gui/control-panel.rst, docs/gui/launcher.rst, gui/control-panel.lua, gui/launcher.lua
=> [gui/launcher, gui/control-panel] allow double-click to do something useful

changelog.txt, gui/unit-syndromes.lua
we forgot to actually pass input processing to the widgets
=> [gui/unit-syndromes] fix input processing

changelog.txt, gui/gm-editor.lua
and offset the new window slightly so it doesn't completely cover up the existing window
=> support multiple windows for gui/gm-editor

docs/force.rst, force.lua, modtools/force.lua
and prevent crashy FeatureAttack events
Fixes DFHack/dfhack#2876
Fixes DFHack/dfhack#2793
=> clean up force and modtools/force

changelog.txt, devel/hello-world.lua
Updates devel/hello-world to use a ZScreen
=> Modernize devel/hello-world

changelog.txt, docs/quickfort.rst, gui/blueprint.lua, internal/quickfort/list.lua, internal/quickfort/set.lua
=> use new blueprint paths

changelog.txt, docs/quicksave.rst, quicksave.lua
=> fix autosave with code reverse engineered by ab9rf

changelog.txt, gui/launcher.lua
this is a stop gap solution for true tabulation, which would take a lot more work
Should this be considered to fix DFHack/dfhack#3023 and fix DFHack/dfhack#3024?
=> [gui/launcher] replace tabs with spaces in command output

changelog.txt, combine.lua, docs/combine.rst, gui/control-panel.lua
=> support quiet combine and add "combine all" maintenance script

changelog.txt, gui/control-panel.lua
Fixes maxarq/mrau-ui#2 (I believe)
=> support overlays from scripts with capital letters

changelog.txt, suspendmanager.lua
Fix https://github.com/DFHack/dfhack/issues/3074
=> Suspendmanager: Fix suspending floor grates, bridges and others

changelog.txt, docs/gui/cp437-table.rst, gui/cp437-table.lua
as per feedback from esotericist on discord: https://discord.com/channels/793331351645323264/873014631315148840/1089082478523850823
=> [gui/cp437-table] widgetify the onscreen keyboard and add backspace button

changelog.txt, gui/cp437-table.lua
=> overhaul onscreen kbd to be usable on steam deck

docs/gui/civ-alert.rst, gui/civ-alert.lua
=> add gui/civ-alert

caravan.lua, changelog.txt, docs/caravan.rst
Fixes DFHack/dfhack#3111
also simplify logic in loops so it's easier to grok and read and doesn't do loops in loops
=> [caravan] fix logic for expanding and collapsing

changelog.txt, docs/stripcaged.rst, stripcaged.lua
=> [stripcaged] unforbid dumped items and allow forbidden items to be ignored

changelog.txt, prioritize.lua
why, json, why?
Fixes DFHack/dfhack#3071
=> [prioritize] work around json converting numbers to strings

caravan.lua, changelog.txt
fix list height and position issues
Fixes DFHack/dfhack#3155
=> [caravan] fix list height and position issues

changelog.txt, prioritize.lua
as per reddit discussion linked in the issue
Fixes DFHack/dfhack#3145
=> revise default prioritized job list

changelog.txt, warn-starving.lua
=> [warn-starving] don't warn about uncomfortable dead units

changelog.txt, gui/control-panel.lua
=> add faststart to system services and persist setting

internal/quickfort/command.lua
=> [quickfort] output a better error message when orders are attempted

changelog.txt, gui/control-panel.lua
=> [gui/control-panel] don't offer gui/automelt when not in fort mode

changelog.txt, deteriorate.lua, docs/deteriorate.rst
as per: https://github.com/DFHack/dfhack/issues/3221
=> Deteriorate: check for residents and don't deteriorate usable parts

gui/control-panel.lua
=> [gui/control-panel] add option for hiding the terminal console at startup

gui/control-panel.lua, gui/launcher.lua
DFHack/dfhack#3206
also give control panel preferences readable labels instead of just showing the variable names
=> set/respect armok hiding in control panel/launcher

docs/fix/dry-buckets.rst, fix/dry-buckets.lua
Buckets will now be emptied also in buildings.
Description and output changed.
=> Now also empties in buildings

changelog.txt, docs/gui/gm-editor.rst, gui/gm-editor.lua
=> [gui/gm-editor] add --freeze option for inhibiting calls to parent's logic()

docs/toggle-kbd-cursor.rst, toggle-kbd-cursor.lua
converts the command from an alias to a proper script
Fixes DFHack/dfhack#3292
=> add toggle-kbd-cursor

changelog.txt, gui/launcher.lua
=> [gui/launcher] show DFHack version in the default help text

gui/control-panel.lua
=> add work-now as a user-controlled System service

changelog.txt, gui/design.lua
Previous update broke these features
=> Fix errors when trying to designate buildings, fix auto stair designations

gui/control-panel.lua
DFHack/dfhack#3191
DFHack/dfhack#3381
=> [gui/control-panel] add option for full text search for list filters

gui/overlay.lua
=> [gui/overlay] use dynamic texpos values

changelog.txt, docs/gui/gm-editor.rst, gui/gm-editor.lua
=> [gui/gm-editor] also halt rendering when --freeze is passed

changelog.txt, docs/gui/autodump.rst, gui/autodump.lua
Fixes DFHack/dfhack#3316
Fixes DFHack/dfhack#3362
Fixes DFHack/dfhack#3138
=> add gui/autodump

changelog.txt, internal/quickfort/dig.lua
=> [quickfort] fix carving restrictions under buildings

changelog.txt, deathcause.lua
Fixes DFHack/dfhack#2923
fix based directly on Quietust's input. Thanks!
=> [deathcause] fix incorrect weapon being implicated in a death

changelog.txt, internal/quickfort/dig.lua
=> [quickfort] properly rotate carved track tiles

changelog.txt, gui/blueprint.lua, gui/quickfort.lua, internal/quickfort/parse.lua, internal/quickfort/place.lua
also add support for recording stockpiles in gui/blueprint
tagged on a new feature: display a small marker on the "start" tile for the blueprint that you're applying so you can see if you've got it centered properly
partner to DFHack/dfhack#3408
building towards DFHack/dfhack#2974
=> [gui/quickfort] support place mode

gui/sandbox.lua
remove tools since they are slow to add and are of questionable utility. we can add them back if there is call for it.
add quivers, which fixes DFHack/dfhack#3426
=> [gui/sandbox] remove tools; add quivers

internal/quickfort/zone.lua
creates locations as necessary
=> [quickfort] updated zone and location logic

internal/quickfort/place.lua
uses the `stockpiles` API to configure stockpiles
=> [quickfort] updated stockpile property and configuration logic

changelog.txt, prioritize.lua
Discovered some critical, but ignored, job types while testing Dreamfort
=> [prioritize] add some more important job types

internal/quickfort/place.lua
=> [quickfort] logistics integration for place mode

gui/gm-editor.lua
still fine-tuning the auto-validation change
=> [gui/gm-editor] allow structs to be viewed again

changelog.txt, makeown.lua
=> [gui/sandbox] generate names for citizens

changelog.txt, internal/quickfort/dig.lua
=> [quickfort] traffic restrictions can be applied anywhere

changelog.txt, internal/quickfort/meta.lua
=> [quickfort] protect against infinite loops

changelog.txt, internal/quickfort/command.lua
=> [quickfort] don't duplicate messages when repeating blueprints

unsuspend.lua
=> use new textures for unsuspend overlay

caravan.lua, changelog.txt
=> [caravan] select all/none for liaison trade requests

gui/control-panel.lua
expose preference option created in DFHack/dfhack#3543
=> [gui/control-panel] expose key suppression preference

autofish.lua
=> [autofish] protect against missing units

gui/pathable.lua
=> [gui/pathable] adapt to changes in pathable plugin

changelog.txt, docs/quickfort.rst, internal/quickfort/list.lua, quickfort.lua
Fixes DFHack/dfhack#3326
Depends on DFHack/dfhack#3586
=> [quickfort] add modded blueprint libraries to the blueprint list

gui/control-panel.lua
=> [gui/control-panel] add dwarfvet to fort list

gui/launcher.lua
=> [gui/launcher] adjust to EditField behavior changes

.github/workflows/build.yml
refactors docs and lint actions to use the reusable versions
adds test action
=> reuse reusable workflos from the dfhack repo

.github/workflows/build.yml
=> align with the new repository-agnostic workflows

changelog.txt, internal/caravan/common.lua, internal/caravan/trade.lua
=> [caravan] fix price calculations for items affected by trade agreements

devel/scan-vtables.lua, docs/devel/scan-vtables.rst
Linux-only for now
Requires https://github.com/DFHack/dfhack/pull/3657
=> Add devel/scan-vtables

changelog.txt, docs/hide-interface.rst, hide-interface.lua
run it to hide the interface so you can take clean screenshots or just sit back and watch dwarves live.
=> new tool: hide-interface

changelog.txt, internal/caravan/movegoods.lua
provide a toggle: show bins and hide items within or show items within and hide bins
DFHack/dfhack#3509
=> [caravan] see inside bins

changelog.txt, docs/gui/gm-editor.rst, gui/gm-editor.lua
so you don't have to right click (or hit esc) multiple times to go all the way back up the stack to exit
=> [gui/gm-editor] shift right click to quick exit

changelog.txt, gui/gm-editor.lua
so I can finally stop wondering if I remembered to toggle it
=> [gui/gm-editor] visually indicate whether autoupdate is on

caravan.lua, changelog.txt
Fixes DFHack/dfhack#3608
Depends on DFHack/dfhack/#3713
=> [caravan] cancel TradeAtDepot jobs if all caravans are leaving

changelog.txt, gui/design.lua
=> [gui/design] don't conflict with default keybindings

changelog.txt, gui/liquids.lua
requested on Steam: https://steamcommunity.com/app/2346660/discussions/0/3820796140084699146/
=> [gui/liquids] support removing river sources

changelog.txt, docs/necronomicon.rst, necronomicon.lua
and pretty up output format a little
Fixes DFHack/dfhack#3619
=> [necronomicon] also check for secrets in scrolls

ban-cooking.lua, changelog.txt, docs/ban-cooking.rst
also rewrite docs with more explanation about why the tool exists
Fixes DFHack/dfhack#2840
Fixes DFHack/dfhack#3741
=> add --unban option and remove unused code

changelog.txt, gui/launcher.lua
as suggested by u/BeerNTacos on reddit: https://www.reddit.com/r/dwarffortress/comments/16en35c/comment/jzxaqnl/?utm_source=share&utm_medium=web2x&context=3
=> [gui/launcher] show tagged tools as autocomplete options when a tag is typed

unsuspend.lua
depends on [#3716](https://github.com/DFHack/dfhack/pull/3716)
=> use reserved range for tileset

devel/inspect-screen.lua, exportlegends.lua, gui/autochop.lua, gui/autodump.lua, gui/blueprint.lua, gui/control-panel.lua, gui/design.lua, gui/gm-editor.lua, gui/gm-unit.lua, gui/liquids.lua, gui/mass-remove.lua, gui/masspit.lua, gui/overlay.lua, gui/quickfort.lua, gui/sandbox.lua, gui/seedwatch.lua, gui/unit-syndromes.lua, hide-tutorials.lua, internal/caravan/trade.lua, internal/gm-unit/editor_body.lua, test/gui/blueprint.lua
depends on https://github.com/DFHack/dfhack/pull/3816
=> adjust to new mouse event semantics

caravan.lua, changelog.txt, docs/caravan.rst, internal/caravan/pedestal.lua
Once we move our item filtering/widget library to `stocks`, this can move there too
=> dialog for assigning items to display furniture

gui/cp437-table.lua, gui/sandbox.lua, hide-tutorials.lua
depends on https://github.com/DFHack/dfhack/pull/3841
=> use new centralized mouse handling

gui/control-panel.lua
Related to PR: https://github.com/DFHack/dfhack/pull/3829
=> added preserve-tombs to fort services list

changelog.txt, gui/sandbox.lua
and getting double-handled by the vanilla UI
=> [gui/sandbox] fix clicks not getting cleared

changelog.txt, hide-tutorials.lua
the button was sometimes not responding to the click. waiting a frame seems to make it more reliable.
=> [hide-tutorial] don't click too quickly for embark tutorial

CMakeLists.txt
remove unused lines, don't install empty docs dir
=> [scripts] clean up installation paths

gui/gm-editor.lua, warn-stranded.lua
depends on https://github.com/DFHack/dfhack/pull/3922
=> take advantage of new highlight parameter

devel/unit-path.lua, gui/pathable.lua, warn-stranded.lua
depends on https://github.com/DFHack/dfhack/pull/3933
=> use new walkability group api

changelog.txt, docs/sync-windmills.rst, sync-windmills.lua
=> new tool: sync-windmills

changelog.txt, docs/gui/design.rst, gui/design.lua
=> [gui/design] add floating label indicating selected dimensions

changelog.txt, emigration.lua
Fixes https://github.com/DFHack/dfhack/issues/3991
=> [emigration] fix structure path to work details

build-now.lua, changelog.txt, docs/build-now.rst
Fixes https://github.com/DFHack/dfhack/issues/2614
Depends on https://github.com/DFHack/dfhack/pull/4028
=> [build-now] reinstate build-now, using DF-native completeBuild

docs/gui/mod-manager.rst, exportlegends.lua, gui/civ-alert.lua, gui/design.lua, gui/mod-manager.lua, internal/caravan/movegoods.lua, internal/caravan/pedestal.lua, internal/caravan/trade.lua, internal/caravan/tradeagreement.lua, startdwarf.lua, suspendmanager.lua, trackstop.lua, unsuspend.lua
for use in the control panel overlays tab
=> add descriptions to script overlays

quickstart-guide.lua
not like there are any yet, but when we *do* add them, we'll be ready!
=> support utf-8 chars in the quickstart guide

docs/full-heal.rst
Fixes https://github.com/DFHack/dfhack/issues/4071
=> [full-heal] add usage notes to docs

internal/quickfort/zone.lua
ref: https://github.com/DFHack/df-structures/pull/695
=> [quickfort] update flags to new names

changelog.txt, internal/confirm/specs.lua
as requested on Reddit https://www.reddit.com/r/dwarffortress/comments/18x651d/comment/kgayx2p/?utm_source=share&utm_medium=web2x&context=3
=> [confirm] add hotkey reassignment/clearing prompt

changelog.txt, docs/gui/reveal.rst, gui/reveal.lua
Fixes: https://github.com/DFHack/dfhack/issues/4078
=> implement gui/reveal for safe terrain peeking

changelog.txt, uniform-unstick.lua
and don't report on that unit's equipment issues
also give some advice on fixing the problem
=> [uniform-unstick] warn if unit's squad is from another site

gui/launcher.lua
Depends on https://github.com/DFHack/dfhack/pull/4149
=> use new divider widget in gui/launcher

changelog.txt, gui/mass-remove.lua
depends on https://github.com/DFHack/dfhack/pull/4164
=> [gui/mass-remove] support unremove for buildings and constructions

docs/gui/reveal.rst, gui/reveal.lua
and better handling of gui/reveal hell
=> [gui/reveal] more explanation of what is happening

internal/caravan/common.lua, internal/caravan/pedestal.lua, internal/confirm/specs.lua, internal/quickfort/zone.lua, modtools/create-unit.lua
depends on https://github.com/DFHack/dfhack/pull/4170
=> move getCurrentSite from dfhack to world

changelog.txt, docs/gui/embark-anywhere.rst, gui/embark-anywhere.lua
Fixes: https://github.com/DFHack/dfhack/issues/3805
=> convert embark-anywhere prototype into an interface

docs/gui/reveal.rst, gui/reveal.lua
Fixes: https://github.com/DFHack/dfhack/issues/4185
=> [gui/reveal] add note about graphics mode to docs and ui

changelog.txt, internal/caravan/movegoods.lua
not just the ones that are displayed with current filters
note this still doesn't check non-current settings for group_items and inside_containers, but I think that is appropriate
=> [caravan] check all trade goods on close

changelog.txt, makeown.lua, modtools/create-unit.lua
ref: https://github.com/DFHack/df-structures/pull/684
=> [makeown] fix field names changed in structures update

control-panel.lua, gui/control-panel.lua, internal/control-panel/common.lua, internal/control-panel/registry.lua
depends on https://github.com/DFHack/dfhack/pull/4260
=> [control-panel] add tweak tweaks to control panel

changelog.txt, exportlegends.lua
and stabilize text formatting so the percent number doesn't jump around as the type of thing that is being exported changes
=> [exportlegends] add 2 digits of precision to progress percentage

internal/control-panel/registry.lua
=> Add tweak/flask-contents to control panel registry

changelog.txt, docs/source.rst, source.lua
the list was sometimes being used as a map, which was interrupting the sequence
=> [source] fix removing sources interrupting the list

changelog.txt, exportlegends.lua
that is, increase the displayed progress smoothly instead of jumping in large amounts and then stopping dead while exporting historical events
=> [exportlegends] smooth displayed progress bar over the entire export

changelog.txt, docs/gui/petitions.rst, gui/petitions.lua, list-agreements.lua
and prep for use by gui/notify
=> [gui/petitions] reinstate

changelog.txt, warn-stranded.lua
Issue found by Rurik - Thanks!
=> [warn-stranded] skip miners instead of adding them to the ignored list

changelog.txt, docs/list-waves.rst, list-waves.lua
=> reinstate list-waves

changelog.txt, docs/make-legendary.rst, make-legendary.lua
=> reinstate make-legendary

add-thought.lua, changelog.txt, docs/add-thought.rst
=> reinstate add-thought

changelog.txt, internal/caravan/movegoods.lua
on the move goods to depot screen
ref: https://discord.com/channels/793331351645323264/807444467140788254/1208003223294709811
=> [caravan] correctly display value into the millions

gui/notify.lua, internal/notify/notifications.lua
and move overlay up a bit so it doesn't conflict with the vanilla "following" panel
=> [gui/notify] fix "trader ready" detection logic

changelog.txt, internal/caravan/common.lua
instead of scroll descriptions
=> [caravan] display book titles in trade screens

gui/notify.lua, internal/notify/notifications.lua
also should catch invaders once they start to flee
=> [gui/notify] add notification for non-invader hostiles

exportlegends.lua
Fixes https://github.com/DFHack/dfhack/issues/4283
=> [exportlegends] fix refactoring typo

internal/confirm/specs.lua
needs to interact with new widgets to determine which unit is being convicted
note that merging this will make this confirmation prompt incompatible with 50.11, which is also building from this scripts branch. we're (probably) very close to 50.12, though, so this *shouldn't* matter. As long as we don't push any more 50.11 builds to Steam (which we have no plans to do), we should be ok.
=> [confirm] update conviction confirmation for 50.12

changelog.txt, docs/item.rst, item.lua
=> [item] move description from option to positional

changelog.txt, gui/mod-manager.lua
also print out list of failed mods in the warning dialog
=> [gui/mod-manager] automatically unmark default mod profile if it fails to load

changelog.txt, devel/input-monitor.lua, docs/devel/input-monitor.rst
=> add devel/input-monitor; interactive input debugger

internal/confirm/specs.lua
Reverts DFHack/scripts#993 since we *are* doing another 50.11 release
=> Revert "[confirm] update conviction confirmation for 50.12"

internal/confirm/specs.lua
Reverts DFHack/scripts#1012
restore 50.12 compatibility after 50.11-r7 release is tagged
=> Revert "Revert "[confirm] update conviction confirmation for 50.12""

changelog.txt, docs/gui/settings-manager.rst, gui/settings-manager.lua, internal/control-panel/registry.lua
Fixes: https://github.com/DFHack/dfhack/issues/4253
=> [gui/settings-manager] implement import/export/autoload for work details

gui/launcher.lua
depends on https://github.com/DFHack/dfhack/pull/4323
=> [gui/launcher] fix initial incorrect armok filter setting and make tag match all

changelog.txt, gui/notify.lua
Fixes https://github.com/DFHack/dfhack/issues/4324
=> [gui/notify] persist config state when changed

build-now.lua
=> Remove obsolete code from build-now.lua

changelog.txt, docs/exterminate.rst, exterminate.lua
makes the command much less picky about input formatting
Fixes: https://github.com/DFHack/dfhack/issues/4304
=> [exterminate] make race name matching case and space insensitive

gui/mod-manager.lua
Made get_newregion_viewscreen and get_modlist_fields global, so that mod related data is accessible through the dfhack api.
=> Made two functions global for third party use.

changelog.txt, docs/instruments.rst, instruments.lua
This tool provides information on how to craft the instruments used by the player civilization.
=> new tool: instruments

changelog.txt, devel/tile-browser.lua, docs/devel/tile-browser.rst
SDL2 normalizes the size of textures; we only have to handle 1x1
=> [devel/tile-browser] simplify code now that we don't have to handle large textures

internal/control-panel/registry.lua
ref: https://github.com/DFHack/dfhack/pull/4343
=> [control-panel] add logistics autoretrain to the registry

changelog.txt, internal/control-panel/common.lua
=> [control-panel] quiet tweak

changelog.txt, docs/gui/launcher.rst, gui/launcher.lua
- support `clear` and `cls` commands
- add a button for clearing the scrollback
=> [gui/launcher] add support for clearing the scrollback buffer

agitation-rebalance.lua, changelog.txt, docs/agitation-rebalance.rst, docs/exterminate.rst, exterminate.lua, internal/control-panel/registry.lua
gameplay mod: change the behavior of irritation attacks so that attacks do not continue if you do not continue to irritate nature
=> new tool: agitation-rebalance

agitation-rebalance.lua
keep statistics and add an optional debug monitor panel
=> [agitation-rebalance]

catsplosion.lua, changelog.txt, docs/catsplosion.rst
Fixes https://github.com/DFHack/dfhack/issues/4263
=> [catsplosion] only cause pregnancies in adults

changelog.txt, docs/modtools/item-trigger.rst, modtools/item-trigger.lua
clean up docs, reformat code, no behavior changes
=> reinstate modtools/item-trigger

changelog.txt, docs/gui/gm-editor.rst, gui/gm-editor.lua
also add that big fat warning we discussed earlier about gui/gm-editor crashing when viewing deallocated data
=> [gui/gm-editor] support directly opening engravings

changelog.txt, docs/gui/notify.rst, gui/notify.lua, internal/notify/notifications.lua
so if you miss the unit you want in a long list, it's easy to go back
=> [gui/notify] shift click/enter to zoom to previous target

agitation-rebalance.lua, docs/agitation-rebalance.rst
- proactively deter invasions before they spawn
- fix displayed chances of cavern invasion (was using fb chances)
- separately display fb chances
- update docs
=> agitation-rebalance v2

changelog.txt, prioritize.lua
also add ChainAnimal and FillPond to default prioritization list
ref: https://discord.com/channels/329272032778780672/1069640085718450218/1217597416291827733
=> [prioritize] output job names in same format as commandline

fix/drop-webs.lua, full-heal.lua, internal/caravan/movegoods.lua, internal/caravan/pedestal.lua, makeown.lua
depends on https://github.com/DFHack/df-structures/pull/734
=> use newly named fields

agitation-rebalance.lua, docs/agitation-rebalance.rst
and proactively remove invasions if we're already over the invader limit
=> [agitation-rebalance] reformat monitor panel

agitation-rebalance.lua
- fix typo in tracking when a new invasion has happened
- change global key back to v1 string so beta players won't lose their state
- more protection against spoiling when cavern invasions have happened
=> [agitation-rebalance] only throttle invasions once per season

changelog.txt
Add changelog entry for fix/noexert-exhaustion
=> Add changelog entry for fix/noexert-exhaustion

changelog.txt, docs/gui/quickfort.rst, docs/quickfort.rst, gui/quickfort.lua, internal/quickfort/api.lua, internal/quickfort/command.lua, internal/quickfort/dig.lua
the other half of https://github.com/DFHack/dfhack/pull/4405
also incidentally fix the issue where you couldn't click on the "mini" hotkeys for repeat and transform
=> [quickfort] support options for warm and damp dig

changelog.txt, fix/loyaltycascade.lua
Fixes https://github.com/DFHack/dfhack/issues/4407
=> [fix/loyaltycascade] use find instead of direct array lookup

changelog.txt, docs/gui/reveal.rst, gui/reveal.lua
and add aquifer-only mode for people who only want to see where the aquifers are and not reveal the whole map
=> [gui/reveal] integrate with warmdamp aquifer visualization

armoks-blessing.lua, changelog.txt
Fixes https://github.com/DFHack/dfhack/issues/4435
=> [armoks-blessing] don't bork on missing names for unused skills

changelog.txt, gui/launcher.lua
when run from minimal mode
Fixes logic broken by https://github.com/DFHack/scripts/pull/1032
=> [gui/launcher] don't pop up a content-free dialog if a command has no output

changelog.txt, open-legends.lua
Fixes https://github.com/DFHack/dfhack/issues/4463
I was trying to be all sleek and fancy by not using ZScreen. I should have used ZScreen.
=> [open-legends] unbork scrollbars

docs/item.rst
and clean up some doc formatting
=> [item] document verbose option

changelog.txt, docs/gui/quantum.rst, gui/quantum.lua, test/gui/quantum.lua
with shaded highlighting of selected stockpiles w00t
=> reinstate gui/quantum

changelog.txt, gui/create-item.lua, modtools/create-item.lua
as discussed on [Discord](https://discord.com/channels/793331351645323264/807444467140788254/1231382262256369715)
=> [gui/create-item] update filters for bags, shoes, and gloves

changelog.txt, internal/gm-unit/editor_body.lua
Fixes https://github.com/DFHack/dfhack/issues/4486
=> [gui/gm-unit] refresh the portrait when changing body parameters

changelog.txt, gui/quantum.lua
Fixes: https://github.com/DFHack/dfhack/issues/4510
=> [gui/quantum] fix output stockpile type for stockpiles

changelog.txt, gui/unit-info-viewer.lua
Fixes https://github.com/DFHack/dfhack/issues/4511
=> [deathcause] fix module inclusion

changelog.txt, combine.lua, docs/combine.rst
and artificially lower the barrel capacity for drinks so it can only contain 25 instead of 100, which is just too many and is causing complaints
Fixes: https://github.com/DFHack/dfhack/issues/4377
=> [combine] respect container volume limits

internal/caravan/common.lua, internal/caravan/movegoods.lua, internal/caravan/pedestal.lua, internal/caravan/trade.lua, item.lua
depends on https://github.com/DFHack/dfhack/pull/4521
=> [various] use new getReadableDescription API

changelog.txt, gui/launcher.lua
Fixes: https://github.com/DFHack/dfhack/issues/4512
=> [gui/launcher] add button for copying output to clipboard

changelog.txt, modtools/create-item.lua
Requires dfhack/dfhack#4488
Fixes dfhack/dfhack#2063
=> [modtools/create-item] - adjust for createItem API

gui/blueprint.lua
add 'name' label and colons to all labels
Fixes: https://github.com/DFHack/dfhack/issues/4524
=> [gui/blueprint] better label formatting

deathcause.lua
Fixes: https://github.com/DFHack/dfhack/issues/4513
=> [deathcause] better error message when a non-corpse item is selected

changelog.txt, docs/instruments.rst, instruments.lua, workorder.lua
Add a subcommand to instruments for creating instrument work orders
=> Add instruments order

changelog.txt, deathcause.lua
and overall better selection of corpse items when the choice is ambiguous
ref: comments in https://github.com/DFHack/dfhack/issues/4513
=> [deathcause] handle vermin remains

assign-minecarts.lua, changelog.txt, gui/quantum.lua
Fixes https://github.com/DFHack/dfhack/issues/4529
=> [gui/quantum] make minecart ordering/attaching optional

internal/quickfort/build.lua, internal/quickfort/place.lua
as per https://github.com/DFHack/dfhack/pull/4544
=> [quickfort] conform to new stockpiles API

changelog.txt, docs/gui/reveal.rst, gui/reveal.lua
ref: https://github.com/DFHack/dfhack/pull/4553
=> update gui/reveal for adventure mode

changelog.txt, docs/fix/engravings.lua, docs/fix/engravings.rst, engravings.lua, fix/engravings.lua, internal/control-panel/registry.lua
Fixes: https://github.com/DFHack/dfhack/issues/4421
=> fix engravings that have gone out of sync

modtools/create-item.lua
Fixes: https://github.com/DFHack/dfhack/issues/4552
=> [modtools/create-item] lua lists start at 1

changelog.txt, docs/gui/quantum.rst, gui/quantum.lua, test/gui/quantum.lua
Fixes https://github.com/DFHack/dfhack/issues/4518
=> [gui/quantum] allow multiple stockpiles to be linked to the QSP

changelog.txt, internal/quickfort/build.lua
was failing when all adjacent tiles were occupied by buildings
=> [quickfort] fix detection of valid well tiles

internal/control-panel/registry.lua
ref: https://github.com/DFHack/dfhack/pull/4585
=> [control-panel] enable tweak named-codices by default

changelog.txt, docs/gui/sitemap.rst, gui/sitemap.lua
whereupon the need for such a tool was made apparent on [Reddit](https://www.reddit.com/r/dwarffortress/comments/1cpe1kx/comment/l3km57e/?utm_source=share&utm_medium=web2x&context=3)
=> initial version of gui/sitemap

break-dance.lua, cannibalism.lua, gui/companion-order.lua, launch.lua
ref: https://github.com/DFHack/dfhack/issues/4603
=> convert usage of units.active[0] to getAdventurer()

gui/civ-alert.lua
depends on https://github.com/DFHack/dfhack/pull/4610
=> [gui/civ-alert] use new button text API

docs/combine.rst
salvage usable bits from https://github.com/DFHack/scripts/pull/852
=> [combine] editing pass for docs

changelog.txt, gui/autodump.lua, gui/blueprint.lua, gui/design.lua, gui/mass-remove.lua, gui/teleport.lua
and display it when building
requires: https://github.com/DFHack/dfhack/pull/4614
=> use new reusable dimensions widget

deep-embark.lua, open-legends.lua, quicksave.lua, toggle-kbd-cursor.lua, twaterlvl.lua
ref: https://github.com/DFHack/df-structures/pull/764
separate PRs coming for pop-control and friends, which needs a more involved rewrite
=> update to new d_init structure layout

docs/open-legends.rst, open-legends.lua
as per discussion on [Discord](https://discord.com/channels/793331351645323264/807443277132595211/1245869249801748650)
=> [open-legends] adjust the warning dialog for adventure mode

assign-preferences.lua, ban-cooking.lua, combine.lua, deteriorate.lua, devel/tree-info.lua, extinguish.lua, gui/create-item.lua, internal/quickfort/build.lua, modtools/create-item.lua, modtools/reaction-trigger-transition.lua
ref: https://github.com/DFHack/df-structures/pull/772
=> update to canonicalized field names

changelog.txt, gui/design.lua, internal/design/shapes.lua, internal/design/util.lua
and lots of bugfixing along the way
=> [gui/design] UI/UX redesign

build-now.lua, feature.lua, gui/advfort.lua, gui/tiletypes.lua, gui/workshop-job.lua, internal/advfort/advfort_items.lua, internal/dwarf-op/dorf_tables.lua, internal/quickfort/stockflow.lua, modtools/create-unit.lua, sync-windmills.lua, workorder.lua
ref: https://github.com/DFHack/df-structures/pull/774
=> use canonicalized structures and field names

ban-cooking.lua, gui/settings-manager.lua
ref: https://github.com/DFHack/df-structures/pull/777
=> adapt to structures updates

gui/tiletypes.lua
A couple of fixes for the BoxSelection widget
- Option to disable the DimensionsTooltip
- Issue with selection tiles not rendering correctly
- A couple minor edits to formatting and type definitions
=> BoxSelection fixes

changelog.txt, gui/launcher.lua
depends on https://github.com/DFHack/dfhack/pull/4680
=> allow tag filter to be poked when mortal mode is toggled

gui/tiletypes.lua
Adds the new `surroundings` option from DFHack/dfhack#4670 to `gui/tiletypes`
=> Add new surroundings option for gui/tiletypes

gui/launcher.lua
so core doesn't have to call `gui/launcher` (see https://github.com/DFHack/dfhack/pull/4684)
=> [gui/launcher] watch for changes in armok mode

changelog.txt, gui/sandbox.lua, makeown.lua
now use DF API endpoint to create hist fig and nemesis and do some basic makeown tasks
fixed:
- adding elements to end of list instead of in sorted order
- not removing ids from removed historical entities
Fixes: https://github.com/DFHack/dfhack/issues/4625
Fixes: https://github.com/DFHack/dfhack/issues/3490
=> [makeown] use DF native endpoint, fix bugs

changelog.txt, internal/notify/notifications.lua
special extra warning if you don't have a functional hospital
Fixes: https://github.com/DFHack/dfhack/issues/4682
=> [gui/notify] notify on injured citizens

changelog.txt, docs/prioritize.rst, prioritize.lua
and do_job_now integration
Fixes: https://github.com/DFHack/dfhack/issues/3169
=> [prioritize] job status panel for under-construction buildlings

changelog.txt, gui/unit-info-viewer.lua
depends on https://github.com/DFHack/dfhack/pull/4688 for locale-specific number formatting
=> [gui/unit-info-viewer] add precise unit sizes in cc

changelog.txt, docs/gui/civ-alert.rst, gui/civ-alert.lua, internal/quickfort/burrow.lua
FYI @ab9rf 
Fixes: https://github.com/DFHack/dfhack/issues/4409
=> [gui/civ-alert] multi-burrow

changelog.txt, internal/caravan/common.lua, internal/caravan/movegoods.lua
Fixes: https://github.com/DFHack/dfhack/issues/4313
this changes the UX of the dialog enough that we should seek beta feedback on whether this is the right improvement
=> [caravan] show distance to depot in bring goods to depot screen

colonies.lua, deep-embark.lua, do-job-now.lua, exportlegends.lua, extinguish.lua, firestarter.lua, fix/engravings.lua, gui/advfort.lua, gui/extended-status.lua, gui/gm-editor.lua, gui/sitemap.lua, internal/quickfort/dig.lua, internal/quickfort/stockflow.lua, open-legends.lua, test/gui/workorder-details.lua, workorder.lua
ref: https://github.com/DFHack/df-structures/pull/780
=> adapt to canonicalized structures

changelog.txt, gui/design.lua, internal/design/shapes.lua
now matches the more popular curvature of `digcircle`
=> [gui/design] keep ui from getting into invalid states and make circles more circular

changelog.txt, gui/control-panel.lua, internal/control-panel/registry.lua
depends on https://github.com/DFHack/dfhack/pull/4705
=> [gui/control-panel] make number format a preference

changelog.txt, docs/gui/notify.rst, gui/notify.lua, internal/notify/notifications.lua
in preparation for https://github.com/DFHack/scripts/pull/1174 and blood loss meter
=> prepare gui/notify for adventure mode

gui/control-panel.lua, internal/control-panel/registry.lua
=> [gui/control-panel] give descriptive choices for formatting

internal/caravan/common.lua
=> [caravan] use preferred number formatting for prices

changelog.txt, docs/suspend.rst, suspend.lua
=> fixed broken suspend script / remove --onlyblocking option (fixes #4717)

deteriorate.lua, devel/nuke-items.lua, full-heal.lua, gui/autodump.lua, modtools/invader-item-destroyer.lua
instead of just marking for garbage collection directly
instigated by https://github.com/DFHack/scripts/pull/1187
=> use the more robust item removal method

devel/export-dt-ini.lua
see https://github.com/DFHack/scripts/commit/d129d7260f1852c8123dce2a650579595393d96e#r143280613
=> update export-dt-ini for new names

gui/tiletypes.lua
Removes the vein type option from `gui/tiletypes`
=> Remove vein type option from `gui/tiletypes`

gui/tiletypes.lua
Rename `surroundings` to autocorrect
Linked to DFHack/dfhack#4735
=> Rename surroundings to autocorrect

confirm.lua, gui/design.lua, gui/gm-editor.lua, gui/launcher.lua, gui/overlay.lua, internal/advtools/convo.lua, internal/caravan/pedestal.lua, internal/confirm/specs.lua, open-legends.lua, startdwarf.lua, trackstop.lua
for when max_interface_percentage is set
requires: https://github.com/DFHack/dfhack/pull/4739
ref: https://github.com/DFHack/dfhack/issues/4419
=> behave properly on scaled interface widths

docs/gui/tiletypes.rst, gui/tiletypes.lua
Fixes the "More Options" menu to have consistent ordering.
Hides values that have a greater level of complexity
Block some invalid combinations that were previously allowed
=> Fix ordering, hide values, and block invalid combos

changelog.txt, docs/gui/pathable.rst, gui/pathable.lua
ref: https://github.com/DFHack/dfhack/pull/4741
ref: https://github.com/DFHack/dfhack/issues/3230
=> [gui/pathable] highlight trade depot accessibility for wagons

gui/sandbox.lua
it crashes the game (sometimes) and resets visiblity in fort mode (always)
Fixes: https://github.com/DFHack/dfhack/issues/4747
Fixes: https://github.com/DFHack/dfhack/issues/4737
=> [gui/sandbox] don't let the "assume control of unit" button

timestream.lua
was making fort animals dehydrate to death
=> [timestream] fixes

timestream.lua
depends on https://github.com/DFHack/dfhack/pull/4771
=> [timestream] use new unpaused FPS tracker

deep-embark.lua
Fixes https://github.com/DFHack/dfhack/issues/4770
=> [deep-embark] use canonicalized structures

changelog.txt, docs/prioritize.rst, prioritize.lua
also list all jobs for --jobs
and autofix bad keys when listing status
Fixes: https://github.com/DFHack/dfhack/issues/4774
=> [prioritize] boost all jobs, not just unclaimed ones

changelog.txt, internal/gm-unit/editor_body.lua, internal/gm-unit/editor_colors.lua
used to error and break on rng rolls, etc. now it works
in a different PR this code should be overhauled, the amount of copy-pasting of helper functions is making babies cry.
=> Fix gui/gm-editor appearance editing

advtools.lua, internal/advtools/party.lua
Also forbid advtools command from being run outside adventure mode
=> Fix advtools party not importing properly

internal/advtools/convo.lua
choice -> cc -> choice var changing happened :(
=> Fix extra choice options not showing up for advtools convo

changelog.txt, full-heal.lua
Fixes: https://github.com/DFHack/dfhack/issues/4788
=> [full-heal] check dead citizens when resurrecting citizens

unretire-anyone.lua
Fix unretire-anyone --dead reviving ALL historical figures in the world!!
Also fix https://github.com/DFHack/dfhack/issues/4789
Also makes the list prettier:
=> Fix unretire-anyone reviving everything + vector misalignment error

changelog.txt, open-legends.lua
Fixes: https://github.com/DFHack/dfhack/issues/4790
=> [open-legends] don't intercept text

changelog.txt, internal/unit-info-viewer/skills-progress.lua
Discussed in DFHack Support channel in Discord
=> Fix skills-progress, use correct field for rust

build-now.lua, changelog.txt
also unsuspend before scanning for buildings
=> [build-now] designed flag is gone; don't try to set it

changelog.txt, fix/dead-units.lua
=> [fix/dead-units] don't modify container while iterating through it

fix/empty-wheelbarrows.lua
=> [fix/empty-wheelbarrows] cancel jobs involving items in wheelbarrows before moving them

agitation-rebalance.lua, changelog.txt, docs/exterminate.rst, emigration.lua, exterminate.lua, gui/sitemap.lua, internal/notify/notifications.lua
add some annotations for units in gui/sitemap
clean up exterminate
Depends on https://github.com/DFHack/dfhack/pull/4850
Fixes: https://github.com/DFHack/dfhack/issues/4845
=> use new unit module property functions

docs/embark-anyone.rst
Adds a line to the description of embark-anyone mentioning add-recipe.
=> Add note mentioning add-recipe

changelog.txt, docs/gui/pregnancy.rst, gui/pregnancy.lua
also add confirmation dialogs for disruptive actions, such as choosing a partner from a different race, which clears the selected unit
Fixes: https://github.com/DFHack/dfhack/issues/4818
=> [gui/pregnancy] set or clear spouse relationships

gui/seedwatch.lua
and to not imply that the "all" threshold is saved somewhere
Fixes: https://github.com/DFHack/dfhack/issues/4878
=> rework gui/seedwatch UI to support sorting

changelog.txt, docs/exportlegends.rst, exportlegends.lua, internal/exportlegends/asyncexport.lua, internal/exportlegends/racefilter.lua
and refactor exportlegends overlays into separate files
and fix missed export start when Export XML button is clicked but the user has already navigated to a subpage
=> [exportlegends] add race filter on histfig page

idle-crafting.lua
depends on https://github.com/DFHack/dfhack/pull/4921
=> hide panel when assigning someone to the workshop

idle-crafting.lua
=> [idle-crafting] add help button for idle-crafting overlay

changelog.txt, docs/fix/ownership.rst, fix/ownership.lua
Fixes https://dwarffortressbugtracker.com/view.php?id=6578
=> [fix/ownership] check and fix room ownership links

changelog.txt, exterminate.lua
and sort generated race names by number
=> [exterminate] display actual names for unique beasts

changelog.txt, docs/idle-crafting.rst, idle-crafting.lua
(for workshops with linked input stockpiles)
[Asked for on Discord](https://discord.com/channels/793331351645323264/793331351645323267/1288812678151929858)
=> `idle-crafting`: also support making shell crafts 

changelog.txt, internal/control-panel/registry.lua
Add realistic-melting tweak from https://github.com/DFHack/dfhack/pull/4958 to control-panel registry
=> Add realistic-melting tweak to control-panel registry

changelog.txt, internal/control-panel/common.lua
to avoid an unwarranted error message
=> [control-panel] convert numeric strings to numbers for numeric preferences

uniform-unstick.lua
=> [uniform-unstick] redo layout of conflict report dialog

internal/notify/notifications.lua
now that the underlying issue in isDanger is fixed
ref: https://github.com/DFHack/dfhack/pull/5076
=> [gui/notify] revert hostile notification fix

docs/fix/stuck-squad.rst, fix/stuck-squad.lua, internal/notify/notifications.lua
thanks, Rumrusher, for the idea!
=> [fix/stuck-squad] allow messengers to rescue stuck squads

internal/gm-unit/editor_profession.lua
ref: https://discord.com/channels/793331351645323264/807444467140788254/1323465248510054401
=> [gui/gm-unit] also set prof of hf when changing profession

changelog.txt, docs/gui/rename.rst, gui/rename.lua, gui/sitemap.lua
rename things with an interface similar to the vanilla word selector
also add an overlay that launches the tool to rename the world at the end of worldgen
Fixes: https://github.com/DFHack/dfhack/issues/4963
Fixes: https://github.com/DFHack/dfhack/issues/843
=> new tool: `gui/rename`

changelog.txt, docs/gui/rename.rst, gui/rename.lua
Fixes: https://github.com/DFHack/dfhack/issues/2997
Fixes: https://github.com/DFHack/dfhack/issues/5173
=> [gui/rename] allow units to be given nicknames on the embark screen

gui/rename.lua
Fixes: https://github.com/DFHack/dfhack/issues/5184
@quietust Does the `get_word_selectors` function look correct?
=> [gui/rename] refactor for handling word selectors, add word selector selector

changelog.txt, deathcause.lua
Fixes: https://github.com/DFHack/dfhack/issues/5205
=> [deathcause] fix typo in API call

gui/manipulator.lua
no changelog since this isn't a released feature yet
=> [gui/manipulator] use the new setAutomaticProfessions endpoint

gui/spectate.lua
=> spectate.lua: add activity

fix/ownership.lua
ref: https://github.com/DFHack/dfhack/pull/5413
=> use new assigned_unit API for 51.11

changelog.txt, gui/mod-manager.lua
=> `gui/mod-manager`: Hide other versions of loaded mods

husbandry.lua
(no changelog as covered in prior log)
=> fix enable/disable in husbandry
